### ISSUE TITLE
NotImplementedException while trying to load VGG19

### ISSUE THREAD

**Issue by individ2016** [SciSharp/TensorFlow.NET#1013]
I'm trying to load VGG19 model from https://huggingface.co/keras-io/VGG19 and get NotImplementedException in method Tensorflow.Keras.Saving.KerasObjectLoader._infer_inputs(int layer_node_id, bool convert_to_shapes = false)

help please)

code is simple:

var model = keras.models.load_model("./vgg19");
model.summary();

P.S. if it is important - im using SciSharp.TensorFlow.Redist-Windows-GPU package

**Comment by AsakusaRinne** [comment]
Hi, sorry for the late response. The support of loading model in v0.100.4 is not complete. I was developing it rapidly recently. I'll tell you once I finish it :)

**Comment by individ2016** [comment]
I will be here waiting) Thank you!

**Comment by AsakusaRinne** [comment]
The loading of VGG19 has been fixed. Now it works with the model in the link. 

The following is an example:

```cs
        var model = tf.keras.models.load_model(@"model path");
        model.summary();

        var classify_model = keras.Sequential(new System.Collections.Generic.List<Tensorflow.Keras.ILayer>()
        {
            model,
            keras.layers.Flatten(),
            keras.layers.Dense(10),
        });
        classify_model.summary();

        classify_model.compile(tf.keras.optimizers.Adam(), tf.keras.losses.SparseCategoricalCrossentropy(), new string[] { "accuracy" });

        var x = np.random.uniform(0, 1, (8, 512, 512, 3));
        var y = np.ones((8));

        classify_model.fit(x, y, batch_size: 4);
```

**Comment by individ2016** [comment]
thank you a lot) will try it soon)
