### ISSUE TITLE
[BUG Report]: Reshape may not be sizing properly with SequenceLength when creating layer

### ISSUE THREAD

**Issue by GadgetNutt** [SciSharp/TensorFlow.NET#1045]
### Description

I believe the  initial function parameter for Reshape isn't taking into consideration the SequenceLength and as a result isn't sizing the array properly.

        Dim denseLayer = layers.Dense(512, activation:=keras.activations.Relu)
        Dim denseOutput = denseLayer.Apply(inputLayer)

        Dim dropoutLayer1 = layers.Dropout(0.3)
        Dim dropoutOutput1 = dropoutLayer1.Apply(denseOutput)

        Dim reshapeLayer = layers.Reshape(New Integer() {SequenceLength, 512})
        Dim reshapeOutput = reshapeLayer.Apply(dropoutOutput1)

        Dim conv1DLayer = layers.Conv1D(128, kernel_size:=3, activation:="relu")
        Dim conv1DOutput = conv1DLayer.Apply(reshapeOutput)

Tries to compare 131072 with 7864320 (my sequence length is 60).  Present work around is to set SequenceLength to 1.
(maybe I'm using it wrong?)

### Known Workarounds

Set SequenceLength to 1.

### Configuration and Other Information

Windows 11
VS2022
.NET6
TF.NET 0.100.4
TensorFlow.Keras 0.10.4
SciSharp.TensorFlow.Redist 2.11.3

**Comment by AsakusaRinne** [comment]
Hi, thanks for reporting us it. I tried it but the error didn't appear. According to the code, the output shape of `denseLayer` is `(n, 512)`, in which `n` is the batchsize of your input shape `(n, m)`. Then you reshape it to `(60, 512)`. Therefore unless n = 1, the reshaping will fail. So I guess maybe the error is from the reshaping because your input shape is only `(1, m)` or `(m)`?

If the error still appeared, please tell us about the input layer information in your code. :)

**Comment by GadgetNutt** [comment]
Are you sure that is correct?  I'm under the understanding that the Conv1D layer should expect an input shape that includes the SequenceLength (number of time steps) and the number of features in the input data instead of the BatchSize value as a parameter.  I understand that it should be like this for other layers, LSTM also,  particularly layers that work with sequential or time-series data.

Is my understanding incorrect?

**Comment by AsakusaRinne** [comment]
Conv1D itself is now aware of `SequentialLength`, here is a good introduction of conv1D (https://towardsdatascience.com/understanding-1d-and-3d-convolution-neural-network-keras-9d8f76e29610). When applying conv1D, the kernel just go along the X axis and calculate the result of Convolution (which is actually a multiply-sum process). The `SequentialLength` you mentioned may be a concept in your project, however Conv1D just does what it should do and cannot fully understand the meaning of the shape.

I wrote the following code in tensorflow python and it works:

```py
    input_layer = tf.keras.layers.Input([60, 128]) # If the number "60" is replaced with other numbers, the code will throw an exception when reshaping the data.
    dense_layer = tf.keras.layers.Dense(512, 'relu')
    dense_output = dense_layer(input_layer)

    dropout_layer = tf.keras.layers.Dropout(0.3)
    dropout_output = dropout_layer(dense_output)

    reshape_layer = tf.keras.layers.Reshape([60, 512])
    reshape_output = reshape_layer(dropout_output)

    conv1d_layer = tf.keras.layers.Conv1D(128, kernel_size=3, activation='relu')
    conv1d_output = conv1d_layer(reshape_output)
```

I also wrote similar codes in C# and it works.

I'm not familiar with your research area or project. What I can do for you is to make Conv1D work well. Could you please confirm again that if the error throws when you run the Conv1D layer? I guess the error may come from the reshaping layer.

**Comment by GadgetNutt** [comment]
My mistake, I'm sorry.   You are right, the error was from the Reshaping layer.  When SequenceLength is set to 60 in this code in VB.NET it fails.

<code>
        Dim inputLayer = layers.Input(New Integer() {SequenceLength, InputFeatures}, batchSize,, dtype:=TF_DataType.TF_FLOAT)

        Dim denseLayer = layers.Dense(512, activation:=keras.activations.Relu)
        Dim denseOutput = denseLayer.Apply(inputLayer)

        Dim dropoutLayer1 = layers.Dropout(0)
        Dim dropoutOutput1 = dropoutLayer1.Apply(denseOutput)

        Dim reshapeLayer = layers.Reshape(New Integer() {SequenceLength, 512})
        Dim reshapeOutput = reshapeLayer.Apply(dropoutOutput1)

        Dim conv1DLayer = layers.Conv1D(2048, kernel_size:=1, activation:="relu")
        Dim conv1DOutput = conv1DLayer.Apply(reshapeOutput)

        Dim flattenLayer = layers.Flatten()
        Dim flattenOutput = flattenLayer.Apply(conv1DOutput)

        Dim dropoutLayer2 = layers.Dropout(0.03)
        Dim dropoutOutput2 = dropoutLayer2.Apply(flattenOutput)

        Dim denseLayer2 = layers.Dense(1024, activation:="relu")
        Dim denseOutput2 = denseLayer2.Apply(dropoutOutput2)

        Dim outputLayer = layers.Dense(OutputFeatures)
        Dim output = outputLayer.Apply(denseOutput2)

        ' Compile the neural network model
        Me.Model = keras.Model(inputs:=inputLayer, outputs:=output)
        Me.Model.compile(optimizer:=keras.optimizers.Adam(learning_rate:=0.009), loss:=New MeanSquaredError(), metrics:=New String() {})
</code>

**Comment by GadgetNutt** [comment]
Here is the kind of error I get with the SequenceLength set to 60:

Tensorflow.InvalidArgumentError: 'Input to reshape is a tensor with 16384 values, but the requested shape has 983040'

Here is the stack trace:
   at Tensorflow.Eager.EagerRunner.TFE_FastPathExecute(FastPathOpExecInfo op_exec_info)
   at Tensorflow.Contexts.Context.ExecEagerAction(String OpType, String Name, ExecuteOpArgs args)
   at Tensorflow.Contexts.Context.ExecuteOp(String opType, String name, ExecuteOpArgs args)
   at Tensorflow.gen_array_ops.reshape[T](Tensor tensor, T shape, String name)
   at Tensorflow.Keras.Layers.Reshape.Call(Tensors inputs, Tensor state, Nullable`1 training)
   at Tensorflow.Keras.Engine.Layer.Apply(Tensors inputs, Tensor state, Boolean training)
   at Tensorflow.Keras.Engine.Functional.Call(Tensors inputs, Tensor state, Nullable`1 training)
   at Tensorflow.Keras.Engine.Layer.Apply(Tensors inputs, Tensor state, Boolean training)
   at Tensorflow.Keras.Engine.Model.train_step(DataHandler data_handler, Tensor x, Tensor y)
   at Tensorflow.Keras.Engine.Model.train_step_function(DataHandler data_handler, OwnedIterator iterator)
   at Tensorflow.Keras.Engine.Model.FitInternal(DataHandler data_handler, Int32 epochs, Int32 verbose, IDatasetV2 validation_data)
   at Tensorflow.Keras.Engine.Model.fit(NDArray x, NDArray y, Int32 batch_size, Int32 epochs, Int32 verbose, Single validation_split, Boolean shuffle, Int32 initial_epoch, Int32 max_queue_size, Int32 workers, Boolean use_multiprocessing)
   at Nutt_Trader.UberPriceForecastingNeuralNet.GPTBuildModel() in D:\OneDrive\Business\Trading\Nutt Trader\Current\Nutt Trader\UberPriceForecastingNeuralNet.vb:line 231
   at Nutt_Trader.UberPriceForecastingNeuralNet.BuildModel() in D:\OneDrive\Business\Trading\Nutt Trader\Current\Nutt Trader\UberPriceForecastingNeuralNet.vb:line 120
   at Nutt_Trader.UberPriceForecastingNeuralNet..ctor(Int32 sequenceLength, Int32 forecastLength, Int32 inputFeatures, Int32 outputFeatures, NeuralNetArgs args, Int32 numEpochs) in D:\OneDrive\Business\Trading\Nutt Trader\Current\Nutt Trader\UberPriceForecastingNeuralNet.vb:line 48
   at Nutt_Trader.AIEvalForm.Button1_Click(Object sender, EventArgs e) in D:\OneDrive\Business\Trading\Nutt Trader\Current\Nutt Trader\AIEvalForm.vb:line 45
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by AsakusaRinne** [comment]
What's your input shape?

**Comment by GadgetNutt** [comment]
Right now 11,11.  It's different from when I started this report.  It's been (17,11), (22,11), (16,11) and (11,11).  Same problem every time with the Reshape though.

**Comment by AsakusaRinne** [comment]
Assume that you use the code from the beginning and your input shape is (n, m), then the shapes of each layer is listed as below:

```vb
    Dim denseLayer = layers.Dense(512, activation:=keras.activations.Relu)
    Dim denseOutput = denseLayer.Apply(inputLayer) // (n, 512)

    Dim dropoutLayer1 = layers.Dropout(0.3)
    Dim dropoutOutput1 = dropoutLayer1.Apply(denseOutput) // (n, 512)

    Dim reshapeLayer = layers.Reshape(New Integer() {SequenceLength, 512})
    Dim reshapeOutput = reshapeLayer.Apply(dropoutOutput1) // (SequenceLength, 512)

    Dim conv1DLayer = layers.Conv1D(128, kernel_size:=3, activation:="relu")
    Dim conv1DOutput = conv1DLayer.Apply(reshapeOutput)
```

Reshaping requires the original shape and the target shape have exactly the same element count. Therefore according to the comments in the code block above, only `SequenceLength == n` is satisfied will the code work.

**Comment by GadgetNutt** [comment]
Sorry, maybe I'm not on the same page.

My initial input line:
 Dim inputLayer = layers.Input(New Integer() {SequenceLength, InputFeatures}, batchSize,, dtype:=TF_DataType.TF_FLOAT)  <-- (60,11)   SequenceLength = 60 , InputFeatures = 11

My second layer:
    Dim denseLayer = layers.Dense(512, activation:=keras.activations.Relu)   <--  I haven't changed the SequenceLength, so (60,512)

My third layer:
    Dim dropoutLayer1 = layers.Dropout(0)

My fourth layer:
   Dim reshapeLayer = layers.Reshape(New Integer() {SequenceLength, 512})  <--  SequenceLength = 60, so (60, 512)

This isn't working when SequenceLength = 60.  It only works when SequenceLength = 1.

**Comment by AsakusaRinne** [comment]
What's your batchsize in the args of InputLayer?

**Comment by GadgetNutt** [comment]
256

**Comment by AsakusaRinne** [comment]
It seems the code above is only a part of your code. Anyway, I think the code above is ok when compiling the model. Then when you use the `fit`, what is the input tensor shape?

**Comment by GadgetNutt** [comment]
THis is literally the whole sub:

<code>
    Private Sub BuildModel()
        ' Load and preprocess the data
        Dim features()() As Double
        Dim labels()() As Double
        Dim validationSplit As Single = 0.2F
        Dim layers = keras.layers
        Dim batchSize As Integer = 32

        LoadData(features, labels)
        Dim preparedDataAndLabels1 As List(Of NDArray) = PrepareData(ConvertToSinglePrecision(JaggedTo2DArray(features)), ConvertToSinglePrecision(JaggedTo2DArray(labels)))
        Dim x_train As NDArray = preparedDataAndLabels1.Item(0)
        Dim y_train As NDArray = preparedDataAndLabels1.Item(1)
        keras.backend.clear_session()
        ' Define the neural network model using Keras layers
        Dim inputLayer = layers.Input(New Integer() {SequenceLength, InputFeatures}, batchSize,, dtype:=TF_DataType.TF_FLOAT)

        Dim denseLayer = layers.Dense(512, activation:=keras.activations.Relu)
        Dim denseOutput = denseLayer.Apply(inputLayer)

        Dim dropoutLayer1 = layers.Dropout(0)
        Dim dropoutOutput1 = dropoutLayer1.Apply(denseOutput)

        Dim reshapeLayer = layers.Reshape(New Integer() {SequenceLength, 512})
        Dim reshapeOutput = reshapeLayer.Apply(dropoutOutput1)

        Dim conv1DLayer = layers.Conv1D(2048, kernel_size:=1, activation:="relu")
        Dim conv1DOutput = conv1DLayer.Apply(reshapeOutput)

        Dim flattenLayer = layers.Flatten()
        Dim flattenOutput = flattenLayer.Apply(conv1DOutput)

        Dim dropoutLayer2 = layers.Dropout(0.03)
        Dim dropoutOutput2 = dropoutLayer2.Apply(flattenOutput)

        Dim denseLayer2 = layers.Dense(1024, activation:="relu")
        Dim denseOutput2 = denseLayer2.Apply(dropoutOutput2)

        Dim outputLayer = layers.Dense(ForecastLength * OutputFeatures)
        Dim output = outputLayer.Apply(denseOutput2)

        'Dim outputLayer = layers.Dense(ForecastLength * OutputFeatures)


        ' Compile the neural network model
        Me.Model = keras.Model(inputs:=inputLayer, outputs:=output)
        Me.Model.compile(optimizer:=keras.optimizers.Adam(learning_rate:=0.009), loss:=New MeanSquaredError(), metrics:=New String() {})

        ' Train the neural network model using batch size
        Me.Model.fit(x_train, y_train, epochs:=m_Epochs, batch_size:=batchSize, verbose:=1, validation_split:=validationSplit)
    End Sub

</code>

**Comment by GadgetNutt** [comment]
And here is how I call it:
        Dim sequenceLength As Integer = 1
        Dim forecastLength As Integer = 1
        Dim inputFeatures As Integer = 11  ' Based on your initial feature set
        Dim outputFeatures As Integer = 11 ' Based on your initial label set

        ' Create a NeuralNetArgs object
        Dim args As New NeuralNetArgs()
        ' You can set other properties of the NeuralNetArgs object if necessary

        ' Initialize the UberPriceForecastingNeuralNet class
        Dim tmpEpochs As Integer = 0
        If textEpochs.Text <> "" AndAlso Val(textEpochs.Text) > 0 Then
            tmpEpochs = Val(textEpochs.Text)
        End If
        uberNet = New UberPriceForecastingNeuralNet(sequenceLength, forecastLength, inputFeatures, outputFeatures, args, tmpEpochs)
        'uberNet.LoadData()

**Comment by GadgetNutt** [comment]
> It seems the code above is only a part of your code. Anyway, I think the code above is ok when compiling the model. Then when you use the `fit`, what is the input tensor shape?

Yes, it is ok to compile.

x_train.Shape = {(885, 11)}
y_train.Shape = {(885, 11)}

**Comment by AsakusaRinne** [comment]
Well, since I'm not familiar with the purpose of your project, I can only give some of my guesses:

1. The shape of each single data is expected to be (60, 11), and you want to input a batch of it, which means you want to input many tensors with shape of (60, 11) at the same time.
2. The shape of each single data is expected to be (11), and 60 is the batch size you want to set during the training process.

If case 1 matches, then your `x_train` should be of shape (n, 60, 11), in which n is an arbitrary number. 

If case 2 matches, then you should set the shape of input layer to (11) and specify `batchsize=60` in the parameters of `model.fit`. Under this condition, please don't use reshaping or set `SequenceLength` to 1 to make it work.

**Comment by GadgetNutt** [comment]
Thank you.  The error is mine.  I misunderstood the application of SequenceLength in this instance.  I understand now.
