### ISSUE TITLE
[BUG Report]: v0.100.5 is not thread safe anymore

### ISSUE THREAD

**Issue by Superpiffer** [SciSharp/TensorFlow.NET#1066]
### Description

I have this exception in a multi thread application:
![image](https://github.com/SciSharp/TensorFlow.NET/assets/1334453/5ff211bb-2c28-42fa-9c96-5c158f7b73fb)

Apparently different threads tries to modify this Dictionary: https://github.com/SciSharp/TensorFlow.NET/blob/cd64ea96f31cce51405664023023db94de45f1e7/src/TensorFlowNET.Core/Device/DeviceSpec.cs#L10

### Reproduction Steps

Create more than one thread with a new instance of Session per thread:

```
private static void TestThreads()
{
    List<Thread> threads = new List<Thread>();

    const int THREADS_COUNT = 5;

    for(int t = 0; t < THREADS_COUNT; t++)
    {
        Thread thread = new Thread(() =>
        {
            Graph g = new Graph();
            g.Import("model.pb");
            Session session = new Session(g);
        });
        thread.Start();
        threads.Add(thread);
    }

    threads.ForEach(t => t.Join());
}
```

### Known Workarounds

I can bypass this issue using a ConcurrentDictionary, but I don't know if that's an ideal solution.

### Configuration and Other Information

Tensorflow.NET v0.100.5
.NET 6.0

**Comment by Oceania2018** [comment]
`ConcurrentDictionary` is the good approach. @AsakusaRinne
