### ISSUE TITLE
Rationale - The Second TensorFlowSharp

### ISSUE THREAD

**Issue by pkese** [SciSharp/TensorFlow.NET#107]
Please provide a rationale somewhere in the main README about how does this project compare to https://github.com/migueldeicaza/TensorFlowSharp  
...e.g what's wrong with the other project and how it is so impossible to fix that a new project was needed.

**Comment by Oceania2018** [comment]
Some points mentioned in https://github.com/SciSharp/Pandas.NET/issues/13

![image](https://user-images.githubusercontent.com/1705364/50908820-224c1100-13f0-11e9-91d2-f8f1e192d0b0.png)

**Comment by Oceania2018** [comment]
Check the latest README. Close this issue.
