### ISSUE TITLE
How to set a bidirectional layer?

### ISSUE THREAD

**Issue by IgnacioRodriguez98** [SciSharp/TensorFlow.NET#1099]
### Description

Hi, I built a bidirectional LSTM in python, but when I tried to set up a bidirectional layer, I couldn't find the bidirectional layer on tensorflow.net.

reading the tensorflow documentation it's supposed to be something like this

`tf.keras.layers.Bidirectional()`

but i didn't find it on tensorflow.net. Is it possible to set a bidirectional layer in tensorflow.net?

thanks for advance

**Comment by Wanglongzhi2001** [comment]
Sorry, bidirectional LSTM has not been developed in TensorFlow.NET, I'll let you know as soon as it's developed.

**Comment by IgnacioRodriguez98** [comment]
> Sorry, bidirectional LSTM has not been developed in TensorFlow.NET, I'll let you know as soon as it's developed.

I'll be on the lookout thanks

**Comment by Wanglongzhi2001** [comment]
Thank you for your interest in TensorFlow.NET.^_^

**Comment by Wanglongzhi2001** [comment]
Hello, I have implemented the bidirectional layer. ^_^
