### ISSUE TITLE
注释问题

### ISSUE THREAD

**Issue by wujun007** [SciSharp/TensorFlow.NET#1102]
由于第一次使用.net 框架下的TensorFlow 还是有很多不明白的地方，对于国人来说没有注释不太友好，我看了这个项目整体都不错，后期肯定也会大方光彩，期望后期的版本提升计算速度上的优化，增加注释这个才是最重要的。
目前在使用上发现了一个问题就是在GPU版本中，计算时发现GPU显存是在提高，但GPU 的计算显然是没有在计算，感觉只是在GPU里面走了一个过场，并没有什么实质性的提高

**Comment by Oceania2018** [comment]
你能提供代码来重现这个问题吗？
