### ISSUE TITLE
[BUG Report]: Early stopping parameter "min_delta" is set to "int" instead of "float"

### ISSUE THREAD

**Issue by boranyang-ML** [SciSharp/TensorFlow.NET#1119]
### Description

Under the file path: [TensorFlow.Keras](https://github.com/SciSharp/TensorFlow.NET/blob/master/src/TensorFlowNET.Keras/Callbacks/Earlystopping.cs#L14C13-L14C13), the early stopping parameter "min_delta" is set to "int" instead of "float", could you please check?

**Comment by Wanglongzhi2001** [comment]
Thank you for your advice, you are right, type of "min_delta" should be float, I will revise it.

**Comment by Wanglongzhi2001** [comment]
Hi, I have revised it. ^_^
