### ISSUE TITLE
tf.exp.cs - exp shall be moved to tf.math.cs

### ISSUE THREAD

**Issue by BalashovK** [SciSharp/TensorFlow.NET#1128]
### Description

For consistency, 
src/APIs/tf.exp.cs 
shall be removed.

These 2 lines of code:

public Tensor exp(Tensor x,
                string name = null) => gen_math_ops.exp(x, name);
                
shall be moved to 
src/APIs/tf.math.cs

**Comment by Wanglongzhi2001** [comment]
I'm agree with you.
