### ISSUE TITLE
[Question]:  CallbackParameters when using function model.Fit()

### ISSUE THREAD

**Issue by kojack14** [SciSharp/TensorFlow.NET#1130]
### Description

I want to use the EarlyStopping object to identify when the model achieved convergence in training, but I can't use it in the Fit() function. Follow the code example below:

var CallbackParameters = new CallbackParams
            {
            };

            var earlyStopping = new EarlyStopping(parameters: CallbackParameters, monitor: "val_loss", mode: "min", patience: 5);

**Comment by Wanglongzhi2001** [comment]
Hello, please refer to https://github.com/SciSharp/TensorFlow.NET/blob/master/test/TensorFlowNET.Keras.UnitTest/Callbacks/EarlystoppingTest.cs/#L55-63

**Comment by kojack14** [comment]
thanks, problem solved
