### ISSUE TITLE
[BUG Report]: SciSharp.TensorFlow.Redist nuget packages missing OSX binaries

### ISSUE THREAD

**Issue by puddlejumper9** [SciSharp/TensorFlow.NET#1141]
### Description

I doubt this is the right place for this but it's the best I could find.

I'm trying to use TF.NET nuget package and everything is fine except the SciSharp.TensorFlow.Redist nuget package is missing the binaries for OSX. Both the Windows and Linux binaries seem to be present.
<img width="285" alt="Screenshot 2023-07-09 at 2 46 21 PM" src="https://github.com/SciSharp/TensorFlow.NET/assets/9509621/0cf498b5-fc5e-492c-8965-8f28a575ca31">

Mac Homebrew doesn't have the correct binary version, and the default pip package is 2.12 which is missing a symbol that TF.NET tried to load. Currently working to force pip to use TF version 2.11.0

### Reproduction Steps

1. Use a Mac
2. Create dotnet core project.
3. Add TF.NET and SciSharp.TensorFlow.Redist nuget packages.
4. Run code that uses the library.

### Known Workarounds

Downloading binaries somewhere other than the SciSharp.TensorFlow.Redist nuget package.
Compiling TF from source.

### Configuration and Other Information

On OSX
"SciSharp.TensorFlow.Redist" Version="2.11.0"
"TensorFlow.Keras" Version="0.11.0"
"TensorFlow.NET" Version="0.110.0"
TargetFramework net7.0

**Comment by Wanglongzhi2001** [comment]
Hello, since there are relatively few developers in tf.net, the developer who was responsible for compiling at that time did not have a computer with a macos system, and there are relatively few macos users on tf.net, so the macos version has not been compiled since 2.11. Sorry for the inconvenience.

**Comment by Wanglongzhi2001** [comment]
Thank you for your enthusiasm and attention to TensorFlow.NET. If you can participate in the development of TensorFlow.NET, TensorFlow.NET will definitely become better. BTW, you can join our discord channel or QQ group to get in touch with us more closely. ^_^

**Comment by Oceania2018** [comment]
@puddlejumper9 @Wanglongzhi2001 Good news @AsakusaRinne just compiled the library for `mac os`. You can download from this [link](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist-osx/).
Please keep us updated if the library works or not.

**Comment by puddlejumper9** [comment]
@Oceania2018 
dlopen(/Users/nolans/source/repos/ML Chess/EngineTest/bin/Debug/net7.0/runtimes/osx-x64/native/libtensorflow.dylib, 0x0001): tried: '/Users/nolans/source/repos/ML Chess/EngineTest/bin/Debug/net7.0/runtimes/osx-x64/native/libtensorflow.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))

It seems this binary in osx-x64 folder is for arm64 architecture. This should be in the osx-arm64 folder.

So the issue persists. Now have osx-arm64 binaries, but lacking osx-x64 binaries.

**Comment by Lesiuk** [comment]
> @puddlejumper9 @Wanglongzhi2001 Good news @AsakusaRinne just compiled the library for `mac os`. You can download from this [link](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist-osx/). Please keep us updated if the library works or not.

Something is wrong with this library. Arm64 runtime is inside x64 directory.

**Comment by jambudipa** [comment]
> > @puddlejumper9 @Wanglongzhi2001 Good news @AsakusaRinne just compiled the library for `mac os`. You can download from this [link](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist-osx/). Please keep us updated if the library works or not.
> 
> Something is wrong with this nuget package. Arm64 runtime is inside x64 directory. It does not work.

I am suffering the same problem on macOS, `Tensorflow.NET cannot find a backend.`

Is there a means to compile this from source code and use it in my own app? .NET was my daily bread and butter for many years, but I haven't done it in nearly a decade!
