### ISSUE TITLE
[BUG Report]: NumPy amin and amax function are incorrectly mapped

### ISSUE THREAD

**Issue by OliBomby** [SciSharp/TensorFlow.NET#1151]
### Description

`amin` and `amax` are aliases for `min` and `max` in numpy. They don't do the same as `argmin` or `argmax`. Refer to the documentation:
https://numpy.org/doc/stable/reference/generated/numpy.amin.html
https://numpy.org/doc/stable/reference/generated/numpy.amax.html

They should map to `tf.min` and `tf.max`

Relevant source file:
https://github.com/SciSharp/TensorFlow.NET/blob/master/src/TensorFlowNET.Core/NumPy/NumPy.Statistics.cs

### Reproduction Steps

use `np.amin` and notice everything go up in flames

### Configuration and Other Information

- TensorFlow.NET 0.110.2
- TensorFlow.Keras 0.11.2
- .NET 6
- Windows 10

**Comment by Wanglongzhi2001** [comment]
Thank you for your kind reminder, I will fix it.

**Comment by Wanglongzhi2001** [comment]
Hello, this bug has been fixed.
