### ISSUE TITLE
[Feature Request]: Support for GRU layer

### ISSUE THREAD

**Issue by MattCW1701** [SciSharp/TensorFlow.NET#1167]
### Background and Feature Description

The GRU Cell is implemented, but unlike LSTM, there is no layer implementation for GRU.

**Comment by Wanglongzhi2001** [comment]
Thank you for your advice, I' will implement it. And I will let you know once it is implemented.

**Comment by Wanglongzhi2001** [comment]
Hello, GRU layer have been implemented in #1168.

**Comment by Wanglongzhi2001** [comment]
Close because GRU layers has been developed.
