### ISSUE TITLE
The Assign operation should record gradient

### ISSUE THREAD

**Issue by Esther2013** [SciSharp/TensorFlow.NET#117]
The `assign` operation will record gradient. The logic is missing in TensorFlow.NET.

![image](https://user-images.githubusercontent.com/33488376/51478860-4396f080-1d52-11e9-9b2a-58ac1feb3ab4.png)

**Comment by Oceania2018** [comment]
`var _inputs_flat = _op.inputs;` the inputs is always null, fix will.

**Comment by Deep-Blue-2013** [comment]
The `Operation.inputs` is a type of `_InputList` object in python.
