### ISSUE TITLE
[BUG Report]: gen_ops.scatter_update() prompts for input not ref

### ISSUE THREAD

**Issue by JustDooooIt** [SciSharp/TensorFlow.NET#1191]
### Description
use tf.compat.v1.disable_eager_execution();
![3f561ecf26e8245c238d77146edcc566](https://github.com/SciSharp/TensorFlow.NET/assets/43512399/15ab89e3-4249-460d-9473-bb18b2f2094c)
![d67902fd45f3813c44426a04865d3c33](https://github.com/SciSharp/TensorFlow.NET/assets/43512399/ae67bce2-80ec-4889-9f9c-43fb3ded3252)

### Configuration and Other Information

1, 0.110.4
2, net6
3, win10

**Comment by Wanglongzhi2001** [comment]
这个 issue 能 close吗，之前在qq群已经问过了
