### ISSUE TITLE
4 errors while building NodeDef 'gradients/Sum_grad/DynamicStitch'

### ISSUE THREAD

**Issue by Esther2013** [SciSharp/TensorFlow.NET#165]
When I did linear regression, I encountered 4 errors.
```sh
4 errors while building NodeDef 'gradients/Sum_grad/DynamicStitch' using Op<name=DynamicStitch; signature=indices:N*int32, data:N*T -> merged:T; attr=N:int,min=1; attr=T:type>:
Single tensor passed to 'indices', expected list
Single tensor passed to 'data', expected list
More Input() calls than the 2 input_args
More Input() calls than the 2 input_args
```

**Comment by Esther2013** [comment]
Attach a screenshot:
![image](https://user-images.githubusercontent.com/33488376/52361923-fa5ac800-2a04-11e9-88ac-e9836aea470a.png)

**Comment by Esther2013** [comment]
fixed

**Comment by vsatyakumar** [comment]
Hey, I'm currently facing the same bug while creating a mixture density network using tf.keras. How did you fix this?

`ValueError: 5 errors while building NodeDef 'mdn_layer/tf_op_layer_Mixture/sample/DynamicStitch/Mixture/sample/DynamicStitch' using Op<name=DynamicStitch; signature=indices:N*int32, data:N*T -> merged:T; attr=N:int,min=1; attr=T:type>:
Single tensor passed to 'data', expected list
More Input() calls than the 2 input_args
More Input() calls than the 2 input_args
More Input() calls than the 2 input_args
More Input() calls than the 2 input_args
`
