### ISSUE TITLE
TensorFlow.NET doesn't work on Linux

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/TensorFlow.NET#176]
TensorFlow.NET doesn't work on Linux

**Comment by dotChris90** [comment]
As we said - just to tracking it. We try out Ubuntu System in Virtual Box on windows 10. By the way - what is our wish or goal? we plan to pack them into nuget packages and reference them - right? or shall we allow user to install manually?

**Comment by Oceania2018** [comment]
I think pack into NuGet will be more convinent for users. We will run it in Debian docker, so it's necessary to  support linux.

**Comment by dotChris90** [comment]
Agree - I will check again how we do it in NumSharp (the LAPACK) and will package it for Tensorflow libs. Just thinking if we should create a separate project (repository) or if we should make a separate project inside Tensorfow.NET. maybe first go with keep in Tensorflow.NET.

**Comment by Oceania2018** [comment]
Yes, keep it in TF.NET

**Comment by dotChris90** [comment]
Hm interesting. With TensorFlowNET.Native in future we will try out Native Lib or do you plan to extend the C API? Just ask for understanding. :)

**Comment by Oceania2018** [comment]
Hm, won't do. Just for testing some function which is hard to migrate from C++/ Python.

**Comment by Oceania2018** [comment]
Testing on Linux for CPU and GPU version. works great.
