### ISSUE TITLE
how  to specify GPU .

### ISSUE THREAD

**Issue by pkingwsd** [SciSharp/TensorFlow.NET#190]
with tf.device('/gpu:0'):
    ....
with tf.device('/gpu:1'):
    ...
with tf.device('/cpu:0'):
    ...

**Comment by Oceania2018** [comment]
@pkingwsd From session option. Is this issue addressed? If so, I'll close this issue.

**Comment by Oceania2018** [comment]
You can use `SessionOptions` to specify GPU.
```csharp
var opts = new SessionOptions();
opts.SetConfig(new ConfigProto { InterOpParallelismThreads = 4 });
session_ = new Session(graph, opts, s);
```
