### ISSUE TITLE
Missing _greedy_batch_sampler._random

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/TensorFlow.NET#213]
_greedy_batch_sampler._random in `_InitializeClustersOpFactory`

**Comment by Oceania2018** [comment]
Added the `_random`, but the returned `shape` seems like not correct.
![image](https://user-images.githubusercontent.com/1705364/55774027-0c82d200-5a59-11e9-8e2f-42161eb28ba9.png)

**Comment by Oceania2018** [comment]
new exception raised.
`Invalid reduction dimension 1 for input with 0 dimensions. for 'Sum' (op: 'Sum') with input shapes: [], [] and with computed input tensors: input[1] = <1>.`

**Comment by Oceania2018** [comment]
There should be a `cond/assert_equal/Equal/Switch` between them.

![image](https://user-images.githubusercontent.com/1705364/55878127-72f31780-5b61-11e9-8e9b-a1d4e480c4d9.png)

**Comment by henon** [comment]
This is the same bug that also lets the CondTest fail. The cond operation constructs the Graph incorrectly

**Comment by Oceania2018** [comment]
@henon Got some clue.
![image](https://user-images.githubusercontent.com/1705364/55925848-999e6600-5bd4-11e9-9da0-43a217eccaac.png)
