### ISSUE TITLE
Memory leak on BaseSession.run

### ISSUE THREAD

**Issue by bpzoran** [SciSharp/TensorFlow.NET#220]
On call BaseSession.run method, passing Operation as a first variable, the memory leak occurs, on unmanaged  memory.

**Comment by Oceania2018** [comment]
Coud you provide more detail. There used to have this kind of issue. We thought we have fixed it. As I konw someone already run tf.net on live environemnt for about months, no memory leak occurs.

Provide code details please.

**Comment by bpzoran** [comment]
This problem can be presented on your example - LinearRegression.cs . Please find attached a video of this example, showing code debugging  together with memory increasement presented by task manager. I adapted the original code in order to present this problem, but the same problem happens with original example. My code is in attachment, too.
[TensorFlowNetMemoryLeakProblem.zip](https://github.com/SciSharp/TensorFlow.NET/files/3065536/TensorFlowNetMemoryLeakProblem.zip)

**Comment by Oceania2018** [comment]
Have you tried on v0.8.2 ?

**Comment by bpzoran** [comment]
I've tried on v0.8.3. The same problem occurs.

**Comment by deepakkumar1984** [comment]
> I've tried on v0.8.3. The same problem occurs.

The issue was with the example code you have. The testing cost function and the test data are in the loop. 
Made the following changes
1) The test data need to be defined once. 
2) The testing cost function defined once and used in the training process

Updated RunSession function and below is the result for 5000 epoches
```csharp
private void RunSession(Session sess, Operation init, Tensor X, Tensor Y, Tensor W, Tensor b, Tensor cost, Tensor pred, Operation optimizer)
		{
			// Run the initializer
			sess.run(init);
            var test_X = np.array(6.83f, 4.668f, 8.9f, 7.91f, 5.7f, 8.7f, 3.1f, 2.1f);
            var test_Y = np.array(1.84f, 2.273f, 3.2f, 2.831f, 2.92f, 3.24f, 1.35f, 1.03f);

            var metric = tf.reduce_sum(tf.pow(pred - Y, 2.0f)) / (2.0f * test_X.shape[0]);
            // Fit all training data
            for (int epoch = 0; epoch < training_epochs; epoch++)
			{
				foreach (ValueTuple<float, float> x_y in Python.zip<float>(train_X, train_Y))
				{
					float x = x_y.Item1;
					float y = x_y.Item2;
					sess.run(optimizer,
						new FeedItem(X, x),
						new FeedItem(Y, y));
				}
				// Display logs per epoch step
				if ((epoch + 1) % display_step == 0)
				{
					var c = sess.run(cost,
						new FeedItem(X, train_X),
						new FeedItem(Y, train_Y));
				}

                var training_cost = sess.run(cost,
                    new FeedItem(X, train_X),
                    new FeedItem(Y, train_Y));

                //// Testing example
                
                var testing_cost = sess.run(metric,
                    new FeedItem(X, test_X),
                    new FeedItem(Y, test_Y));

                Console.WriteLine("Epoch: {0}, Train: {1}, Test: {2}", epoch, training_cost, testing_cost);
            }
		}
```

![image](https://user-images.githubusercontent.com/6328361/61019292-ca12bd80-a3d8-11e9-89db-84c270b2ee0c.png)

**Comment by deepakkumar1984** [comment]
[ann.zip](https://github.com/SciSharp/TensorFlow.NET/files/3380097/ann.zip)

Updated code

**Comment by bpzoran** [comment]
This is much better. However, there is still memory leak. It is much smaller, but it increases with more epoches, more variables and continuous executions. For example, I have tried 72 executions in a row (without testing), with 50000 epoch per execution and 2 predictor arrays (and one predicted array, of course) with 40 variables in each execution. Memory leak was over 1,5G.
