### ISSUE TITLE
CondContext.AddValue

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/TensorFlow.NET#226]
Run K-Means, different nodes are built.

![image](https://user-images.githubusercontent.com/1705364/56008615-662a0d00-5ca2-11e9-9f1a-76a77ea0c68a.png)

@henon

**Comment by Oceania2018** [comment]
Causes `op.inputs.Length` reset to 1.

![image](https://user-images.githubusercontent.com/1705364/56009633-1a796280-5ca6-11e9-928e-eb95d2111261.png)

**Comment by Oceania2018** [comment]
@henon Looks good now.

![image](https://user-images.githubusercontent.com/1705364/56010263-907ec900-5ca8-11e9-82ff-020ff4700168.png)

**Comment by Oceania2018** [comment]
`node 61` break:

![image](https://user-images.githubusercontent.com/1705364/56010453-3b8f8280-5ca9-11e9-86f3-2f7a7c5150a9.png)

**Comment by henon** [comment]
This is the same bug that the TestCond unit test also can reproduce. It is caused by op._update_input(index, Tensor) not being able to update the graph because of a missing c_api call
