### ISSUE TITLE
flow_control_ops.cond graph not constructed correctly

### ISSUE THREAD

**Issue by henon** [SciSharp/TensorFlow.NET#229]
CondTestCases.testCondTrue creates the following graph:

```csharp
            with(tf.Graph().as_default(), g =>
            {
                var x = tf.constant(2);
                var y = tf.constant(5);
                var z = control_flow_ops.cond(tf.less(x, y), () => tf.multiply(x, tf.constant(17)),
                    () => tf.add(y, tf.constant(23)));
                tf.train.export_meta_graph(@"D:\dev\tensorboard\logdir\sharp.meta", as_text: false);
                self.assertEquals(eval_scalar(z), 34);
            });
```

![cond_graph](https://user-images.githubusercontent.com/44090/56079109-23764b00-5df0-11e9-91c3-50436453b1fc.PNG)

But the same code in Python creates this graph:

```python
    g = ops.Graph()
    with g.as_default():
        x = tf.constant(2);
        y = tf.constant(5);
        z = control_flow_ops.cond(tf.less(x, y), lambda: tf.multiply(x, tf.constant(17)),
                                  lambda: tf.add(y, tf.constant(23)));
        writer = tf.summary.FileWriter(logdir="D:/dev/tensorboard/logdir", graph=g)
        writer.flush()
```

![cond_graph_py](https://user-images.githubusercontent.com/44090/56079112-2ffaa380-5df0-11e9-9408-5eac945a529b.PNG)

**Comment by henon** [comment]
After @Oceania2018 updated the c_api Operation._update_inputs seems to work now. Only the control dependencies are still missing from the graph:
![image](https://user-images.githubusercontent.com/44090/56083725-483ae480-5e29-11e9-9864-6d3dadb790c9.png)

**Comment by henon** [comment]
I have identified the problem why the control dependency edges are not generated. Here is how to reproduce:
* In Control.Operations._add_control_input add the line  `var updated_control_inputs=control_inputs;` after the `c_api` call.
* Set a breakpoint on that new line
![image](https://user-images.githubusercontent.com/44090/56084275-407f3e00-5e31-11e9-9832-03d3b2d36b24.png)
* Run CondTestCases.testCondTrue

You will see that the cond/switch_f control dependency is added to this (which is cond/Const). But after stepping over the new line `var updated_control_inputs=control_inputs;` you will see that control_inputs is still empty. Seems like the update via the c_api fails somehow

**Comment by Oceania2018** [comment]
@henon I can't reproduce it.

![image](https://user-images.githubusercontent.com/1705364/56085788-f5543380-5e0e-11e9-8c4e-00310567b149.png)

**Comment by henon** [comment]
Have you checked the problem with TF_AddControlInput I outlined above? The problem is that after adding a control input the control inputs are still 0.

**Comment by Oceania2018** [comment]
We recompiled the tensorflow c_api, now it passed the unit test.

**Comment by henon** [comment]
the simplified test case passes, the original one with Add and Mul still fails. but the graph looks better now:
![image](https://user-images.githubusercontent.com/44090/56095165-60b70780-5eda-11e9-8662-134bb4d550cd.png)

**Comment by Oceania2018** [comment]
This should be 1.

![image](https://user-images.githubusercontent.com/1705364/56102041-4cc9d080-5eef-11e9-97c2-57ddff8afc48.png)

**Comment by Oceania2018** [comment]
@henon Fixed.

![image](https://user-images.githubusercontent.com/1705364/56102138-6e778780-5ef0-11e9-8128-346a904940b6.png)

**Comment by henon** [comment]
Now that it is fixed, side by side the graphs of tensorflow Python and TensorFlow.NET

![cond_graph_py](https://user-images.githubusercontent.com/44090/56115409-99e78a00-5f63-11e9-8121-6c4f91c6be4d.PNG)

![image](https://user-images.githubusercontent.com/44090/56115385-8b00d780-5f63-11e9-8387-fc461896cec6.png)
