### ISSUE TITLE
How to use GPU?

### ISSUE THREAD

**Issue by phikyzom** [SciSharp/TensorFlow.NET#240]
I want to use the GPU to run the example. Which Cuda i should to setup? It is better to tell me the step.

**Comment by Oceania2018** [comment]
Same issue as https://github.com/SciSharp/TensorFlow.NET/issues/190.

**Comment by bluetrees886** [comment]
I have the same problem.
The example project 'TensorFlowNET.Examples.GPU' cann't load lib 'scisharp.tensorflow.redist-windows-gpu'.

**Comment by Oceania2018** [comment]
@bluetrees886 Please install https://www.nuget.org/packages/SciSharp.TensorFlow.Redist-Windows-GPU
