### ISSUE TITLE
compiling models in the `Keras` module. 

### ISSUE THREAD

**Issue by willashford** [SciSharp/TensorFlow.NET#244]
Hi, 

I've seen that there exists a Keras module within the package. I was wondering if anyone knew how to the Keras models "compile" in this package? I cannot find a reference to a `compile` method and the docs don't see references to it. Any help would be greatly appreciated.

Cheers :)

**Comment by Oceania2018** [comment]
Are you talking about this folder ?

![image](https://user-images.githubusercontent.com/1705364/57651689-809e2180-7593-11e9-8bdf-6cd3e4293585.png)

**Comment by williamashfordQB** [comment]
Yep :)

**Comment by Oceania2018** [comment]
The Keras module is not finished yet.

**Comment by williamashfordQB** [comment]
Ah no worries. Looking forward to it developments on this :)

**Comment by arnavdas88** [comment]
@williamashfordQB , The development of the keras package i.e. tf.keras is in process...Rightnow, I am working on the `backend.cs` file and hopefully it will be complete soon... the most time consuming task though are the util functions from **tf.keras.utils**.  Once we complete the util  functions, hopefully the other tasks like the compile function, models and Layers, won't take much time to finish...

**Comment by williamashfordQB** [comment]
Nice, can’t wait!

**Comment by williamashfordQB** [comment]
Just wondering if there was any update on this?

**Comment by simonbuehler** [comment]
hi,
great work guys, is there a ETA for this / full tf2.0 support ?

**Comment by faeze-el** [comment]
Nice, can’t wait!

**Comment by Oceania2018** [comment]
Please try [TensorFlow.Keras](https://www.nuget.org/packages/TensorFlow.Keras/).
