### ISSUE TITLE
Links to examples are broken.

### ISSUE THREAD

**Issue by SrancsikAtBitrise** [SciSharp/TensorFlow.NET#249]
E.g. https://github.com/SciSharp/TensorFlow.NET/blob/master/test/TensorFlowNET.Examples/LinearRegression.cs

Actually, most of the examples are 404 as well. Just as in the book.

The sample code is under subfolders of:
https://github.com/SciSharp/TensorFlow.NET/tree/master/test/TensorFlowNET.Examples/

**Comment by Oceania2018** [comment]
@SrancsikAtBitrise Could you help fix the link issue? It's not hard.

**Comment by SrancsikAtBitrise** [comment]
Done. Please review.
https://github.com/SciSharp/TensorFlow.NET/pull/251

**Comment by Oceania2018** [comment]
Appreciate your contribution. Will merge soon.
