### ISSUE TITLE
DLL Not Found Exception

### ISSUE THREAD

**Issue by eduardobellotto** [SciSharp/TensorFlow.NET#252]
Hi.

I've created a new project in Windows 10 VS 2019 targeting .NET Framework 4.6.2.

Then, I've installed the Tensorflow.NET Nuget Package version 0.8.0.

In Program class, I've inserted ```using Tensorflow;```.

In Main method, I've inserted the code ```var a = tf.constant(3);```.

When I run the code, I receive the exception: ```DllNotFoundException: Unable to load DLL 'tensorflow': The specified module could not be found.```.

I've found the closed issue #144 (Cannot load Tensorflow DLL error), but I was not able to solve the problem after reading it.

There is a ```TensorFlow.NET.dll``` file in ```..\bin\Debug``` folder, but there is no ```TensorFlow.dll``` file in that folder.

I've found a ```TensorFlow.dll``` file in ```..\packages\TensorFlow.NET.0.8.0\tensorflowlib\runtimes\win-x64``` folder.

I've tried to copy this file to the ```..\bin\Debug``` folder, but the error persisted.

I've tried the same with VS 2017 and received the same exception.

Could you help me?

Thanks in advance.

**Comment by Oceania2018** [comment]
@eduardobellotto Try to install another redist provided by Microsoft https://www.nuget.org/packages/Microsoft.ML.TensorFlow.Redist
```shell
PM> Install-Package Microsoft.ML.TensorFlow.Redist
```

**Comment by eduardobellotto** [comment]
Hi @Oceania2018 

I've installed the Microsoft.ML.TensorFlow.Redist version 0.12.0, but I sill have the same exception.

**Comment by kerryjiang** [comment]
Hello @eduardobellotto, just make sure the package reference is there and do a full build:
<PackageReference Include="Microsoft.ML.TensorFlow.Redist" Version="0.11.0" />

**Comment by kerryjiang** [comment]
@Oceania2018 it seems this problem always be an obstacle for the beginners of TF.NET. I forgot this issue many times as well.

**Comment by eduardobellotto** [comment]
Hi @Oceania2018.

I've migrate the ```Package.config``` format to the ```PackageReference``` format and the reference is OK:

```
  <ItemGroup>
    <PackageReference Include="Microsoft.ML.TensorFlow.Redist">
      <Version>0.12.0</Version>
    </PackageReference>
    <PackageReference Include="TensorFlow.NET">
      <Version>0.8.0</Version>
    </PackageReference>
  </ItemGroup>
```

I also created a brand new project with the default package management ```PackageReference``` format.

The project was created with the same right reference above.

But the exception continues in both cases.

Thanks again.

**Comment by Oceania2018** [comment]
@eduardobellotto .NET 4.7.2 is the first version of the full .NET Framework that is fully .NET Standard 2.0 compliant without any additional dependencies. Can you try to upgrade your .NET Framework first?

**Comment by eduardobellotto** [comment]
Hi @Oceania2018.

I've created a new project targeting .NET Framework 4.7.2 with the Nugets ```Microsoft.ML.TensorFlow.Redist``` and ```TensorFlow.NET``` correctly installed, but the same exception occurred.

Thanks once more.

**Comment by Oceania2018** [comment]
@eduardobellotto This is what my files look like:

![image](https://user-images.githubusercontent.com/1705364/58376426-ad0d5280-7f30-11e9-878e-90111c1b5331.png)

**Comment by tradexdev** [comment]
> @eduardobellotto This is what my files look like:
> 
> ![image](https://user-images.githubusercontent.com/1705364/58376426-ad0d5280-7f30-11e9-878e-90111c1b5331.png)

Hi

I copy the "tensorflow.dll" file to Debug folder to test. I worked in that case. It is not the solution, but a small hack lets say.  Problem is why it is not found originally.

![image](https://user-images.githubusercontent.com/24697955/58383454-ae498880-7fdf-11e9-9826-f76f13cf1449.png)

**Comment by eduardobellotto** [comment]
Hi @Oceania2018 and @tradexdev.

I've discovered that this copy and paste solution works just for a .NET Core project.

I have a .NET Framework 4.6.2 project that has some dependencies to this framework and I would like to use TensorFlow in that project.

I've tried to create a solution with two different projects: a .NET Framework 4.6.2 and a .NET Core 2.0 project, but the Visual Studio does not permit us to reference the two projects directly.

I've found a workaround way to create that dependency in this link: https://www.youtube.com/watch?v=qc2WFaMfdp8&t=485s and I've followed this example.

It is interesting that TensorFlow works then we call the method from the own .NET Core application, but throws the exception when we try to call the same method of the same .NET Core app class from the .NET Framework application.

I have already tried to create an intermediate .NET Standard library project, referenced by the other two projects, but it has trown the same exception.

I'd like to ask you a favor.

Could you create a project from scratch, with .NET Framework 4.6.2 and the Nuget packages cited above and see if it works on your computers?

I would like to know if the problem with the .NET Framework would also occur on your computer or if it is a problem with the Frmework.

Thank you very much for the help!

**Comment by Oceania2018** [comment]
@eduardobellotto Just make sure you're running x64 platform.

![image](https://user-images.githubusercontent.com/1705364/58386901-01194500-7fcc-11e9-8b0c-0bc0b7c4ef1c.png)

![image](https://user-images.githubusercontent.com/1705364/58386911-17bf9c00-7fcc-11e9-9fc9-db3b5c2a7521.png)

![image](https://user-images.githubusercontent.com/1705364/58386898-e47d0d00-7fcb-11e9-986a-f30085865043.png)

**Comment by eduardobellotto** [comment]
Bingo!

Its working now!

For those who are facing the same difficulty, just follow these steps:

1) In the top menu, click on the ```Any CPU``` dropdown and select the option ```Configuration Manager```:

![image](https://user-images.githubusercontent.com/38707465/58387514-ddfb8f00-7fe5-11e9-97e5-51e5e911a577.png)

2) Under the ```Active solution platform``` label, select the option ```<New...>```:

![image](https://user-images.githubusercontent.com/38707465/58387515-e8b62400-7fe5-11e9-9dcf-36471827b900.png)

3) In the pop up window, just click on the ```OK``` button:

![image](https://user-images.githubusercontent.com/38707465/58387525-22872a80-7fe6-11e9-98b7-7cd88585ecca.png)

4) The option ```x64``` will be selected in the top menu:

![image](https://user-images.githubusercontent.com/38707465/58387542-70039780-7fe6-11e9-924a-09f538cf10af.png)

5) Install both NuGet Packages cited above:

![image](https://user-images.githubusercontent.com/38707465/58387535-45b1da00-7fe6-11e9-9b0a-b38c7f1a7c71.png)

As Haiping has shown above, the application is working fine:

![image](https://user-images.githubusercontent.com/38707465/58387536-49ddf780-7fe6-11e9-9502-c34ec9527afb.png)

Thank you very much @Oceania2018, @kerryjiang and @tradexdev, for the great help!

**Comment by eformx** [comment]
That almost worked for me.  Added `using static Tensorflow.Binding;` and then it worked.

**Comment by pthinh14** [comment]
In my cases, everything works fine when running on my computer, but the exception raises when I bring the Debug folder to other computers. Does it happen because of lacking environment? If yes, please help me out some possible fixes.

At first, the message is 'Unable to load DLL 'tensorflow''. Then after I installed C++ Redistributed in the client's computer, the message changed to "Unable to load DLL 'tensorflow': A dynamic link library (DLL) initialization failed.

**Comment by NarwhalRoger** [comment]
I had same issues but every time I solved one with advices from this thread, I was getting other errors which went deeper and deeper into the system until it had already nothing to do with TensorFlow anymore. What helped me is to create completely new project ad install a bit older versions of NuGet packages (I used Microsoft.ML 1.6, Microsoft.ML.ImageAnalytics 1.6, Microsoft.ML.Visions 1.6 and SciSharp.TensorFlow.Redist 2.3.1.

These are versions of packages which VS 2022 ML Model Builder uses, and there everything works ok
