### ISSUE TITLE
The type initializer for 'Tensorflow.tf' threw an exception.”

### ISSUE THREAD

**Issue by 309441166** [SciSharp/TensorFlow.NET#253]
I get this error:

The type initializer for 'Tensorflow.tf' threw an exception.

DllNotFoundException: Unable to load DLL 'tensorflow' or one of its dependencies: 找不到指定的模块。 (Exception from HRESULT: 0x8007007E)

---------- MY CODE----
using System;
using Tensorflow;

namespace TFNet
{
    class Program
    {
        static void Main(string[] args)
        {
            //Console.WriteLine("Hello World!");
            var hello = tf.constant("Hello, TensorFlow!");
        }
    }
}

Nuget TensorFlow.NET(0.8.0)
.NET Core 2.2

**Comment by Oceania2018** [comment]
Same issue as https://github.com/SciSharp/TensorFlow.NET/issues/252

**Comment by 18628271760** [comment]
Ues nuget to insatll Microsoft.ML.TensorFlow.Redist
