### ISSUE TITLE
Following the first HelloWorld example fails to run.

### ISSUE THREAD

**Issue by krisri** [SciSharp/TensorFlow.NET#255]
Starting a new VS project, and adding only the TensorFlow.NET reference is not sufficient. On first usage of 'tf' it throws an exception: "The type initializer for 'Tensorflow.tf" threw an exception" of type DllNotFoundException.

Adding also nuget package Microsoft.ML.TensorFlow.Redist gets me going. But not sure if this is proper.

Kris

**Comment by Oceania2018** [comment]
Same issue as https://github.com/SciSharp/TensorFlow.NET/issues/252.
