### ISSUE TITLE
How to run a network on GPU under win x64 

### ISSUE THREAD

**Issue by serjl** [SciSharp/TensorFlow.NET#258]
Hello,
Is it possible to run a network on GPU under windows x64?
For now with a supplied tensorflow.dll it runs on CPU only.
I tried to put a gpu version (by renaming the python's _pywrap_tensorflow_internal.pyd into tensorflow.dll) but it fails to load the dll.

**Comment by Oceania2018** [comment]
You should download the GPU version as https://github.com/SciSharp/TensorFlow.NET/blob/master/tensorflowlib/README.md

**Comment by serjl** [comment]
> You should download the GPU version as https://github.com/SciSharp/TensorFlow.NET/blob/master/tensorflowlib/README.md

Thank you for a quick reply. As i can see the only windows version is a CPU one. GPU is for LINUX only there.

**Comment by serjl** [comment]
I downloaded gpu version of tensorflow.dll from the following link 
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-1.13.1.zip 
on the https://www.tensorflow.org/install/lang_c

I get the following exception:

System.DllNotFoundException: 'Unable to load DLL 'tensorflow': The specified module could not be found. (Exception from HRESULT: 0x8007007E)'

**Comment by mfagerlund** [comment]
Same problem here, the tensorflow.dll from the CPU download works fine (and it's 75MB);

https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.13.1.zip

But the GPU version (which is HUGE, 734MB) fails with the same error as above;

https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-1.13.1.zip

Anyone get it to work? GPU training support would be awesome...

**Comment by serjl** [comment]
Fixed by installing Cuda + CuDNN, made a PR: https://github.com/SciSharp/TensorFlow.NET/pull/260
