### ISSUE TITLE
Compiled tensorflow-gpu 1.40.0-rc1

### ISSUE THREAD

**Issue by Nucs** [SciSharp/TensorFlow.NET#264]
It would be very helpful if you could provide a compiled dll of tensorflow-gpu 1.40.0-rc1 (for windows atleast) with AVX2 support along with the cpu version [there](https://github.com/SciSharp/TensorFlow.NET/tree/master/tensorflowlib/runtimes/win-x64/native).

**Comment by Oceania2018** [comment]
We added the `Microsoft.ML.TensorFlow.Redist` as dependency for cross-platform.
