### ISSUE TITLE
Build graph: implement switch statement + tests

### ISSUE THREAD

**Issue by henon** [SciSharp/TensorFlow.NET#265]
See TensorFlowNET.UnitTest => control_flow_ops_test/SwitchTestCase.cs

TODO:
* Port the test cases from Python to C# and 
* Port the missing functions that are required for the tests to run and succeed

**Comment by ctorrez** [comment]
Hi @henon @Oceania2018 I want to help with this issue, it is my first time doing a PR, I am going to follow this guide lines [https://github.com/necolas/issue-guidelines/blob/master/CONTRIBUTING.md](url)

I have experience in Python and .Net, ML - Sk Learn, Keras, and Pandas. I am going to work this weekend and hope to have some progress.
