### ISSUE TITLE
Document that tensorflow.dll r1.14-rc1 is needed

### ISSUE THREAD

**Issue by sattisvar** [SciSharp/TensorFlow.NET#273]
[Here](https://github.com/SciSharp/TensorFlow.NET/blob/master/tensorflowlib/README.md) it is stated that we can download tensorflow.dll at r1.13 while some parts of TensorFlow.NET seems to work only with r1.14-rc1

**Comment by Oceania2018** [comment]
Hi, could you state which part is incompatible?
We only pack the latest compiled library up to date with source code.

**Comment by Oceania2018** [comment]
TensorFlow v1.14.0 is published officially.
