### ISSUE TITLE
Allow model to be imported using bytes

### ISSUE THREAD

**Issue by PranovD** [SciSharp/TensorFlow.NET#276]
https://github.com/SciSharp/TensorFlow.NET/blob/476f8cfad0fa5c37639a1b6fb73ff179ec3d4a41/src/TensorFlowNET.Core/Graphs/Graph.Import.cs

It would be nice if it could import model from byte array
```
public Status Import(byte [] bytes)
        {
            var graph_def = new Tensorflow.Buffer(bytes);
            var opts = c_api.TF_NewImportGraphDefOptions();
            c_api.TF_GraphImportGraphDef(_handle, graph_def, opts, Status);
            return Status;
        }
```

**Comment by Oceania2018** [comment]
Added for v0.8.3. 
This version only works with tensorflow v1.14.
