### ISSUE TITLE
Duplicate Enum type in TF_Datatype

### ISSUE THREAD

**Issue by PranovD** [SciSharp/TensorFlow.NET#277]
There are two enum types that map to 8, TF_COMPLEX64 and TF_COMPLEX
https://github.com/SciSharp/TensorFlow.NET/blob/master/src/TensorFlowNET.Core/Tensors/TF_DataType.cs

**Comment by Oceania2018** [comment]
@PranovD When I check the source code in tensorflow. It's not typo.
Just for API backwards compatibility.

![image](https://user-images.githubusercontent.com/1705364/60435889-58649380-9bd0-11e9-8dda-73f1b3b0aab1.png)
