### ISSUE TITLE
Is it possible to load a tensor from an in-memory image?

### ISSUE THREAD

**Issue by zamirkhan** [SciSharp/TensorFlow.NET#281]
I'm trying to use TensorFlow.NET to run inference using a custom model that we've already trained. The model is trained to run on frames of a video. Ideally, I'd like our application to be able to load the video file and then run the inference on it frame-by-frame. However, looking at `tf.read_file` makes it seem that it expects an image file that is saved to disk. I am able to get a `Bitmap` object in memory from the video, but would like to avoid writing these Bitmaps to disk simply to read them back in to TF, especially given the unnecessary I/O operations. Is this possible? Is there a better way to approach what I'm trying to do?

**Comment by Oceania2018** [comment]
@zamirkhan Absoutely yes, You have to modify your graph to allow input tensor as placeholder which is an `NDArray` contains your Bitmap bytes in memory.

**Comment by mjbedford2017** [comment]
@Oceania2018 I see that you can said you can use an in memory image which is good news. I would venture to say this is what most people need as most are working with images that they have either already loaded or are receiving from a stream. In my case, I have a Bitmap in memory. I understand from your response above that I need to get this into an NDArray. However, it is not really clear how to do this and I can't find too many examples on it. Can you tell me a simply way to do this? I did try to simply convert the Bitmap to byte array and pass that in when instantiating a new NDArray. However, when I do that, I get an error that the input expects a multidimensial (4) array. 

So, then I tried instantiating a new NDArray with my Bitmap bytes and a new Shape which i set to the width and height of my image and then 3 channels, like this:

    //Take the in memory image, resize for Tensor input!
    var resized_image = ResizeImage(image, InputImageWidth, InputImageHeight);
    //Numpy array, convert image to byte array and then try to add to NDArray.
    byte[] imgArray = BitmapToByteArray(resized_image);
    NDArray test = new NDArray(imgArray, new Shape(1, resized_image.Width, resized_image.Height, 3));

Please let me know an easy way to make this work.

Thanks!

**Comment by itzukah** [comment]
Hi! mjbedford2017,
The above code doesn't work for me.

**Comment by Nucs** [comment]
@itzukah Please take a look at [this](https://github.com/SciSharp/NumSharp/issues/289#issuecomment-520626604)
