### ISSUE TITLE
i try to use objectdection tensorflow-gpu but too much slow

### ISSUE THREAD

**Issue by HJB83** [SciSharp/TensorFlow.NET#293]
i try to use tensorflow.net within gpu in winform c#. but. is too much slow? why is that happen?

compare to python that need to only 1 second. but .net is almost 8 seconds..can you explain why is that happen?

**Comment by Oceania2018** [comment]
@HJB83 Are you talking about this example https://github.com/SciSharp/TensorFlow.NET/blob/master/test/TensorFlowNET.Examples/ImageProcessing/ObjectDetection.cs ?

**Comment by HJB83** [comment]
i found problem at first time that takes too much time almost 6 second..

how to make a local variable to global variable?

anyone know that? 

====sample.

 Graph graph = new Graph().as_default();
            graph.Import(Path.Combine(modelDir, pbFile));

            Tensor tensorNum = graph.OperationByName("num_detections");
            Tensor tensorBoxes = graph.OperationByName("detection_boxes");
            Tensor tensorScores = graph.OperationByName("detection_scores");
            Tensor tensorClasses = graph.OperationByName("detection_classes");
            Tensor imgTensor = graph.OperationByName("image_tensor");
            Tensor[] outTensorArr = new Tensor[] { tensorNum, tensorBoxes, tensorScores, tensorClasses };
           // sch.Stop();
           // label2.Text = sch.Elapsed.ToString();
            using (var sess = tf.Session(graph))
            {

**Comment by Oceania2018** [comment]
You just need import once, after that, you can do inference many times.

**Comment by henon** [comment]
Good point Haiping. but. too much no example. he understand what is you meaning?

**Comment by HJB83** [comment]
public partial class Form1 : Form
    {
       // dynamic graph;
        //private Session sess;
        public bool IsImportingGraph { get; set; } = false;

        public float MIN_SCORE = 0.5f;
        // string pbFile = @"exported_model\frozen_inference_graph.pb";
        //  string labelFile = @"records\classes.pbtxt";
        string modelDir = "exported_model";
       
        string pbFile = "frozen_inference_graph.pb";
        string labelFile = "classes.pbtxt";
        Stopwatch sch = new Stopwatch();
        public Form1()
        {
            InitializeComponent();
        }

        private void Button1_Click(object sender, EventArgs e)
        {
            inspection();
            
        }
        public void inspection()
        {
          //  sch.Start();
            var imgArr = ReadTensorFromImageFile("TOP.jpg");
            var imgArr2= ReadTensorFromImageFile("conn.jpg");
            var imgArr3 = ReadTensorFromImageFile("BOTT.jpg");
            var imgArr4 = ReadTensorFromImageFile("side.jpg");
            Graph graph = new Graph().as_default();
            graph.Import(Path.Combine(modelDir, pbFile));

            Tensor tensorNum = graph.OperationByName("num_detections");
            Tensor tensorBoxes = graph.OperationByName("detection_boxes");
            Tensor tensorScores = graph.OperationByName("detection_scores");
            Tensor tensorClasses = graph.OperationByName("detection_classes");
            Tensor imgTensor = graph.OperationByName("image_tensor");
            Tensor[] outTensorArr = new Tensor[] { tensorNum, tensorBoxes, tensorScores, tensorClasses };
          
            dynamic sess = tf.Session(graph);
           
               
                var results = sess.run(outTensorArr, new FeedItem(imgTensor, imgArr));

                NDArray[] resultArr = results.Data<NDArray>();

                buildOutputImage(resultArr, pictureBoxTOP, @"TOP.jpg");

                //  sch.Stop();
               // label8.Text = sch.Elapsed.ToString(); before takes 11 seconds. but after that only takes 0.11seconds.

                results = sess.run(outTensorArr, new FeedItem(imgTensor, imgArr2));

                resultArr = results.Data<NDArray>();

                buildOutputImage(resultArr, pictureBoxCON, @"conn.jpg");
            
                results = sess.run(outTensorArr, new FeedItem(imgTensor, imgArr3));

                resultArr = results.Data<NDArray>();

                buildOutputImage(resultArr, pictureBoxBOT, @"BOTT.jpg");
                results = sess.run(outTensorArr, new FeedItem(imgTensor, imgArr4));

                resultArr = results.Data<NDArray>();

                buildOutputImage(resultArr, pictureBoxSIDE, @"side.jpg");
             
            


        }
       
        private NDArray ReadTensorFromImageFile(string file_name)
        {
            return with(tf.Graph().as_default(), graph =>
            {
                var file_reader = tf.read_file(file_name, "file_reader");
                var decodeJpeg = tf.image.decode_jpeg(file_reader, channels: 3, name: "DecodeJpeg");
                var casted = tf.cast(decodeJpeg, TF_DataType.TF_UINT8);
                var dims_expander = tf.expand_dims(casted, 0);
                return with(tf.Session(graph), sess => sess.run(dims_expander));
            });

        }

        private void buildOutputImage(NDArray[] resultArr,PictureBox pbbox,string path)
        {
            // get pbtxt items
            PbtxtItems pbTxtItems = PbtxtParser.ParsePbtxtFile(labelFile);

            // get bitmap
            Bitmap bitmap = new Bitmap(path);

            float[] scores = resultArr[2].Data<float>();

            for (int i = 0; i < scores.Length; i++)
            {
                float score = scores[i];
                if (score > MIN_SCORE)
                {
                    float[] boxes = resultArr[1].Data<float>();
                    float top = boxes[i * 4] * bitmap.Height;
                    float left = boxes[i * 4 + 1] * bitmap.Width;
                    float bottom = boxes[i * 4 + 2] * bitmap.Height;
                    float right = boxes[i * 4 + 3] * bitmap.Width;

                    Rectangle rect = new Rectangle()
                    {
                        X = (int)left,
                        Y = (int)top,
                        Width = (int)(right - left),
                        Height = (int)(bottom - top)
                    };

                    float[] ids = resultArr[3].Data<float>();
                    if (ids[i] == 21||ids[i]==22||ids[i]==11||ids[i]==12)
                    {

                    }

                    else {
                        string name = pbTxtItems.items.Where(w => w.id == (int)ids[i]).Select(s => s.display_name).FirstOrDefault();
                        drawObjectOnBitmap(bitmap, rect, score, name);
                    }

                   
                }
            }

            //string path = @"output.jpg";
            pbbox.Image = bitmap;
            //bitmap.Save(path);
            // Console.WriteLine($"Processed image is saved as {path}");
        }
        private void drawObjectOnBitmap(Bitmap bmp, Rectangle rect, float score, string name)
        {
            using (Graphics graphic = Graphics.FromImage(bmp))
            {
                graphic.SmoothingMode = SmoothingMode.AntiAlias;

                using (Pen pen = new Pen(Color.Red, 2))
                {
                    graphic.DrawRectangle(pen, rect);

                    Point p = new Point(rect.Right + 5, rect.Top + 5);
                    string text = string.Format("{0}:{1}%", name, (int)(score * 100));
                    graphic.DrawString(text, new Font("Verdana", 8), Brushes.Red, p);
                }
            }
        }
        public Graph ImportGraph()
        {
            throw new NotImplementedException();
        }

        public Graph BuildGraph()
        {
            throw new NotImplementedException();
        }

        public void Train(Session sess)
        {
            throw new NotImplementedException();
        }

        public void Predict(Session sess)
        {
            throw new NotImplementedException();
        }

        public void Test(Session sess)
        {
            throw new NotImplementedException();
        }


        private void Form1_Load(object sender, EventArgs e)
        {
          
        }

        private void Button2_Click(object sender, EventArgs e)
        {
            pictureBoxBOT.Image = null;
            pictureBoxCON.Image = null;
            pictureBoxSIDE.Image = null;
            pictureBoxTOP.Image = null;
        }
    }

**Comment by itzukah** [comment]
Anyone does resolved this issue? I'm facing the problem too. Appreciated your help. Thanks.

**Comment by simonbuehler** [comment]
hi,

it would be great if there would be a way to instantiate the session on a class level and reuse the session from a  class method.
Now there needs to be a method with a `using` block and a loop inside.
There are a few  issues ( #477 #520 #430 ) with the same problem : slow performance when session gets recreated for each prediction.

Any hint if and how to use the session as a class variable would be great!
