### ISSUE TITLE
Does not run in LinqPad

### ISSUE THREAD

**Issue by MovGP0** [SciSharp/TensorFlow.NET#297]
**Steps to reproduce**

1. Open LinqPAD 5 (Developer Edition)
2. add the following NuGet packages: 
    * Tensorflow.NET 0.9.0

This will also install the following packages: 
* Google.Protobuf 3.8.0
* Microsoft.ML.TensorFlow.Redist 0.14.0
* NumSharp 0.10.3

3. insert the following code 
```
var m = new double[,] { { 1.0, 2.0 }, {3.0,4.0} };
var c = tf.constant(m);
c.Dump();
```
4. Execute

**Current Behaviour**

I get a `DllNotFoundException`;  
```
Unable to load DLL 'tensorflow': The specified module could not be found. (Exception from HRESULT: 0x8007007E) | Unable to load DLL 'tensorflow': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```
Stacktrace: 
```
at Tensorflow.c_api.TFE_NewContextOptions()   at Tensorflow.Eager.ContextOptions..ctor()   at Tensorflow.tf..cctor() | at Tensorflow.c_api.TFE_NewContextOptions()   at Tensorflow.Eager.ContextOptions..ctor()   at Tensorflow.tf..cctor()
```

Apparently the problem lies with the `[DllImport("tensorflow", EntryPoint="TFE_NewContextOptions")]` statement.

**Comment by MovGP0** [comment]
same issue with Tensorflow.NET 0.10.0-rc

**Comment by MovGP0** [comment]
apparently the issue is because LinqPad runs in x86/32 bit mode.

**Comment by Oceania2018** [comment]
@MovGP0 What's LinqPad ? TensorFlow only run x64 platform.

**Comment by MovGP0** [comment]
LinqPad is kinda like Python's Jupiter Notebook, but for C#, F# and SQL. 
https://www.linqpad.net/

**Comment by Oceania2018** [comment]
Understand, You can try [SciSharp Cube](https://github.com/SciSharp/SciSharpCube) with Jupyter Notebook built-in.

**Comment by kerryjiang** [comment]
That problem might be caused by the common issue the native tensorflow lib cannot be loaded automatically. You can try install tensorflow to a location like one dir in PATH in advance.

**Comment by MovGP0** [comment]
Thanks for the tipp 👍 I still think that it should work with both. 

Simply unsure if it's better to run LinqPad in x64 mode or rather modify the Tensorflow.NET NuGet to work with both, x68 and x64 dll, dependent on the build target. 

Maybe a `init.ps1` script that modifies the `.csproj` file such that there is something like the following

```xml
<!-- pseudocode -->
<ItemGroup>
<Reference Condition="'$(Platform)' = 'x86'" Include="tensorflow">
   <HintPath>..\lib\tensorflow-x86.dll</HintPath>
</Reference>
<Reference Condition="'$(Platform)' = 'x64'" Include="tensorflow">
   <HintPath>..\lib\tensorflow-x64.dll</HintPath>
</Reference>
</ItemGroup>
```

**Comment by Oceania2018** [comment]
@MovGP0 TensorFlow only works on x64 platform. Try to use the preview [0.10.0rc](https://www.nuget.org/packages/TensorFlow.NET/0.10.0-rc).
