### ISSUE TITLE
tf.gradients producing unexpected results 

### ISSUE THREAD

**Issue by moloneymb** [SciSharp/TensorFlow.NET#303]
It appears that the tf.gradients function has a bug in it. 

For the example x^3 * 0.1 should be 3x^2 * 0.1 but it appears to be x^2 * 0.1.

In TF.Net
```
let x = tf.constant(7.0)
let y = x*x*x*tf.constant(0.1)
sess.run(tf.gradients(y,x)).[0].Data<double>()
//[|4.9|]
```

In Python
```
x = tf.constant(7.0)
y = x*x*x*tf.constant(0.1)
sess.run(tf.gradients(y,x))
#[14.7]
```

**Comment by Oceania2018** [comment]
![image](https://user-images.githubusercontent.com/1705364/61756937-06a0ca80-ad84-11e9-85fb-71cad04500f5.png)
