### ISSUE TITLE
Nuget 0.10.5 - NumSharp.Core is not strong named but TensorFlow.NET is

### ISSUE THREAD

**Issue by dsyme** [SciSharp/TensorFlow.NET#308]
I don't understand why but the NumSharp.Core in the 0.10.5 nuget package is is not strong named but TensorFlow.NET is (meaning TF.NET can't run on .NET 4.7.2)

https://github.com/SciSharp/TensorFlow.NET/blob/master/src/TensorFlowNET.Core/TensorFlowNET.Core.csproj#L36

Oddly the keyfile is mentioned here:

https://github.com/SciSharp/NumSharp/blob/master/src/NumSharp.Core/NumSharp.Core.csproj#L41

Perhaps it was some problem with the build process??

**Comment by Oceania2018** [comment]
I release a patch TF.NET v0.10.1 to include signed NumSharp.
Our library is all `.NET Standard 2.0`, So It should be used in all version of `.NET Framework`.

**Comment by dsyme** [comment]
Thanks all good now
