### ISSUE TITLE
tf.assign missing

### ISSUE THREAD

**Issue by MovGP0** [SciSharp/TensorFlow.NET#313]
example test

```csharp
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Tensorflow;
using static Tensorflow.Python;

namespace TensorFlowNET.UnitTest
{
    [TestClass]
    public sealed class AssignTests
    {
        [TestMethod]
        public void ShouldAssignVariable()
        {
            var raw_data = new[] { 1.0, 2.0, 8.0, -1.0, 0.0, 5.5, 6.0, 16.0 };
            var expected = new [] { false, true, false, false, true, false, true };

            var spike = tf.Variable(false);
            
            with<Session>(tf.Session(), sess =>
            {
                spike.initializer.run();
                foreach (var i in range(1, raw_data.Length))
                {
                    if (raw_data[i] - raw_data[i-1] > 5d)
                    {
                        var updater = tf.assign(spike, tf.constant(true));
                        updater.eval();
                    }
                    else
                    {
                        tf.assign(spike, false).eval();
                    }
                    
                    Assert.AreEqual(spike.eval(), expected[i-1]);
                }
            });
        }
    }
}
```
Since I am not familiar with the project right now, I am unsure how to implement it myself.

**Comment by MovGP0** [comment]
Also I am unsure what the `RefVariable.eval()` method should return. does it refer to `_variable` or `_snapshot`?

**Comment by MovGP0** [comment]
apparently the implementation on tf is straight-forward. in `tf.ops.cs` add the following: 
```csharp
public static Tensor assign(Tensor @ref, object value, bool validate_shape = true, bool use_locking = true, string name = null) 
            => state_ops.assign(@ref, value, validate_shape, use_locking, name);
```
and in `RfeVariable.cs` add
```csharp
public Tensor eval() => _variable;
```
Problem here is that `state_obs.assign` throws a `NotImplementedException`.

**Comment by Oceania2018** [comment]
@MovGP0 Could you PR your UnitTest to [VariableTest](https://github.com/SciSharp/TensorFlow.NET/blob/master/test/TensorFlowNET.UnitTest/VariableTest.cs)?

**Comment by MovGP0** [comment]
I could. But I'm unsure how useful it is, since the test is failing and therefore further preventing a build.

**Comment by Oceania2018** [comment]
@MovGP0, you can annnotate `[Ingore("REASON")]` to disable the UnitTest.

![image](https://user-images.githubusercontent.com/1705364/61918154-089a9300-af16-11e9-80a5-096008c4842f.png)

**Comment by Oceania2018** [comment]
@MovGP0 It's been implemted [here](https://github.com/SciSharp/TensorFlow.NET/commit/ae9a161cd7ade6afef1af6f4b9b5a0f5674ca37d). Please let me know if you have any issue.
