### ISSUE TITLE
Run GPU and CPU by falling back to CPU if no GPU

### ISSUE THREAD

**Issue by mjbedford2017** [SciSharp/TensorFlow.NET#333]
Hello, 

I am following this instruction on the getting started:

> ### For CPU version
> PM> Install-Package SciSharp.TensorFlow.Redist
> ### For GPU version (CUDA and cuDNN are required)
> PM> Install-Package SciSharp.TensorFlow.Redist-Windows-GPU

I want my project to run on GPU if it can but also, to be universal, fall back to CPU if no GPU. The way things are worded above and throughout the site makes it sound like I can do one or the other. For example, I want to install the package above for GPU version but it says CUDA and cuDNN are required. 

Do I install both packages to handle both types of machines? 

I saw the code to use session options to specify GPU. Do I do this still and it will still run or fallback on CPU if no GPU?

Thanks!

**Comment by Oceania2018** [comment]
@mjbedford2017 @Jiuyong PRed a quick/ simple solution.

**Comment by captainst** [comment]
for some unknown reason, inside visual studio 2017 community edition, I can not have both **TensorFlowNET.Examples** and **TensorFlowNET.Examples.GPU** included **simutanously** in the solution. To be able to properly rebuild the solution, you need to exclude one of the above 2 projects.

Another thing to mention is that the solution uses tensorflow 1.14.0, so you might need CUDA 10.0 and cudnn 7.4.2 to work properly.

**Comment by Jiuyong** [comment]
Yes, you say the situation is present and correct. But there's no way. Separating the two directories means repeatedly downloading the data. If put together, the NetCore project has this problem.
