### ISSUE TITLE
TensorFlow.Net doesn't work with net461 applications

### ISSUE THREAD

**Issue by AndreiDegtiarev** [SciSharp/TensorFlow.NET#340]
I want to use TF.Net in my net461 application, but I get exception. To reproduce it please change in TensorFlowNET.Examples.FSharp.fsproj the TargetFramework to the net461. After compilation there is exception at the line “tf.placeholder(tf.float64, new TensorShape(N_points,n_input))”
Exception sounds like The DLL Tensorflow: The module was not found. Exception HRESULT: 0x8007007E. 
StackTrace:
   at Tensorflow.c_api.TFE_NewContextOptions()
   at Tensorflow.Eager.ContextOptions..ctor() in D:\Projects\TensorFlow.NET-master\src\TensorFlowNET.Core\Eager\ContextOptions.cs:line 11
   at Tensorflow.tf..cctor() in D:\Projects\TensorFlow.NET-master\src\TensorFlowNET.Core\tf.cs:line 35
The version from end of May worked in this configuration without any troubles.

**Comment by Oceania2018** [comment]
Please make sure your're running on x64 platform.

**Comment by AndreiDegtiarev** [comment]
The problem is, that in case of net461-TargetFramework the tensorflow.dll will be not copied into output folder.

**Comment by Oceania2018** [comment]
Can you check if changing project to `<TargetFrameworks>net461;netstandard2.0</TargetFrameworks>` ?

**Comment by AndreiDegtiarev** [comment]
With the TargetFrameworks is the same result. I guess the difference between netstandartd and net461 platforms is the “TensorFlowNET.Examples.FSharp.deps.json” file which in case of netstandartd resolves dependency from tensorflow.dll. In this file there is explicit path to this dll. For my project I solved this problem by processing of postbuild event. I don’t like it and it would be nice if better solution will be provided.

**Comment by Oceania2018** [comment]
If you want full .NET Standard support, consider using .NET 4.7.2 or later.
https://weblog.west-wind.com/posts/2019/Feb/19/Using-NET-Standard-with-Full-Framework-NET#the-first-version-that-fully-net-standard-20-compliant-is-472

**Comment by Jiuyong** [comment]
Change project's PlatformTarget from default "AnyCPU" to "x64" and re build.

**Comment by Oceania2018** [comment]
@AndreiDegtiarev Resolved?

**Comment by AndreiDegtiarev** [comment]
I have following settings: 
 <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
The result is the same: tensorflow.dll is not copied into bin folder and the problem with exception remains

**Comment by Jiuyong** [comment]
Did you rebuild it ?

**Comment by AndreiDegtiarev** [comment]
Yes, I made Clean and Rebuild.

**Comment by Jiuyong** [comment]
If you want to run first, you can test the dll to the output directory and run it first. If you want to solve the problem fundamentally, you may have to wait, because we havenundefinedt recreated this bug. yet. Weundefinedll try to repeat the problem completely later.
chinese source:
如果你现在想首先运行起来，你可以将这个 dll 先考到输出目录，先运行起来。
如果你是想要根本性的解决问题，可能还要等等，因为我们还没复现这个bug。
稍后我们再尝试完全复现下这个问题。

**Comment by AndreiDegtiarev** [comment]
@Jiuyong. This problem I have reproduced in the project TensorFlowNET.Examples.FSharp.fsproj. This project belongs to Tensorflow.Net. Could you please try it in your environment?

**Comment by Jiuyong** [comment]
@AndreiDegtiarev I put in the code that I can run successfully, and you can try to run down and have a look.
