### ISSUE TITLE
Question: NLP Support

### ISSUE THREAD

**Issue by dgerding** [SciSharp/TensorFlow.NET#352]
Hi,
Sorry to post here, just wondering which NLP libraries are in "most useable" form so far?  Thanks!

Dave G

**Comment by Oceania2018** [comment]
Try this: https://github.com/curiosity-ai/catalyst

**Comment by Nucs** [comment]
Please re-open this issue if you have further related questions.

**Comment by Oceania2018** [comment]
@dgerding We're planning to implement the BERT model.

**Comment by flieks** [comment]
@Oceania2018 Are there any updates on the bert model ?
Thanks

**Comment by Oceania2018** [comment]
We don’t have any further progress about BERT model. We’re struggling to implement the YOLOv3. We need help.

**Comment by flieks** [comment]
Right, there are so many things in AI. I appreciate the efforts.

I dont know anything about python. Just looking for a good .NET NLP library with dutch support

**Comment by GeorgeS2019** [comment]
Just found this.
[BERT for ML.NET](https://github.com/GerjanVlot/BERT-ML.NET)
