### ISSUE TITLE
SciSharp.TensorFlow.Redist package is not copying tensorflow.dll to output directory.

### ISSUE THREAD

**Issue by Nucs** [SciSharp/TensorFlow.NET#361]
[SciSharp.TensorFlow.Redist-Windows-GPU](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist-Windows-GPU/1.14.0) and [SciSharp.TensorFlow.Redist](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist/1.14.0) nuget packages are not performing copy correctly in cases when the project is:
1. targeting netstandard
2. targeting netcore (need to verify)
3. Located in an unusual location relative to the solution directory which contains the folder `packages` folder.

The redists fail to copy tensorflow.dll to output directory because it can't find `/packages` folder.

When a project targets netstandard, `../../packages` does not exist.
Instead it uses global nuget cache folder: `%userprofile%\.nuget\packages`

Here is the msbuild file that takes care of resolving the copying: 
>scisharp.tensorflow.redist.1.14.0.nupkg\build\netstandard2.0\SciSharp.TensorFlow.Redist.props
```XAML
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <!--
  NuGet packages.config doesn't support native assemblies automatically,
  so copy the native assemblies to the output directory.
  -->
  <ItemGroup Condition="Exists('packages.config') OR
                        Exists('$(MSBuildProjectName).packages.config') OR
                        Exists('packages.$(MSBuildProjectName).config')">
    <Content Include="$(MSBuildThisFileDirectory)\..\..\runtimes\win-x64\native\*.dll"
             Condition="'$(PlatformTarget)' == 'x64'">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
      <Link>%(Filename)%(Extension)</Link>
    </Content>
    <Content Include="$(MSBuildThisFileDirectory)\..\..\runtimes\win-x86\native\*.dll"
             Condition="'$(PlatformTarget)' == 'x86'">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
      <Link>%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>

</Project>
```

**Comment by Nucs** [comment]
Related issues, https://github.com/SciSharp/TensorFlow.NET/issues/361 https://github.com/SciSharp/TensorFlow.NET/issues/297

**Comment by chaami** [comment]
Hi,
My understanding is that the nuget default behavior when resolving dependencies is to install the packages in the global user repository.
Visual studio should be able to do what's needed when running/debugging to make the dlls available when needed, a copy being made only in cases of `publish`.
Are you specifying that your project is targeting the win-x64 runtime ?
Are you getting an error saying that the tensorflow.dll couldn't be found when attempting to run ?
Kind regards.

**Comment by Oceania2018** [comment]
@chaami Thanks for contribution.

Do you change the name `SciSharp.TensorFlow.Redist` to `SciSharp.TensorFlow-Cpu.Redist`.
The script is original written by @harishsk. 
Can you PR and I will assign @harishsk to review it.

**Comment by Nucs** [comment]
This issue still persists, I have no clue to why it was closed.

**Comment by Nucs** [comment]
After looking into it further, I think this issue is irrelevant as explained [here](https://stackoverflow.com/a/45845351/1481186):

> It doesn't make sense to create a .NET Standard console app.
> 
> You can think of .NET Standard like you would an interface in C#. .NET Standard is an interface, then there's concrete implementations of it in .NET Framework, .NET Core and other platforms. .NET Standard makes sense for class libraries, but a console app needs to actually run on a specific concrete implementation.
> 
> Thus, there is no Visual Studio project template for .NET Standard console apps. You can create a console app for .NET Framework or .NET Core and then consume .NET Standard class libraries.
