### ISSUE TITLE
Tensor Indexing

### ISSUE THREAD

**Issue by Nucs** [SciSharp/TensorFlow.NET#368]
The following is not implemented:
``` python
import tensorflow as tf

with tf.Session() as sess:
    const = tf.constant([1, 2])
    ret = const[0]
    print(sess.run(ret))

# prints 1
```

C#'s equivalent:
``` C#
Tensor const = tf.constant(new int[]{1,2});
Tensor ret = const[0];
```

**Comment by Oceania2018** [comment]
@Nucs For some other reason, we use `tensor.slice`.

![image](https://user-images.githubusercontent.com/1705364/63898949-a3c4d380-c9c0-11e9-81a6-cae4900a1ee0.png)

You can try to improve it.

**Comment by Oceania2018** [comment]
Will be avaiable on v0.11.2.
