### ISSUE TITLE
TensorFlow.NET on iOS ,Android 

### ISSUE THREAD

**Issue by ayadgithub** [SciSharp/TensorFlow.NET#376]
Hello ,

I understand the plugin is targeting .Net environment but are there any plans for providing Android and iOS binding so that it can be run on Xamarin.iOS ,Xamarin.Android and Unity3D ?

Regards
Ayad

**Comment by Nucs** [comment]
Tensorflow.NET is a binding of Tensorflow's API called `c_api` which uses TF's dll that are not compiled for mobile uses (Android or IPhone).
In case of Android, TF provides a different light-weight library called [Tensorflow Lite](https://www.tensorflow.org/lite) which in a nutshell works completely different from our binding.

Given these facts, our bindings and architecture are not compatible with mobile platforms.
To do that we would have to re-do the entire library in a completely new and seperate project which at this moment we do not plan (@Oceania2018 Please verify my statement).

If I remember correctly, Xamarin is able to run Java code so you can try and replicate 
the following [example](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android)

**Comment by Nucs** [comment]
In either-way you can not create a model using `Tensorflow Lite` so you can use TF.NET to pre-generate model file in a separate project (from Xamarin) that will be used by `Tensorflow Lite`.

**Comment by Oceania2018** [comment]
@ayadgithub Right, you have to use TensorFlow Lite.

**Comment by ayadgithub** [comment]
Thank you all for the responses .
