### ISSUE TITLE
Using unknown dimension in a TensorShape

### ISSUE THREAD

**Issue by Nucs** [SciSharp/TensorFlow.NET#377]
Currently `TensorShape` only support int/long dimensions. 
We sometimes need to use an unknown dimension that represents a varying batch size that changes from run to run. This is heavily used in reinforcement-learning algorithms.

If you inspect how the following code was written internally, it should explain how python handles None/null dimension
``` python
from tensorflow import TensorShape
from tensorflow.python.framework import tensor_shape

tensorShape: TensorShape = tensor_shape.as_shape((None, 1, 2))
```

The following code is a real use case example
``` python
with tf.Session().as_default() as sess:
    input = tf.placeholder(tf.float64, shape=[None, 3, 3])
    print(input.shape)
    op = tf.layers.flatten(input)
    print(op.shape)
    op = op[3]
    print(op.shape)
    sess.run(tf.global_variables_initializer())

    input_data = np.arange(5 * 3 * 3).reshape((5, 3, 3))
    ret = sess.run(op, feed_dict={input: input_data})

    print(ret)
```

Outputs:
``` python
(?, 3, 3)
(?, 9)
(9,)
[27. 28. 29. 30. 31. 32. 33. 34. 35.]
```

**Comment by Nucs** [comment]
After this is done, `tf.layers.flatten(input)` will need to be updated to recognize unknown dimension. I'll take care of that.

**Comment by Oceania2018** [comment]
Use new Shape(-1, 3, 3)
