### ISSUE TITLE
Error: "Current graph is not default graph." while moving from TF.NET 0.10.10 to 0.11.3

### ISSUE THREAD

**Issue by ashbhandare** [SciSharp/TensorFlow.NET#384]
While trying to move ML.NET from TF.NET 0.10.10 to 0.11.3, getting:

> Tensorflow.RuntimeError
> HResult=0x80131500
> Message=Current graph is not default graph. Default Graph Key: grap-key-6/, Current Graph Key: grap-key-1/
> Source=TensorFlow.NET
> StackTrace:
> at Tensorflow.Graph.OperationByName(String operName)
> at Microsoft.ML.Transforms.Dnn.DnnUtils.Runner.ParseOutput(String operation) in C:\Users\aibhanda\Source\Repos\ashbhandare-achinelearning\src\Microsoft.ML.Dnn\DnnUtils.cs:line 446

Reproducer:
https://github.com/ashbhandare/machinelearning/tree/debug-TF.NET-0.10.10-0.11.3
while running sample: "ImageClassification"
commit ID: cce36f4511d331803baab874313012634fc9230f

**Comment by Nucs** [comment]
@ashbhandare Please take a look at the last limitation in our [wiki](https://github.com/SciSharp/TensorFlow.NET/wiki/Multithreading#limitations).
In your case, the example uses a custom version of TaskScheduler but regardless, it still needs to set the session and graph as default at the beggining of the pipeline.

**Comment by ashbhandare** [comment]
Is this a change in the recent version 0.11.3? Because the error doesn't happen in 0.10.10

**Comment by Nucs** [comment]
0.10.10 Did not support multithreading and caused heap corruption due to Tensorflow's c_api not being thread-safe.

**Comment by Nucs** [comment]
![image](https://user-images.githubusercontent.com/649919/64657391-d39dbd80-d43b-11e9-8ca8-b40c23b978be.png)

Thread ID 1 is the creator of the Session and Graph (via model loading), You to call at the start of the pipeline (assuming only the same thread uses the pipeline untill it is finished):
`DnnModel.Session.as_default()` and `DnnModel.Session.Graph.as_default()`

**Comment by Nucs** [comment]
There is a different approach to fixing this issue.
The exception occurs when calling `_session.graph.OperationByName(string)`, 
If the Operation returned is never used with any methods of our library `tf.*` (and giving a quick look, it doesn't look like you do).

You can implement a custom method that skips that check for your own custom use:
```C#
/// <summary>
///     Get operation with given <paramref name="operName"/>
/// </summary>
/// <exception cref="ValueError">When <paramref name="operName"/> is not found current graph.</exception>
/// <exception cref="RuntimeError">When tf.get_default_graph() is not current graph.</exception>
/// <example>
///     graph.GetOperationByName("CustomInputName");
/// </example>
public Operation OperationByName(string operName)
{
    if (operName == null) 
        throw new ArgumentNullException(nameof(operName));

    var handle = c_api.TF_GraphOperationByName(_handle, operName);
    if (handle == IntPtr.Zero)
        throw new ValueError($"Could not find operation \"{operName}\" inside graph \"{_graph_key}\".");

    return new Operation(handle, g: this);
}
```

**Comment by Oceania2018** [comment]
I don’t understand why you use multiple threads to call session.run(), when do training, c_api already runs in parallel. In high level using Task won’t speed up the training process.

**Comment by Nucs** [comment]
@Oceania2018, The calls are for `_session.graph.OperationByName(string),` which they use internally for logic-purposes rather than training or predicting.

**Comment by Nucs** [comment]
Issue has been resolved.
