### ISSUE TITLE
tf.train.Saver fails to load what it has saved

### ISSUE THREAD

**Issue by meesoft** [SciSharp/TensorFlow.NET#391]
I tried adding 
```
                var saver = tf.train.Saver();
                Directory.CreateDirectory("checkpoint"); saver.save(sess, @"checkpoint\dr");
```
after Train in the DigitRecognitionCNN example and then using
```
                saver.restore(sess, @"checkpoint\dr.index");
```
to load it back, but it fails with TensorflowException: Tensor name "conv1/b" not found in checkpoint files.
I've had similar errors loading checkpoints saved directly from tf/Python.

**Comment by Nucs** [comment]
Can you create a repository or upload a zip so we can to reproduce it locally?

**Comment by meesoft** [comment]
Just copy-paste these 4 lines in after the Train(sess) call in DigitRecognitionCNN.Run() (line 84)
```
                var saver = tf.train.Saver();
                System.IO.Directory.CreateDirectory("checkpoint");
                saver.save(sess, @"checkpoint\dr");
                saver.restore(sess, @"checkpoint\dr.index");
```
and run the example...

**Comment by meesoft** [comment]
Looks like it actually works if I don't add a file extension, so just 
`saver.restore(sess, @"checkpoint\dr");`
- looks like it was just my lack of tensorflow experience
