### ISSUE TITLE
tf.assign does not work with tensor to tensor assignment.

### ISSUE THREAD

**Issue by yj20005237** [SciSharp/TensorFlow.NET#397]
I want to change value of a variable with some operations 
Here's a simple example.
```
            W = tf.Variable(-1, name: "weight_" + 1, dtype: tf.float32);
            var init = tf.global_variables_initializer();
            sess.run(init);
            var reluEval = tf.nn.relu(W);
            var nonZero = tf.assign(W, reluEval);
```

As in the code above, W is initialized with -1 and after initialization, the 'nonZero' operation is defined shown in the code.

I expected that after using `sess.run(nonZero)`, W will be changed to 0 because of the relu operation. But in the line of `var nonZero = tf.assign(W, reluEval);`, I've got an exception message : `System.Exception: 'Input 'resource' passed float expected resource while building NodeDef 'AssignVariableOp' using Op<name=AssignVariableOp; signature=resource:resource, value:dtype -> ; attr=dtype:type; is_stateful=true>'`

Does anyone have an idea?

**Comment by Oceania2018** [comment]
@yj20005237 , this issue has been fixed, will be available for v0.11.5 two weeks later.
