### ISSUE TITLE
How to set timeout for session?

### ISSUE THREAD

**Issue by unominhtuan** [SciSharp/TensorFlow.NET#401]
Hello, I want to ask how to set a timeout for a session. Sometimes, the session may not work, and it may take up to 1 minute for a prediction. I am a newbie, thanks for any help

**Comment by Oceania2018** [comment]
@unominhtuan Yes, you can pass `RunOptions`: https://www.tensorflow.org/api_docs/python/tf/RunOptions#timeout_in_ms

**Comment by unominhtuan** [comment]
@Oceania2018  
Is there any sample code for c # and tensorflow.net? Sorry I'm new, I tried but it didn't work.
Thanks for any help

**Comment by Oceania2018** [comment]
@unominhtuan Try this:
```csharp
                var opts = new SessionOptions();
                opts.SetConfig(new ConfigProto
                {
                    OperationTimeoutInMs = 1000
                });
```

**Comment by Oceania2018** [comment]
Please reopen this issue if it is still not working.
