### ISSUE TITLE
Graph import gives graph with 0 nodes

### ISSUE THREAD

**Issue by Arrjuun** [SciSharp/TensorFlow.NET#402]
Whenever I try to import a model, the return is true but the graph has no nodes
I'm not sure if I'm doing something wrong.  I'm able to run the model using python.

Tensorflow.Net 0.11.3 was a direct VS nuget install  
Microsoft.ML.TensorFlow.Redist.0.14.0

The [model](https://drive.google.com/drive/folders/1DYdxvMXm6n6BsOy4dOTbN9h43F0CoUoK?usp=sharing) I am using is from [FaceBoxes](https://github.com/TropComplique/FaceBoxes-tensorflow)

![TFNET_Error](https://user-images.githubusercontent.com/7102020/65756243-4abc9c80-e132-11e9-9fcf-3cf8383314d6.jpg)

Also, I'm having the same issue when I'm importing the models in Tensorflow.Net Examples.

**Comment by Oceania2018** [comment]
Have you tried use this redist https://www.nuget.org/packages/SciSharp.TensorFlow.Redist/

**Comment by Arrjuun** [comment]
Thank you, that helped.

But I think the below is what caused the confusion.

I was using the graph.get_operation_by_name from the example [here](https://tensorflownet.readthedocs.io/en/latest/ImageRecognition.html) which was saying there was no such operation. Changing that to graph.OperationByName worked.
