### ISSUE TITLE
SciSharp.TensorFlowHub Nuget package out of date

### ISSUE THREAD

**Issue by BradLewis** [SciSharp/TensorFlow.NET#403]
I'm trying to use the nuget package found here https://www.nuget.org/packages/SciSharp.TensorFlowHub/ for access to the MnistModelLoader, but when I try to load the data like in the MNIST DigitRecognitionCNN example, I get the error

> System.AggregateException: 'One or more errors occurred. (Method not found: 'NumSharp.NDArray NumSharp.NDArray.get_Item(NumSharp.NDArray)'.)'.

The named argument `showProgressInConsole`  also doesn't exist in the package so I must use

`var mnist = MnistModelLoader.LoadAsync(".resources/mnist", oneHot: true).Result;`

instead of 

`var mnist = MnistModelLoader.LoadAsync(".resources/mnist", oneHot: true, , showProgressInConsole: true).Result;`

If I reference the current Tensorflowhub project in this repository rather than the Nuget package it all works fine, so I expect that this just needs the Nuget package to be updated.

**Comment by kerryjiang** [comment]
I will fix it today.

**Comment by kerryjiang** [comment]
We released a new package, @BradLewis, could you try again with that new package?
https://www.nuget.org/packages/SciSharp.TensorFlowHub/0.0.3

**Comment by Nucs** [comment]
@kerryjiang, I'll make sure to upgrade NumSharp every time I release.

**Comment by BradLewis** [comment]
Yup it all works fine now, thanks!
