### ISSUE TITLE
tf.split

### ISSUE THREAD

**Issue by Jamaslab** [SciSharp/TensorFlow.NET#407]
Missing API: tf.split

https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/split

**Comment by Nucs** [comment]
Our functions are generally generated. If you can't find it in `tf.*` then it is likely to be in other place.
![image](https://user-images.githubusercontent.com/649919/65892669-5c5ea800-e3af-11e9-8a3d-5eca140b58cc.png)

In this case in `gen_array_ops` and `gen_ops`.
@Oceania2018 An alias in tf namespace will be enought.

**Comment by Jamaslab** [comment]
thank you so much!

**Comment by Oceania2018** [comment]
@Jamaslab It's relatively easy to add. Appreciate if you can PR.

**Comment by Jamaslab** [comment]
Yep will do ASAP

**Comment by Nucs** [comment]
Added in PR #408
