### ISSUE TITLE
tf.layers.batch_normalization throws null-reference exception

### ISSUE THREAD

**Issue by Nucs** [SciSharp/TensorFlow.NET#412]
The following code fails:
```C#
var inputs1 = tf.placeholder(tf.float32, new TensorShape(1, 4));
var x = tf.layers.batch_normalization(inputs1);
```
Exception

> System.NullReferenceException
>   HResult=0x80004003
>   Message=Object reference not set to an instance of an object.
>   Source=TensorFlow.NET
>   StackTrace:
>    at Tensorflow.tensor_util._ConstantValue(Tensor tensor, Boolean partial) in C:\Users\Eli-PC\Desktop\SciSharp\TensorFlow.NET\src\TensorFlowNET.Core\Tensors\tensor_util.cs:line 50

![image](https://user-images.githubusercontent.com/649919/66008119-c2d1ec00-e4bd-11e9-845f-1000d7b7bbb2.png)

I believe I'm not doing anything wrong as it should work without specifying `training` argument.

**Comment by Nucs** [comment]
In [this documentation](https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/layers/batch_normalization) `training` has a default value of `False` but in TF.NET we have `null`.

**Comment by Nucs** [comment]
After adding a boolean placeholder for `training`
```C#
var inputs1 = tf.placeholder(tf.float32, new TensorShape(1, 4));
var training = tf.placeholder(tf.@bool, name: "training");
var x = tf.layers.batch_normalization(inputs1, training: training);
```
I get the following exception:

> System.EntryPointNotFoundException
>   HResult=0x80131523
>   Message=Unable to find an entry point named 'AddControlInput' in DLL 'tensorflow'.
>   Source=TensorFlow.NET
>   StackTrace:
>    at Tensorflow.c_api.AddControlInput(IntPtr graph, IntPtr op, IntPtr input)
>    at Tensorflow.Operation._add_control_input(Operation op) in C:\Users\Eli-PC\Desktop\SciSharp\TensorFlow.NET\src\TensorFlowNET.Core\Operations\Operation.Control.cs:line 46

![image](https://user-images.githubusercontent.com/649919/66008524-90c18980-e4bf-11e9-915d-f53825ee1b81.png)

**Comment by Oceania2018** [comment]
Same as #400

**Comment by Oceania2018** [comment]
This version will help you: https://www.nuget.org/packages/SciSharp.TensorFlow.Redist/1.14.1

**Comment by meesoft** [comment]
1.14.1 works, but unfortunately it is not available in a GPU version so it is not really of any practical use

**Comment by meesoft** [comment]
Any plans for a 1.14.1 release of SciSharp.TensorFlow.Redist-Windows-GPU? ;)

**Comment by Oceania2018** [comment]
@meesoft My local compilation env doesn't work. Once the issue is fixed, I'll release GPU version.

**Comment by Oceania2018** [comment]
@meesoft @moloneymb Can you try Linux [version 1.14.1](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist-Linux-GPU/1.14.1)?

**Comment by meesoft** [comment]
Sorry, I only have Windows

**Comment by moloneymb** [comment]
I'll test it, either today or tomorrow. Thanks Haiping

**Comment by Oceania2018** [comment]
@meesoft @moloneymb [Windows GPU 1.14.1](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist-Windows-GPU/) released.

**Comment by meesoft** [comment]
Great, thanks, it seems to work fine

**Comment by tcwicks** [comment]
Its still way beyond broke. Oh and by the way Windows GPU 1.14.1 is a corrupt DLL file.
