### ISSUE TITLE
Redist for AVX workload.

### ISSUE THREAD

**Issue by turowicz** [SciSharp/TensorFlow.NET#417]
Can we please get a version of `SciSharp.TensorFlow.Redist` that would come with a TF compiled with `AVX`?

**Comment by turowicz** [comment]
DISCLAIMER: Large clients have powerful CPUs in their Data Centers but no GPUs unfortunately.

**Comment by Oceania2018** [comment]
@turowicz That make sense.

If you are building TensorFlow on one CPU type but will run TensorFlow on a different CPU type, then consider supplying a more specific optimization flag as described in the [gcc documentation](https://gcc.gnu.org/onlinedocs/gcc-4.5.3/gcc/i386-and-x86_002d64-Options.html).

The problem is I don't know what optimization flag I should add for your situation.

**Comment by turowicz** [comment]
@Oceania2018 not a problem. 

I recommend generating all permutations for AVX, SSE and FMA with a build script. 

Other projects offer redistributables in this way, such as here for Python: 
https://github.com/evdcush/TensorFlow-wheels#cpu-builds

**Comment by turowicz** [comment]
PS. I get 3-4x performance increase with AVX2, SSE and FMA on in the client environment.

**Comment by Nucs** [comment]
AVX2 is on most modern CPUs, AVX1 is on all CPUs since 9 years ago.
We should have a separate nuget package although our main package can be compiled safely with AVX1.

**Comment by Oceania2018** [comment]
@turowicz That's cool, I havn't compared them yet.
@Nucs I'll make a windows version in a few days.

**Comment by turowicz** [comment]
Can we get a unix version too? We're all Ubuntu / OSX based.

**Comment by Nucs** [comment]
@turowicz We don't have a custom built tensorflow.dll. All we did is download the official dll from tensorflow's website and publish it via nuget for comfort.
We will add AVX2 and maybe unix build (depends on @Oceania2018).
My point is that for now you can build the `tensorflow.dll` yourself for unix with the flags you want and use it. Our binding will work flawlessly.

**Comment by Oceania2018** [comment]
@turowicz I've found a repo contains the binaries: https://github.com/lakshayg/tensorflow-build

**Comment by turowicz** [comment]
@Oceania2018 @Nucs that's how I've been doing it so far - manually. It would be really useful if you provided the nuget packages for the solution to be "clean".

Surely you have a build server?

**Comment by Oceania2018** [comment]
We don’t have build server.
