### ISSUE TITLE
Error in Doc Constant.md

### ISSUE THREAD

**Issue by JranZu** [SciSharp/TensorFlow.NET#419]
https://github.com/SciSharp/TensorFlow.NET/blob/master/docs/source/Constant.md

I'd fix it if I knew what it was supposed to say. Right at the beginning we see: 

> Like in a linear model $\tilde{y_i}=\boldsymbol{w}x_i+b$, constant $b$ can be represented 

I assume that there is a formatting error in the above... If not I have no idea what it is trying to say :D

**Comment by Oceania2018** [comment]
@JranZu The characters are LaTeX math. It doesn't display correctly on GitHub.
