### ISSUE TITLE
'device_count' setting not working

### ISSUE THREAD

**Issue by vermorel** [SciSharp/TensorFlow.NET#426]
I need to control the number of CPUs to be used by TensorFlow on a Windows 10 machinse (6 cores, 12 vCPUs). I am trying with the following config:

    var config = new ConfigProto();
    config.InterOpParallelismThreads = 1;
    config.InterOpParallelismThreads = 1;
    config.DeviceCount.Clear();
    config.DeviceCount.Add("CPU", 1);

However, a cursory inspection of the Task Manager indicates that TensorFlow is still using about 70% of my CPU resources which is clearly above above the capacity above. I suspect that the `device_count` setting is not passed to Tensorflow underneath.

Any help would be welcome.

**Comment by Oceania2018** [comment]
@vermorel I'm pretty sure the config has been passed into tensorflow. But it doesn't work. It uses `TF_SetConfig` to set configs.

I print log in `C++`:
![image](https://user-images.githubusercontent.com/1705364/67149787-23f70f00-f275-11e9-8559-d3fc7697897c.png)
Result:
![image](https://user-images.githubusercontent.com/1705364/67149836-c7482400-f275-11e9-94cd-6feffbdbe96d.png)

This is invoking function:
![image](https://user-images.githubusercontent.com/1705364/67149846-e8a91000-f275-11e9-857e-402a83ccbfa5.png)

If I pass in empty config:
![image](https://user-images.githubusercontent.com/1705364/67149852-feb6d080-f275-11e9-81cc-6b0aa6259c2e.png)
