### ISSUE TITLE
Null reference exception

### ISSUE THREAD

**Issue by raghavendrasri** [SciSharp/TensorFlow.NET#427]
Hi,
I am performing following operation. I am getting null reference exception.  
Please let me know , whether I am missing anything.  Looks op was null  log shows .When I debug the unit test case in Tensorflow.net

var data = new float[166];
            var x1 = new Tensor(data);
            var x6 = tf.reshape(x1, new int[] { 166, 1 }, "test_9");

Regards

**Comment by captainst** [comment]
Should be a bug. the _op member of the tensor is null, thus causing the error.@Oceania2018

**Comment by Oceania2018** [comment]
@raghavendrasri 
You should use high level api started with `tf.xxx`.
Change your code to:
```csharp
var data = new float[166];
var x1 = tf.constant(data);
var x6 = tf.reshape(x1, new int[] { 166, 1 }, "test_9");
```

@captainst Thanks for your help.
