### ISSUE TITLE
UWP 32 bit System

### ISSUE THREAD

**Issue by weizhuang-93** [SciSharp/TensorFlow.NET#429]
Hi, i would like to use this on HoloLens, which is a 32 bit Windows. Would this work if i have a 32 bit wheel?

**Comment by Oceania2018** [comment]
Related to https://github.com/tensorflow/tensorflow/issues/20362

**Comment by weizhuang-93** [comment]
@Oceania2018 , so it still won't work right as tensorflow is fundamentally not supporting 32bit system?
i tried with tensorflowsharp but got some errors that i cant fix. thinking tf.net might help in some way but too bad.

**Comment by Oceania2018** [comment]
Yes, I don’t thing Tensorflow can run in 32 bit system. I’ve never tried that.
