### ISSUE TITLE
Prediction Performance Issue

### ISSUE THREAD

**Issue by domtheluck** [SciSharp/TensorFlow.NET#430]
I tried TensorFlow.Net as a alternative to [TensorFlowSharp](https://github.com/migueldeicaza/TensorFlowSharp) for model prediction only (our training is done 100% in python) and so far the Session.run (TensorFlow.Net) took twice as long to execute than TFSession.Runner.Run (TensorFlowSharp) for the exact same model and same input dataset.

Session.run: 129ms
TFSession.Runner.Run: 67ms

**Comment by domtheluck** [comment]
Looks like a error on my side. I was using a new session on each prediction.
Sorry my bad :)

**Comment by solarflarefx** [comment]
I seem to be experiencing some performance bottleneck issues on my end on TF.NET as compared to Python.  Do you have an example of what in particular you were doing wrong and how you corrected it?

**Comment by Oceania2018** [comment]
@solarflarefx Can you post code here if possible ?

**Comment by solarflarefx** [comment]
@Oceania2018 I made this a separate issue: https://github.com/SciSharp/TensorFlow.NET/issues/520

I have posted code along with the conditions over there.
