### ISSUE TITLE
Unable to load DLL 'tensorflow' 

### ISSUE THREAD

**Issue by emelrad12** [SciSharp/TensorFlow.NET#432]
So I installed it using the TensorFlow CPU version and tried one of the examples but on 

`var hello = tf.constant(str);` it errors with
`{"Unable to load DLL 'tensorflow': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"}`

I also cant add manually the tensorflow dll it says it is not valid.

Also tried using older version of TensorFlow.net

Edit: It works when using net core, might wanna add that somewhere that it is for net core only,

**Comment by Oceania2018** [comment]
Releated to https://github.com/SciSharp/TensorFlow.NET/issues/340
