### ISSUE TITLE
Error run model on GPU: Out of GPU memory

### ISSUE THREAD

**Issue by quintakFR** [SciSharp/TensorFlow.NET#434]
**System information**
- OS: Windows 10 Pro
- TensorFlow dll version: 2.0
- TensorFlow.NET version: 0.11.1.0
- GPU: NVIDIA GeForce RTX 2060 6Go
- CUDA version:  10.1.243
- cuDNN version: 7.6.4.38

**Describe the problem**
I am using TensorFlow.NET to run a saved model and I have an issue to run it on the GPU.
The learning use aroung 1.5Go on the GPU memory so it should be the same for the prediction but it didn't.
When I run the model on the CPU, the prediction is performed but on the GPU it didn't and I have the following error message. I use the following code to set the options of the session for GPU usage. Using nvidia-smi I saw that almost all GPU memory (around 5.8Go) is allocated when run method is executed. So it looks like the definition of memory fraction per process is not used. Is it an error in my code to configure the session or an internal bug of TensorFlow.NET?

**Code sample**
```
SessionOptions sessionOptions = new SessionOptions();
ConfigProto config = new ConfigProto();
config.LogDevicePlacement = true;
config.AllowSoftPlacement = true;
GPUOptions gpuOptions = new GPUOptions();
gpuOptions.AllowGrowth = true;
gpuOptions.PerProcessGpuMemoryFraction = 0.5;
config.DeviceCount.Add("GPU", 1);
config.GpuOptions = gpuOptions;
sessionOptions.SetConfig(config);
_sessionPredict = new Session(_graph, sessionOptions);
```

**Error message**
```
2019-10-28 12:37:34.537578: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2019-10-28 12:37:34.540489: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED
2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node Conv1_1/convConv}}]]
         [[LossScope/outputPrediction/_43]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node Conv1_1/convConv}}]]
0 successful operations.
0 derived errors ignored.
```

**Comment by Oceania2018** [comment]
Have you installed GPU redist from https://www.nuget.org/packages/SciSharp.TensorFlow.Redist-Windows-GPU/ ?

**Comment by captainst** [comment]
What is the tensorflow version you are using? Can you make GPU working with python environment? (if you have installed any).
It seems that you don't have a correct version pair between CUDA/cuDNN and tensorflow.

**Comment by quintakFR** [comment]
Thank @Oceania2018  and @captainst for your answer

@Oceania2018 No I didn't install SciSharp.TensorFlow.Redist-Windows-GPU because of the TensorFlow version but I include dll of TensorFlow 2.0 compile from sources with GPU support

@captainst In fact I use a dll generated from sources of TensorFlow 2.0 with small custom part. The custom method can not be the origin of the issue. I compile TensorFlow 2.0 with CUDA 10.1.243 and cuDNN 7.6.4.38. I used this custom dll to perform the training in C++ so I think it is not the issue

**Comment by captainst** [comment]
I think that the current version of tf.net supports tf 1.14. I am not sure if tensorflow 2.0 works with that.

**Comment by quintakFR** [comment]
@captainst I just used my custom dll of TensorFlow 1.14 and the error is the same... With this version of TF, the learning with my C++ code works perfectly

**Comment by quintakFR** [comment]
If I only use AllowGrowth for GPUOptions, the allocation all of the GPU memory. It is the same if I don't set the GpuOptions parameter of ConfigProto.
Are you sure the parameters of GPUOptions are used to define ConfigProto? I took a look in the source code and I didn't notice issues.

**Comment by Oceania2018** [comment]
@quintakFR Could you raise the issue in [tensorflow](https://github.com/tensorflow/tensorflow) ? It's kind of exceed my knowledge.

**Comment by captainst** [comment]
A way of verification is to try to make the GPU dll work with a python environment. As far as I know, CUDA10.1 might have problems with TF 1.4. My environment is CUDA10.0

**Comment by quintakFR** [comment]
Thank you both, @Oceania2018 and @captainst 
I will try with Python environment and if the issue is still here, I will raise the issue to TensorFlow team.

**Comment by meesoft** [comment]
@quintakFR did you have any luck? I see the samme issue that all GPU memory is allocated even with PerProcessGpuMemoryFraction = 0.5 and then it fails the same way that you report.

**Comment by Oceania2018** [comment]
@quintakFR @meesoft The cuDNN should install v7.4.

**Comment by meesoft** [comment]
Thanks, that was it. I was using cuDNN 7.6 where it failed but it works with cuDNN 7.4.

**Comment by meesoft** [comment]
Small update - according to Windows' Task Manager it sill allocates ~90% of GPU memory no matter what I set PerProcessGpuMemoryFraction to, but it runs without the "Failed to get convolution algorithm" we got before so that is enough for me :)

**Comment by Oceania2018** [comment]
@meesoft Check if this helps you: https://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory

**Comment by meesoft** [comment]
That is exactly what I do, and it is the same as @quintakFR 's code in the first post in this thread. Anyway, it doesn't matter to me that it allocates all memory, the important part is that the convolution woks after downgrading to cuDNN 7.4.

**Comment by quintakFR** [comment]
Thanks @meesoft and @Oceania2018 ! I will use cuDNN 7.4 if I don't find another solution.

**Comment by LittleLittleCloud** [comment]
Write it down for record.


Encounter the same problem. downgrade to cudnn 7.4 solve it.
The version I use is 1.14.1
my GPU is GTX 1660, and cuda version is 10.0
