### ISSUE TITLE
Will tf2.0 be supported in the future?

### ISSUE THREAD

**Issue by msnh2012** [SciSharp/TensorFlow.NET#435]
Thx.

**Comment by Oceania2018** [comment]
Definitely yes. But I havn't a specific timeline.

**Comment by msnh2012** [comment]
@Oceania2018  Can u make a demo for freezing a graph to pb file and reload .

**Comment by msnh2012** [comment]
@Oceania2018 For example: LinearRegression.

**Comment by msnh2012** [comment]
@Thx a lot!

**Comment by msnh2012** [comment]
@Oceania2018  Thx a lot :D

**Comment by Oceania2018** [comment]
There are a lot of examples: https://github.com/SciSharp/TensorFlow.NET-Examples

**Comment by lefig** [comment]
Its a great project. Thank you. Moreover, support for TF 2 would be splendid.

**Comment by hahadashi** [comment]
> There are a lot of examples: https://github.com/SciSharp/TensorFlow.NET-Examples

have you try frozen tf 2.0 ckpt to pb model? hope you give some adivce or demo. thx

**Comment by hahadashi** [comment]
> There are a lot of examples: https://github.com/SciSharp/TensorFlow.NET-Examples

> freeze the graph reference from the below code
> 
> ```python
> from keras import backend as K
> import tensorflow as tf
> 
> def freeze_session(session, keep_var_names=None, output_names=None, clear_devices=True):
>     """
>     Freezes the state of a session into a pruned computation graph.
> 
>     Creates a new computation graph where variable nodes are replaced by
>     constants taking their current value in the session. The new graph will be
>     pruned so subgraphs that are not necessary to compute the requested
>     outputs are removed.
>     @param session The TensorFlow session to be frozen.
>     @param keep_var_names A list of variable names that should not be frozen,
>                           or None to freeze all the variables in the graph.
>     @param output_names Names of the relevant graph outputs.
>     @param clear_devices Remove the device directives from the graph for better portability.
>     @return The frozen graph definition.
>     """
>     from tensorflow.python.framework.graph_util import convert_variables_to_constants
>     graph = session.graph
>     with graph.as_default():
>         freeze_var_names = list(set(v.op.name for v in tf.global_variables()).difference(keep_var_names or []))
>         output_names = output_names or []
>         output_names += [v.op.name for v in tf.global_variables()]
>         # Graph -> GraphDef ProtoBuf
>         input_graph_def = graph.as_graph_def()
>         if clear_devices:
>             for node in input_graph_def.node:
>                 node.device = ""
>         frozen_graph = convert_variables_to_constants(session, input_graph_def,
>                                                       output_names, freeze_var_names)
>         return frozen_graph
> 
> 
> frozen_graph = freeze_session(K.get_session(),
>                               output_names=[out.op.name for out in model.outputs]
> 
> tf.train.write_graph(frozen_graph, "model", "tf_model.pb", as_text=False)
> ```
TF2.0
hi，i use the demo complete frozen the ckpt model(checkpoint = tf.train.Checkpoint(myAwesomeModel=me), checkpoint.restore(tf.train.latest_checkpoint('examples'    ))) or h5 model (model.load_weights('model.h5'))to pb model。after i run ckpt model and pb model，i find their result is different。and the result of ckpt model  is right。i check the pb model parmas， and find some op variable parmas is initial value，like “bias” is vector contain zero，“layer normal beta”  is vector contain zero eg.  i think it is wrong, hope your give me some advice,thx

**Comment by angeliand** [comment]
Hi! 
Any update on the TF 2 timeline? Should we expect it in the near future?

**Comment by erichiller** [comment]
For anyone following, I think this should be closed now, [0.20.0-preview2](https://www.nuget.org/packages/TensorFlow.NET/0.20.0-preview2) is out and:
> tf.net 0.20.x and above are based on tensorflow native 2.x.
Eager Mode is added finally.
It's not stable at this moment and missing many APIs, tf.net 0.15.x is more stable for production.
Please be patient, we're working hard on missing functions, providing full tensorflow binding is our mission.
