### ISSUE TITLE
TF.NET can't run at net472,it always throw exception about TargetInvocationException!

### ISSUE THREAD

**Issue by guangweifan** [SciSharp/TensorFlow.NET#436]
Software Environment List:
 NO1:VS 2019 For Mac
 NO2:TargetFrameWork   .net framework 4.7.2

**Comment by Oceania2018** [comment]
Have you tried x64 configuration?

**Comment by guangweifan** [comment]
在mac pro平台下无论是anycpu还是X64的都不行，但是在windows平台下使用.net framework必须更改成x64才可以。以下为环境配置及出错信息：
<img width="889" alt="截屏2019-10-31下午7 11 06" src="https://user-images.githubusercontent.com/25050623/67942376-a935d880-fc12-11e9-9e1c-8cbf252e39c4.png">
<img width="962" alt="截屏2019-10-31下午7 07 03" src="https://user-images.githubusercontent.com/25050623/67942377-a9ce6f00-fc12-11e9-9cbb-87365814b5b9.png">
<img width="959" alt="截屏2019-10-31下午7 07 25" src="https://user-images.githubusercontent.com/25050623/67942379-a9ce6f00-fc12-11e9-9844-752d0f9ac3e7.png">
<img width="957" alt="截屏2019-10-31下午7 09 41" src="https://user-images.githubusercontent.com/25050623/67942380-a9ce6f00-fc12-11e9-8a5c-33e82aaf9ffd.png">
