### ISSUE TITLE
tensorflow-gpu redist package for 1.15

### ISSUE THREAD

**Issue by Nucs** [SciSharp/TensorFlow.NET#437]
There is no version 1.15 in nuget package [SciSharp.TensorFlow.Redist-Windows-GPU](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist-Windows-GPU/).

**Comment by alfarok** [comment]
It appears this has been resolved as of 8 days ago:
[SciSharp.TensorFlow.Redist-Windows-GPU/1.15.1](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist-Windows-GPU/1.15.1)
