### ISSUE TITLE
Integrate with ml-agents

### ISSUE THREAD

**Issue by Deep-Blue-2013** [SciSharp/TensorFlow.NET#438]
If tf.net can be connected to this, it should be a lot easier. py often encounters some incompatibility problems, it is not easy to debug.

Unity Machine Learning Agents Toolkit
https://github.com/Unity-Technologies/ml-agents

**Comment by jorezy** [comment]
Well, if Tensorflow.NET can support two deep reinforcement learning algorithms like Proximal Policy Optimization (PPO) and Soft Actor-Critic (SAC), I think Unity 3D developers will not have to rely on their ml-agent, they can create their own AI agent in .NET with the support of TF.NET.

**Comment by GeorgeS2019** [comment]
FYI Godot - the most active community 3D Engine for C# and UWP and AR needs [support to integrate TensorFlow.NET](https://github.com/godot-extended-libraries/godot-tensorflow-workspace/issues)

**Comment by Oceania2018** [comment]
Take a look at [TF-Agents](https://github.com/tensorflow/agents). A library for Reinforcement Learning in TensorFlow.

@Nucs What's the difference between `OpenAI/Gym` and `TF-Agents` ?

**Comment by Nucs** [comment]
`OpenAI/Gym` provides a set of standard environments to run RL algorithms against.
`TF-Agents` uses `OpenAI/Gym` and other environment providers and provides its own algorithms and architecture for RL.

**Comment by Oceania2018** [comment]
@GeorgeS2019 There is a PPO model implemented in TF.NET https://github.com/Oceania2018/unity-ml-agents.net.
