### ISSUE TITLE
Tensor is not element of this graph after 3 or 7 loops

### ISSUE THREAD

**Issue by sammuttaja** [SciSharp/TensorFlow.NET#440]
I am trying to make Qtable for sc2 using tensorflow.net, but currently when i'm running my model, the graph in sessions is suddenly initialized to new graph that does not contain my model. https://github.com/sammuttaja/Starcraft2_c-_Bot/blob/TensorflowNet/QLearning.cs contains current version of model and i am still learning tensorflow, so if there is some obvious problem, let me know.

**Comment by Oceania2018** [comment]
@sammuttaja How can I reproduce it?
I can't find `ExecuteInfo.txt`.

**Comment by Nucs** [comment]
@sammuttaja Hey, it is likely has to do with multithreading.
I think that you call TF.NET code from different threads which can lead to problems.
Please dive into [wiki/Multithreading](https://github.com/SciSharp/TensorFlow.NET/wiki/Multithreading).
