### ISSUE TITLE
Missing tf.scan

### ISSUE THREAD

**Issue by BrendanMulcahy** [SciSharp/TensorFlow.NET#444]
tf.scan is missing and there seems to be no other workaround for accessing this operation.
https://www.tensorflow.org/versions/r1.14/api_docs/python/tf/scan

Many RNNs use this api apparently.  I could try adding it but I'm not too confident on how to do that yet.

**Comment by BrendanMulcahy** [comment]
I almost have this working on my fork, with a few obvious problems I could use help with.
https://github.com/BrendanMulcahy/TensorFlow.NET/commit/79da38ae1c6e863d48cbe68e5433ac8d4743668b

1. control_flow_ops.while_loop - compute function in python seems more "flexible".  It is able to take more arguments and still work.  I might be able to figure this out but could use help since I'm not sure how the original types were chosen
1. Not sure on when to use tf.constant vs tf.convert_to_tensor (or something else entirely lol).  Some of the ops take in ints directly in python but we have Tensor as the type in the method signature in tf.net so need to put the int into a tensor somehow?
1. Some of the original code is checking for eager mode via "variablescope.caching_device" but this doesn't exist currently. So for now Im just assuming graph_mode = true.

There are probably a myriad of other issues, but these are the few I immediately have questions about.

**Comment by BrendanMulcahy** [comment]
Also, what's the correct way to translate array indexer like [1:] in python to C# in tf.net?

**Comment by Oceania2018** [comment]
Before you PR, you can run all the unit test and tf.net examples project. If you can pass them all and your own project. It will be good to PR.

You can use tensor[“1:”] or ndarray[“1:”] for slice.

**Comment by BrendanMulcahy** [comment]
Ok, the tests seem easy to run, so I will keep plugging along even if I need to expand while_loop a bit.

**Comment by Oceania2018** [comment]
That’s cool, tf.scan looks no effect with other functions.
