### ISSUE TITLE
Cannot find Tflearn implementation 

### ISSUE THREAD

**Issue by JojoDuke** [SciSharp/TensorFlow.NET#451]
I would like to use tflearn in my project but couldn't find anything like a tflearn implementation for this package? Is there any at all? If not what can I do?

**Comment by Nucs** [comment]
[tflearn](https://github.com/tflearn/tflearn) is an independent and separate library from tensorflow therefore we do not have support for it in Tensorflow.NET.

**Comment by JojoDuke** [comment]
> [tflearn](https://github.com/tflearn/tflearn) is an independent and separate library from tensorflow therefore we do not have support for it in Tensorflow.NET.

Then is there any workaround to it?

**Comment by Nucs** [comment]
AFAIK there is no implementation in C# for tflearn . So you can't replicate tflearn to C#.

**Comment by Oceania2018** [comment]
@JojoDuke @Nucs I'm also interested in making a TFLearn for .NET. If more developers can participate in this project, we could make it real.

**Comment by JojoDuke** [comment]
@Oceania2018 That would be amazing. How would you plan on doing this?
Either way, I believe you could find a lot of interested people on Reddit and other social platforms

**Comment by Oceania2018** [comment]
@JojoDuke Do you know the main difference between `tflearn` and `tf.keras` ?

**Comment by JojoDuke** [comment]
@Oceania2018 No I do not, this is my first time of hearing tf.keras even

**Comment by Oceania2018** [comment]
Tflearn seems not update long time ago.

**Comment by Oceania2018** [comment]
We’re prefer to implement tf.keras rather than tflearn.
