### ISSUE TITLE
Error in object detection example

### ISSUE THREAD

**Issue by masoudnick** [SciSharp/TensorFlow.NET#454]
Hi all,
I want to run [Object Detection](https://github.com/SciSharp/TensorFlow.NET-Examples/blob/master/src/TensorFlowNET.Examples/ImageProcessing/ObjectDetection.cs) example. But i have three errors that illustrated in the bottom photo.
What should I do?
![adnlasdasd](https://user-images.githubusercontent.com/20556982/69902875-b0820a80-13a7-11ea-8dd0-d6f0a7cc5f30.png)

**Comment by Oceania2018** [comment]
@masoudnick Are you using NumSharp 0.20 ?

**Comment by masoudnick** [comment]
@Oceania2018 I installed version 0.20.4

**Comment by Oceania2018** [comment]
Are you using the C# 7.x ? or .NET Core ?

**Comment by masoudnick** [comment]
@Oceania2018 Does it different? I'm using Visual Studio 2015.

**Comment by Oceania2018** [comment]
I'm not sure, you'd better use Visual Studio 2017 +. The error look like the C# compiler is imcompatible.

**Comment by masoudnick** [comment]
@Oceania2018 
Thanks for your response :)
I'll install Visual Studio 2017 and test this example again.
