### ISSUE TITLE
Sqrt automatic differentiation

### ISSUE THREAD

**Issue by mishun** [SciSharp/TensorFlow.NET#461]
Hi!

Running following code:
```F#
[<EntryPoint>]
let main argv =
    let tf = Tensorflow.Binding.tf

    let x = tf.constant (1.0)
    let y = tf.sqrt x
    let g = tf.gradients (y, x)

    use s = tf.Session ()
    let result = s.run (g)
    printf "result = %A" result

    0
```
always yields:
```
Unhandled exception. Tensorflow.LookupError: No gradient defined for operation 'Sqrt' (op type: Sqrt)
```
Analogous python code yields expected result (0.5). If tf.sqrt is replaced with tf.square, for example, code above yields expected result (2.0). Similar issue seems to also be present at least for tf.sin and tf.cos.

Was tested with following fsproj file:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TensorFlow.NET" Version="0.13.0" />
    <PackageReference Include="SciSharp.TensorFlow.Redist" Version="1.15.0" />
  </ItemGroup>

</Project>
```

**Comment by mishun** [comment]
Stupid question: why is there math_ops.conj in almost every derivative specified in math_grad.cs file?

**Comment by Oceania2018** [comment]
It would help if you can PR an UnitTest in C#.

**Comment by mishun** [comment]
I've also found a bug in tf.minimum derivative. That commit seems to fix it:
https://github.com/mishun/TensorFlow.NET/commit/807334e51cb480ff63a50d8a6464e65933785a37
but I'm not sure about math_ops.conj thing.
I'll add tests when I figure how to run them :)

**Comment by Oceania2018** [comment]
@mishun What do you mean `math_ops.conj` ? Do we have this file?

**Comment by mishun** [comment]
I mean if we look at gradient function for Exp (file src/TensorFlow.NET.Core/Gradients/math_grad.cs), for example:
```C#
        [RegisterGradient("Exp")]
        public static Tensor[] _ExpGrad(Operation op, Tensor[] grads)
        {
            var grad = grads[0];
            var y = op.outputs[0];  // y = e^x
            return tf_with(ops.control_dependencies(new Operation[] { grad }), dp => {
                y = math_ops.conj(y);
                return new Tensor[] { math_ops.mul_no_nan(y, grad) };
            });
        }
```
there's that call "y = math_ops.conj(y);" (and similar calls are present in almost every gradient function there). If I remember correctly, reverse differentiation pass should just multiply gradient by derivative of current node, so I don't understand where that complex conjugation comes from. Is complex conjugation of gradient is actually backpropagated instead of just gradient for some external reason?

**Comment by mishun** [comment]
I've created PR with both fixes and tests:  #467

**Comment by mishun** [comment]
Well, it looks like math_ops.conj actually does nothing (even for complex tensors):
https://github.com/SciSharp/TensorFlow.NET/blob/788cd5c20ce1be4064e205425f07bb3e655d6bb7/src/TensorFlowNET.Core/Operations/math_ops.cs#L668-L679

Also, differentiating complex tensors currently is pretty non-trivial matter:
https://github.com/SciSharp/TensorFlow.NET/blob/788cd5c20ce1be4064e205425f07bb3e655d6bb7/src/TensorFlowNET.Core/Gradients/gradients_util.cs#L261-L277
It deliberately throws an exception when encountering complex tensor in case no grad_ys is specified, and if user is to specify grad_ys explicitly then it just fails later because that "if" statement lacks "else" block.

**Comment by mishun** [comment]
From what I can see, complex conjugation is just how original python tensorflow library defines gradients of complex functions. Seems a bit ugly, but this library is expected to emulate tensorflow and those `math_ops.conj`-s should be there. I thinks this issue can be closed.
