### ISSUE TITLE
In importer.py.cs, method _PopulateTFImportGraphDefOptions is not implemented.

### ISSUE THREAD

**Issue by xuwaters** [SciSharp/TensorFlow.NET#462]
I would like to load a `.pb` file, and when I call
```cs
importer.import_graph_def(frozen_graph_def, return_elements: return_elements);
```
A `NotImplementedException` throws:
```cs
Unhandled exception. System.NotImplementedException: _PopulateTFImportGraphDefOptions
   at Tensorflow.importer._PopulateTFImportGraphDefOptions(ImportGraphDefOptions options, String prefix, Dictionary`2 input_map, String[] return_elements) in /TensorFlow.NET/src/TensorFlowNET.Core/Framework/importer.py.cs:line 101
   at Tensorflow.importer.import_graph_def(GraphDef graph_def, Dictionary`2 input_map, String[] return_elements, String name, OpList producer_op_list) in /TensorFlow.NET/src/TensorFlowNET.Core/Framework/importer.py.cs:line 62
```

**Comment by Oceania2018** [comment]
How can I reproduce it? Is there download link for pb file?

**Comment by ChrisUnityArto** [comment]
Hi! Is there any planned timeframe for finishing the functionality in this class? I am migrating from tensorflowsharp but I require the method `_PopulateTFImportGraphDefOptions` to run as it does in the older lib. However it looks like the input mapping functionality is missing as yet, with a `NotImplementedException: _PopulateTFImportGraphDefOptions` error from here :
 https://github.com/SciSharp/TensorFlow.NET/blob/master/src/TensorFlowNET.Core/Framework/importer.cs#L124 

There are also a few other places in that class which throw a `NotImplementedException`

**Comment by ChrisUnityArto** [comment]
If this is not planned, then could you give me any suggestions on the approach I could take to work around it and add input mappings in a different way?

**Comment by ChrisUnityArto** [comment]
I have made a PR to add the input mapping functionality - please have a look at this and let me know if this will not work, I think this change would be sufficient for my needs ; https://github.com/SciSharp/TensorFlow.NET/pull/623

**Comment by ChrisUnityArto** [comment]
Thanks @Esther2013, that was a very quick merge! Could I trouble you to ask if you have any idea when is the timeframe for the next nuget package release?

**Comment by Esther2013** [comment]
@ChrisUnityArto Normally speaking, it's released once a month. So for next release `v0.21` should be `Oct. 17th 2020`.
