### ISSUE TITLE
Calling RegisterGradientFunction too early results in no other gradients being registered

### ISSUE THREAD

**Issue by dsyme** [SciSharp/TensorFlow.NET#464]
If you call `RegisterGradientFunction` before any initialization has happened in TF.NET then the gradient registrations are not scraped from existing assemblies.

The relevant code is here - the initialization of the gradients table should be forced by RegisterGradientFunction too

https://github.com/SciSharp/TensorFlow.NET/blob/75ae2e9e09d74683955478f0a6fe41eb8593a155/src/TensorFlowNET.Core/Gradients/ops.gradient_function_mapping.cs#L56

**Comment by Oceania2018** [comment]
@dsyme It's already there: https://github.com/SciSharp/TensorFlow.NET/blob/75ae2e9e09d74683955478f0a6fe41eb8593a155/src/TensorFlowNET.Core/Gradients/ops.gradient_function_mapping.cs#L36

**Comment by dsyme** [comment]
Yes but if that line gets executed first then this code doesn't get run :) https://github.com/SciSharp/TensorFlow.NET/blob/75ae2e9e09d74683955478f0a6fe41eb8593a155/src/TensorFlowNET.Core/Gradients/ops.gradient_function_mapping.cs#L58

**Comment by Oceania2018** [comment]
Oh, right. Seems like a serious bug there. Will fix it at weekend.

**Comment by dsyme** [comment]
Thanks!
