### ISSUE TITLE
can't find "tf.nn.ctc_greedy_decoder" function

### ISSUE THREAD

**Issue by geminird** [SciSharp/TensorFlow.NET#473]
Hello, In my project， need use the ”tf.nn.ctc_greedy_decoder” and "tf.sparse_tensor_to_dense" functions , how  to do in tensorflow.net api.

and can I use the "Tensorflow.Operations.rnn.static_bidirectional_rnn" funciton instead of "tf.nn.bidirectional_dynamic_rnn" function? 

use "tf.variance_scaling_initializer()" instead of "tf.contrib.layers.variance_scaling_initializer()"?

**Comment by Oceania2018** [comment]
1. Is your project open source? If not, please contact scisharpstack@gmail.com for support.
2. I'm not sure, please refer tensorflow's manual.
3.  They are aliases and produce the same result. You can use `tf.variance_scaling_initializer()`. Please refer to this issue SciSharp/TensorFlow.NET#356.

**Comment by geminird** [comment]
@Oceania2018 open soruce python project at here [url:https://github.com/jinxiwang/ocr_TDR](url)，I'm try to use tensorflow.net implemet it. the method url at here [url:https://github.com/jinxiwang/ocr_TDR/blob/master/test_crnn.py](url), line :32，another method [url:https://github.com/jinxiwang/ocr_TDR/blob/master/crnn.py](url) line 46,57,112。

**Comment by Oceania2018** [comment]
@geminird I'm saying where is your .net version is? We'd like to help if your .net version is also open source.

**Comment by geminird** [comment]
@Oceania2018 The. Net version is just beginning. Because I just started to learn tensorflow, as a learning tool, I can't rewrite several problems, so I came to help. After the later program is sure to run, I will open it up on GitHub.

**Comment by geminird** [comment]
@Oceania2018 I pull it, see here :[https://github.com/geminird/TfConsoleApp](url)

**Comment by geminird** [comment]
@Oceania2018 网络不太好，没看到您的头像，您应该也是华人吧。这个是当作学习示例，目前改写了预测代码，程序跑不通。主要在CRNN类的74行，是参照BUG[404](https://github.com/SciSharp/TensorFlow.NET/issues/404)修改的，但是还是不行，也把redis版本升级到1.15.0了，照样运行不了，不知道怎么解决，估计是那些匹配不到的函数替换错了。

**Comment by Oceania2018** [comment]
@geminird I've raised issue on your repo: https://github.com/geminird/TfConsoleApp/issues/1
