### ISSUE TITLE
Can not found GPU

### ISSUE THREAD

**Issue by Lywzz** [SciSharp/TensorFlow.NET#474]
I have installed Microsoft.ML.TensorFlow.Redist and SciSharp.TensorFlow.Redist-Windows-GPU on windows 10,but it could not found device
2019-12-17 17:53:36.953709: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Device mapping: no known devices.
2019-12-17 17:53:37.858721: I tensorflow/core/common_runtime/direct_session.cc:317] Device mapping:
How can i use it

**Comment by Nucs** [comment]
Hey @Lywzz,
A. You need to have only one package,
I think `Microsoft.ML.TensorFlow.Redist` is a CPU version so uninstall it, keep `SciSharp.TensorFlow.Redist-Windows-GPU` installed and rebuild the project.
B. Make sure the project is targeting x64.
C. You have all the requirements of tensorflow-gpu [here](https://www.tensorflow.org/install/gpu).
1. [CUDA 10.0](https://developer.nvidia.com/cuda-10.0-download-archive) (exactly version 10.0) installed and have the following environment variables set (the directory may vary, verify it exists)
    ```bash
    CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
    CUDA_PATH_V10_0=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
    ```
2. [cuDNN SDK](https://developer.nvidia.com/cudnn) installed.
Extract the zip to `C:\cudann` and set up the environment variable for in PATH:
    ```bash
    Add to PATH
    C:\cudann
    C:\cudann\bin
    ```
3. Make sure your NVIDIA GPU driver version is >=410.x

If you've done all the above correctly, the library should automatically switch to GPU.

**Comment by Lywzz** [comment]
Thank you ,it works
