### ISSUE TITLE
Passing input from GPU

### ISSUE THREAD

**Issue by solarflarefx** [SciSharp/TensorFlow.NET#476]
I am working in a pipeline architecture where all intermediary data resides in the GPU.  I am interested in passing data already in the GPU into a DL network with the output still residing in the GPU to be passed to the next element in a pipeline.  Essentially I would like to pass a cuda array into the network, get an output and convert back into a cuda array.  I’d like to do this without having to perform CPU/GPU copies.  Is this possible at the moment?

**Comment by Oceania2018** [comment]
@solarflarefx If you want to avoid copying data bewteen CPU/GPU, you should do the work in one TensorFlow Graph.

**Comment by solarflarefx** [comment]
@Oceania2018 So I want to be clear that in my current pipeline architecture I am already working with cuda arrays to do other types of processing in the GPU.  I essentially want to take the output of one element in the pipeline and feed it into the model.  I created a .pb file that I load in TensorFlow.NET, but ultimately I have to convert the cuda type into something that the model will take.  Is there a way to do this while keeping all elements in the GPU?

**Comment by solarflarefx** [comment]
So I take it that this is probably not possible with this binding?

**Comment by Oceania2018** [comment]
No, I don't know how to do it neither.
