### ISSUE TITLE
Find bottlenecks in object detection program

### ISSUE THREAD

**Issue by masoudnick** [SciSharp/TensorFlow.NET#477]
Hi @Nucs
I wrote an object detection program.But my program implementation process is very slow.I used dotTrace to finding bottlenecks and i got a performance snapshot.
Can you help me to solve this problem?

my code : 
[Object Detection.txt](https://github.com/SciSharp/NumSharp/files/4002430/Object.Detection.txt)

Snapshot : 
![dotTrace](https://user-images.githubusercontent.com/20556982/71474995-7ca5d380-27f3-11ea-8037-8a60f8a74e0f.JPG)

**Comment by Oceania2018** [comment]
12 seconds? It’s impossible. Where is the pb file?

**Comment by masoudnick** [comment]
@Oceania2018 
In this path :
`bin\x64\Debug`

**Comment by Oceania2018** [comment]
I mean where can I download the on file?

**Comment by Nucs** [comment]
Hi @masoudnick, greeting from Israel
Based on your snapshot screenshot, It seems that the bottleneck is tensorflow computing your model.
So in other words, it has nothing to do with NumSharp or TF.NET but with your model and your cpu/gpu.

**Comment by masoudnick** [comment]
Hi @Nucs
ברכות מאיראן
I thought that my problem was related to TF.NET because i trained my model by ssdlite_mobilenet_v2_coco and detection speed of this model in python programs(on cpu) is very fast.
Anyway thanks for your response.If you have any other comment please let me know.

**Comment by masoudnick** [comment]
@Oceania2018 
If possible, give me your email and i will share with you .pb file.

**Comment by Oceania2018** [comment]
Can you email to scisharpstack@gmail.com?

**Comment by masoudnick** [comment]
@Oceania2018 Yeah, i emailed.

**Comment by Oceania2018** [comment]
@masoudnick I ran your example. No performance issue found.

![image](https://user-images.githubusercontent.com/1705364/71496872-25b3f480-281b-11ea-9a10-94469d08dbdc.png)

```csharp
using NumSharp;
using System;
using Tensorflow;
using static Tensorflow.Binding;
using SharpCV;
using static SharpCV.Binding;

namespace TensorFlowNET.Examples
{
    public class Test
    {
        Tensor image_tensor, boxes, scores, classes, num_detections;
        Tensor[] outTensorArr;

        public bool Run()
        {
            var graph = ImportGraph("ssdlite_Hybridnet_V100.10.pb");
            var mat = cv2.imread("shasta-daisy.jpg");
            Run(mat, graph);
            return true;
        }

        public void Run(Mat frame, Graph graph)
        {
            NDArray image_np = frame;
            image_np = image_np.reshape(1, frame.shape[1], frame.shape[0], 3);
            image_tensor = graph.OperationByName("image_tensor");
            boxes = graph.OperationByName("detection_boxes");
            scores = graph.OperationByName("detection_scores");
            classes = graph.OperationByName("detection_classes");
            num_detections = graph.OperationByName("num_detections");
            outTensorArr = new Tensor[] { num_detections, boxes, scores, classes };

            using (var sess = tf.Session(graph))
            {
                var results = sess.run(outTensorArr, new FeedItem(image_tensor, image_np));
                buildOutputImage(results, frame);
            }
        }

        public Graph ImportGraph(string path)
        {
            Graph graph = new Graph().as_default();
            graph = tf.get_default_graph();
            graph.Import(path);
            Console.WriteLine("Model Loaded.");
            return graph;
        }

        private void buildOutputImage(NDArray[] resultArr, Mat frame)
        {
            var scores = resultArr[2].AsIterator<float>();
            var boxes = resultArr[1].GetData<float>();
            var id = np.squeeze(resultArr[3]).GetData<float>();
            for (int i = 0; i < scores.size; i++)
            {
                float score = scores.MoveNext();
                if (score > 0.7f)
                {
                    float top = boxes[i * 4] * frame.shape[0]; ;
                    float left = boxes[i * 4 + 1] * frame.shape[1];
                    float bottom = boxes[i * 4 + 2] * frame.shape[0];
                    float right = boxes[i * 4 + 3] * frame.shape[1];
                    Console.WriteLine("top: " + top.ToString() + " left: " + left.ToString() + " bottom: " + bottom.ToString() + " right: " + right.ToString());
                    //var plate = np.array(frame[top: left, bottom: right]);
                }
            }

        }
    }
}

```

**Comment by masoudnick** [comment]
@Oceania2018 
Thanks for devoting your time, But the problem I had was related to running the model on frames of a video.The program works very slowly by giving the frames to the model as sequentially.How to solve this problem?

**Comment by Oceania2018** [comment]
Can you show me the video capture code?

**Comment by masoudnick** [comment]
@Oceania2018 
I uploaded a video as an example on google drive.You can download it from bottom link :
[https://drive.google.com/file/d/1F7fWxf7fIkk4kAP_5WWC4Katl2qqpx0s/view?usp=sharing](url)

**Comment by Oceania2018** [comment]
@masoudnick OK, I'll test it. BTW, are you using GPU version? As my experience, object detection should use GPU for better performance, otherwise it will cost about 500ms per frame to process.

And I changed your code using [SharpCV](https://github.com/Oceania2018/SharpCV) to work with NDArray better.

**Comment by Oceania2018** [comment]
@masoudnick It's normal, costs 13s total for 261 frames in the video for CPU version.

![image](https://user-images.githubusercontent.com/1705364/71536530-0ded7680-28d6-11ea-82e2-dd751cfaf77d.png)

60ms per frame, actually it's pretty good.

![image](https://user-images.githubusercontent.com/1705364/71536544-2e1d3580-28d6-11ea-829c-106069a7f55a.png)
