### ISSUE TITLE
Unable to get Tensofflow.NET working:  Source, Nuget, and  Docker Image

### ISSUE THREAD

**Issue by Lithonite** [SciSharp/TensorFlow.NET#478]
Hello, My team and I am clearly still missing something but I've personally spent a day on trying to get these libraries working and no luck. Any assistance getting past this would greatly be appreciated.  At the moment I just trying to get team started using the stack and failing miserably; Given we cant even get "Hello World" executing. 

We have already gone in and set build platform targets to x64 as issue https://github.com/SciSharp/TensorFlow.NET/issues/252 suggests. Unfortunately this has not resolved the issue. We still are met with unable to find dll for UnitTests. 

From source( using stated build platform target ) unit tests fail:
![image](https://user-images.githubusercontent.com/40280243/71523142-86274e00-287c-11ea-815a-3f5b4db581ba.png)

When I tried a simple console app (.NET Core 3.1 using latest NuGet Packages):
![image](https://user-images.githubusercontent.com/40280243/71523265-1e253780-287d-11ea-83e3-9736caa546f9.png)

Existing Examples (.NET Core 3.1 using latest NuGet Packages)
![image](https://user-images.githubusercontent.com/40280243/71523677-de5f4f80-287e-11ea-8d3a-aa2032cd9a92.png)

When debugging while referencing to local build of assembly Both of those fault immediately when attempting to create a new instance of tensorflow object. 

Docker Latest ScSharpCube(.NET Core 2.2):
![image](https://user-images.githubusercontent.com/40280243/71523389-a7d50500-287d-11ea-9325-2e753f598a10.png)

If there is additional supporting documentation needed to determine cause let me know.  Ill post it straight away.

**Comment by Oceania2018** [comment]
@Lithonite Can you setup a TeamViewer to allow remote control? I might connect to help.

**Comment by Lithonite** [comment]
Sure I up for using team viewer to address the issue. By chance do you have Teams or some other means to screen share?

**Comment by Lithonite** [comment]
This is a result of the compiled instructions not being supported on this series following series of processors. 

http://www.cpu-world.com/Sockets/Socket%201366%20(LGA1366).html

If you are running into this issue. Time to upgrade your machine(s).

**Comment by Oceania2018** [comment]
Related to https://github.com/SciSharp/TensorFlow.NET/issues/340
