### ISSUE TITLE
jpeg_encode does not produce a valid jpeg

### ISSUE THREAD

**Issue by moloneymb** [SciSharp/TensorFlow.NET#479]
The Tensorflow->NumSharp where jpeg_encode returns a NDArray<char>. I think there is an issue where Char is uint16 but the 'string' is a ByteString so should be uint8. The dtypesize is 1. Jpegs should start with 255uy; 216uy; whereas the output is 253uy; 253uy. If I go to the Storage and access the bytes directly they start with 253uy; 255uy. I'll examine this more tomorrow to see if isolate the location of this bug.

**Comment by Oceania2018** [comment]
Yes, for C# `char` is encoded as `Unicode` in UTF-16, for other language, it's UTF-8. That causes problem.

**Comment by moloneymb** [comment]
https://github.com/SciSharp/TensorFlow.NET/pull/480 should fix it

**Comment by Oceania2018** [comment]
UnitTest failed.

**Comment by moloneymb** [comment]
I was using the GitHub edit feature, 
The Unit Tests can be fixed by replacing. 

`var result = (string) c.eval(sess);`

with

`var result = System.Text.UTF8Encoding.UTF8.GetString((byte[]) c.eval(sess));`

I wanted to check to see if you had any push-back on this change? If not I can go ahead and add it.

**Comment by Oceania2018** [comment]
@moloneymb Can you push the new change?

**Comment by Nucs** [comment]
@Oceania2018 I think that this might mess with ML.NET code

**Comment by moloneymb** [comment]
ML.Net seems to go directly to the C API for many functions such as EncodeByteAsString. I had a good look for where it might break and couldn't find any. It would be weird if they were depending on current functionality as bytes are escaped into utf16. I'll update the unit tests to match and re-submit the pull request.
