### ISSUE TITLE
tf.layers.dense does not pass through name to the Keras Layer

### ISSUE THREAD

**Issue by moloneymb** [SciSharp/TensorFlow.NET#484]
This is needed so that dense layers can be specifically named so that the dense layer variable scope names line up with the pre-trained models.

https://github.com/tensorflow/tensorflow/blob/590d6eef7e91a6a7392c8ffffb7b58f2e0c8bc6b/tensorflow/python/layers/core.py#L185

I don't see the mechanism to do this in the TF.Net keras layer so for now I'll just make my own little dense layer. This is just a heads up that w/o fixing this it may be hard to load some pre-trained models.

**Comment by Oceania2018** [comment]
@moloneymb Do you have any Unit Test so that I can reproduce the problem?

**Comment by moloneymb** [comment]
I can make a unit test tomorrow.

**Comment by moloneymb** [comment]
I'm tired atm and I keep screwing up the pull request. But the following unit test will surface the bug.

```
namespace TensorFlowNET.UnitTest.layers_test
{
    [TestClass]
    public class dense
    {
        [TestMethod]
        public void Case1()
        {
            var sess = tf.Session().as_default();
            var x = tf.ones(new TensorShape(10, 10));
            var y = tf.layers.dense(x, 20, name: "test");
            Assert.AreEqual("test/BiasAdd:0", y.name); // test name_scope
            Assert.AreEqual("test/bias", y.op.inputs[1].op.inputs[0]); // test variable_scope
        }
    }
}
```
