### ISSUE TITLE
System.Runtime.InteropServices.SEHException : External component has thrown an exception

### ISSUE THREAD

**Issue by frank-dong-ms** [SciSharp/TensorFlow.NET#485]
Hi there, our team (ML.NET) is using tensorflow.NET and we are seeing below exception in some cases which is rare case and not easy to reproduce in local env:

Error Message:
   System.Runtime.InteropServices.SEHException : External component has thrown an exception.
  Stack Trace:
     at Tensorflow.c_api.TF_SessionRun(IntPtr session, TF_Buffer* run_options, TF_Output[] inputs, IntPtr[] input_values, Int32 ninputs, TF_Output[] outputs, IntPtr[] output_values, Int32 noutputs, IntPtr[] target_opers, Int32 ntargets, IntPtr run_metadata, IntPtr status)
    at Microsoft.ML.TensorFlow.TensorFlowUtils.Runner.Run() in D:\a\1\s\src\Microsoft.ML.TensorFlow\TensorflowUtils.cs:line 491
   at ...

Code:
 https://github.com/frank-dong-ms/machinelearning/blob/dd0faef7c6fd12b498ef9fb15ec8378650bc551b/src/Microsoft.ML.TensorFlow/TensorflowUtils.cs#L491 

I'm wondering is there a way to get exception details like error message and call stack so we can investigate further?

**Comment by Oceania2018** [comment]
I can’t tell from the limited information. It has nothing to do with TF.NET, because you use your own runner that is calling c_api directly. Unfortunately, it will hard to debug.

**Comment by frank-dong-ms** [comment]
Yes, we are using c_api directly, is there any way to catch detailed exception?

**Comment by Oceania2018** [comment]
You can check the _status first.

**Comment by frank-dong-ms** [comment]
Thanks, let me have a try

**Comment by Nucs** [comment]
Seems to be an exception thrown from C++, likely to be TF's.
Aside from checking the TF.NET's `Tensorflow.Status` for more details (from props: `status.Message` and `Message.Code`).
`System.Runtime.InteropServices.SEHException` has an `ErrorCode` property, its value might give some insights.
