### ISSUE TITLE
where is `Python` `with` and other operations?

### ISSUE THREAD

**Issue by yedajiang44** [SciSharp/TensorFlow.NET#491]
[https://tensorflownet.readthedocs.io/en/latest/Placeholder.html](url)

the code 
```c# 
var x = tf.placeholder(tf.int32);
var y = x * 3;

Python.with<Session>(tf.Session(), sess =>
{
    var result = sess.run(y, feed_dict: new FeedItem[]
    {
        new FeedItem(x, 2)
    });
    // (int)result should be 6;
});
```
I can not find `Pyrhon.with`

[https://tensorflownet.readthedocs.io/en/latest/Graph.html](url)
```c#
with<Graph>(tf.Graph().as_default(), graph =>
{
	var variable = tf.Variable(31, name: "tree");
	tf.global_variables_initializer();
	variable.assign(12);
});
```
I can not find `with`

**Comment by Oceania2018** [comment]
@yedajiang44 `Python.with` is obseleted, please use `tf.with`. Actually you can use 
```csharp
using(var sess = tf.Sesssion())
{
}
```
More examples are [here](https://github.com/SciSharp/SciSharp-Stack-Examples).
Welcome if you can PR a revisied doc.

**Comment by yedajiang44** [comment]
thanks
