### ISSUE TITLE
nested graph

### ISSUE THREAD

**Issue by Mghobadid** [SciSharp/TensorFlow.NET#497]
hi, when i want run nested graph i faced with this error 

> Current graph is not default graph. Default Graph Key: grap-key-2/, Current Graph Key: grap-key-1/

this is my code summary : 

` public main( ) {
  
		ocr_graph=Ocr_Graph();
		plate_graph=Plate_Graph();
			
		using ( var sess=tf.session(plate_graph){
		
			image_tensor = plate_graph.OperationByName("image_tensor");
            boxes = plate_graph.OperationByName("detection_boxes");
            scores = plate_graph.OperationByName("detection_scores");
            classes = plate_graph.OperationByName("detection_classes");
            num_detections = plate_graph.OperationByName("num_detections");
			outTensorArr = new Tensor[] { num_detections, boxes, scores, classes };
            
            var results = sess.run(outTensorArr, new FeedItem(image_tensor, frame));
			
			if(condtion...){
			
					///other code
					String character = Ocr(char_image,ocr_graph); // in ocr class i run session 
				
			}
			
		}
  
  }
  

	public Graph Plate_Graph()
        {

            Graph graph = new Graph();
          
            graph.Import("plate_detection.pb");
             
			
			return graph;

        }
	public Graph Ocr_Graph()
        {

            Graph graph = new Graph();
			
            graph.Import("ocr.pb");
        
             
           return graph;

        }
`

**Comment by Oceania2018** [comment]
You can switch graph back and forth before `session.run`.
