### ISSUE TITLE
DllNotFoundException: tensorflow

### ISSUE THREAD

**Issue by MakwanaVihas** [SciSharp/TensorFlow.NET#501]
System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Activator.CreateInstance[T] () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
Tensorflow.Binding.New[T] () (at <8a1f7e7c69e4475d81bee40566e03f7b>:0)
Tensorflow.Binding..cctor () (at <8a1f7e7c69e4475d81bee40566e03f7b>:0)
Rethrow as TypeInitializationException: The type initializer for 'Tensorflow.Binding' threw an exception.

This happened while running in VSCode on Mac:
     **using Tensorflow;
        using static Tensorflow.Binding;**
    **while running** ->> tf.convert_to_tensor(0).ToString()

**Comment by Oceania2018** [comment]
Related to:
https://github.com/SciSharp/TensorFlow.NET/issues/252
https://github.com/SciSharp/TensorFlow.NET/issues/253
