### ISSUE TITLE
Got this error while running TF.NET on Unity on Mac

### ISSUE THREAD

**Issue by MakVihas402** [SciSharp/TensorFlow.NET#502]
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Activator.CreateInstance[T] () (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
Tensorflow.Binding.New[T] () (at <8a1f7e7c69e4475d81bee40566e03f7b>:0)
Tensorflow.Binding..cctor () (at <8a1f7e7c69e4475d81bee40566e03f7b>:0)
Rethrow as TypeInitializationException: The type initializer for 'Tensorflow.Binding' threw an exception.

**Comment by Nucs** [comment]
Please take a look at this issue https://github.com/SciSharp/NumSharp/issues/353

**Comment by MakVihas402** [comment]
> Please take a look at this issue [SciSharp/NumSharp#353](https://github.com/SciSharp/NumSharp/issues/353)
> and this https://medium.com/@jonfoust/using-gcp-nuget-packages-with-unity-8dbd29c42cc4

I am able to run NumSharp but not TF.NET. The same error persists.

**Comment by Oceania2018** [comment]
Did you install `Install-Package SciSharp.TensorFlow.Redist` in your project?

**Comment by MakVihas402** [comment]
> Did you install `Install-Package SciSharp.TensorFlow.Redist` in your project?

Yes I did

**Comment by Oceania2018** [comment]
What version?

**Comment by MakVihas402** [comment]
<img width="619" alt="Screenshot 2020-02-10 at 7 16 18 PM" src="https://user-images.githubusercontent.com/60849050/74155197-245b5180-4c3a-11ea-9bcc-e3c08148a029.png">
**This is the package.config file**

<img width="471" alt="Screenshot 2020-02-10 at 7 15 44 PM" src="https://user-images.githubusercontent.com/60849050/74155230-33da9a80-4c3a-11ea-955a-56b1cbe5278d.png">
**This is the project folder**

**Comment by MakVihas402** [comment]
It's working!! 
I reinstalled TF.NET according to[https://github.com/SciSharp/TensorFlow.NET/blob/master/tensorflowlib/README.md](url).
