### ISSUE TITLE
tf.nn.conv2d produces NullReferenceException with Tensorflow.Tensor filters 

### ISSUE THREAD

**Issue by deiruch** [SciSharp/TensorFlow.NET#504]
The following code crashes with a `NullReferenceExeception`:
```
Tensorflow.Tensor filters = tf.Variable(np.ones(new[] { 15, 15, 1, 1 }, NPTypeCode.Float), dtype: tf.float32);
Tensorflow.Tensor weights = tf.Variable(np.ones(new[] { 1, W, H, BasisCount }, NPTypeCode.Float), dtype: tf.float32);
var convolved = tf.nn.conv2d(weights, filters, strides: new[] { 1, 1, 1, 1 }, padding: "SAME");
```

Stacktrace:
```
   at Tensorflow.RefVariable.op_Implicit(RefVariable var)
   at Tensorflow.tensorflow.nn_internal.conv2d(Tensor input, RefVariable filter, Int32[] strides, String padding, Boolean use_cudnn_on_gpu, String data_format, Int32[] dilations, String name)
```

It works when `filters` is not cast to `Tensorflow.Tensor` but is a `Tensorflow.RefVariable` instead. If this cannot be fixed easily, I suggest to at least provide a error message to the user.

**Comment by Oceania2018** [comment]
@deiruch It's been fixed, check the [examples](https://github.com/SciSharp/SciSharp-Stack-Examples/tree/4c814d6f6edd529c3637fe1dfb13a8b2ce6c27e1/src/TensorFlowNET.Examples/ImageProcessing).
