### ISSUE TITLE
Where can we contribute compiled Tensorflow DLL and Lib Variants ?

### ISSUE THREAD

**Issue by tcwicks** [SciSharp/TensorFlow.NET#509]
Managed to get a pure windows build environment working for compiling Tensorflow. My specific requirement was to get Tensorflow 1.15.2 DLL compiled with compute 6.1 (For GTX 1080 TI cards).
Would be happy to upload this and also compile further variants such as GPU compute capability variants or CPU with AVX2 etc... Question is where can I upload this?

**Comment by Oceania2018** [comment]
We release the compiled binary in NuGet. So there is no place to upload.
We compile the customized dll from this fork: https://github.com/SciSharp/tensorflow/tree/r1.15-tfnet
