### ISSUE TITLE
SciSharp.TensorFlow.Redist bad version?

### ISSUE THREAD

**Issue by Superpiffer** [SciSharp/TensorFlow.NET#518]
Why the SciSharp.TensorFlow.Redist nuget package uses TF version 1.15.1? I read on their repository that v1.15.1 was a mistake: https://github.com/tensorflow/tensorflow/issues/36282

**Comment by Oceania2018** [comment]
Actually, this Redist is built based on https://github.com/tensorflow/tensorflow/tree/r1.15, don't care about the minor version.

**Comment by Superpiffer** [comment]
Ok, but if you build from master you should have 1.15.2 and not 1.15.1. 
![image](https://user-images.githubusercontent.com/1334453/75858742-117f0b80-5df9-11ea-89e6-5fa50b0b7236.png)
Not a problem for me, I build tf myself, but I wanted to point that out.
