### ISSUE TITLE
Discrepancy in time to run inference

### ISSUE THREAD

**Issue by solarflarefx** [SciSharp/TensorFlow.NET#520]
So I generated a .pb file to run my model for inference.  For testing purposes I ran this in both python and TensorFlow.NET.  I timed both and for some reason things take much longer in TF.NET compared to Python.

Time to run one pass in Python: ~200 ms
Time to run one pass in TF.NET: ~1 second

I am not sure why there is such a large difference and I do not believe I am putting my timer at the wrong point.

Python:
`
start_time = time.time()
output_node = sess.graph.get_tensor_by_name(output_layer)
predictions, = sess.run(output_node, {input_node: input_tensor})
end_time = time.time()
print()
print('Time elapsed = ' + str(end_time - start_time))
print()
`

TF.NET
`
stopwatch.Start();
var network_out = sess.run(output_operation.outputs[0], (input_operation.outputs[0], input_tensor));
stopwatch.Stop();
Console.WriteLine("\n");
Console.Write("Time elapsed = ");
Console.WriteLine(stopwatch.ElapsedMilliseconds);
Console.WriteLine("\n");
`

Note that this is just the time to pass the data through the network and get an output (so other timing related to loading values into NumSharp types should not factor in at this point).

Should I really be expecting such a large variation?  If not, what could be going wrong?
Again, in both cases I am loading the .pb file.

Thanks in advance.

**Comment by solarflarefx** [comment]
I have run multiple times and consistently the numbers are as I have written.

**Comment by solarflarefx** [comment]
I am building an x64 .NET Framework (4.6.1) Console Application.
I am using the following NuGet packages:

- Google.Protobuf: v3.11.2
- NumSharp: v0.20.4
- SciSharp.TensorFlow.Redist-Windows-GPU: v1.14.1
- SciSharp.TensorFlowHub: v0.0.4
- System.Buffers: v4.4.0
- System.Memory: v4.5.3
- System.Numerics.Vectors: v4.4.0
- System.Runtime.CompilerServices.Unsafe: v4.5.2
- TensorFlow.NET: v0.13.0

I am building in Windows 10 x64.


Here is the relevant code:

Using statements:
`
using NumSharp;
using System;
using System.Collections.Generic;
using System.IO;
using Tensorflow;
using Tensorflow.Hub;
using static Tensorflow.Binding;
using System.Diagnostics;
using System.Threading;
` 


Main code block that runs inference:
`
            string input_name = "input_layer";
            string output_name = "output_layer";
            var input_operation = graph.OperationByName(input_name);
            var output_operation = graph.OperationByName(output_name);

            // Find volumes in test directory
            String[] subdirectoryEntries = Directory.GetDirectories(test_path);
            var Volume_Names = new List<string>();
            for (int i = 0; i < subdirectoryEntries.Length; i++)
            {
                Volume_Names.AddRange(Directory.GetFiles(subdirectoryEntries[i]));
            }

            // Create new stopwatch.
            Stopwatch stopwatch = new Stopwatch();

            // Convert list of volumes to string array
            String[] volume_names = Volume_Names.ToArray();

            for (int i = 0; i < volume_names.Length; i++)
            {
                // load volume
                NDArray vol = load_vol(volume_names[i], target_size, stored_size);

                // normalize volume
                vol = normalize_data(vol);

                for (int s = 0; s < vol.shape[0]; s = s + 1)
                {
                    NDArray patch = generate_patch(vol, s);

                    using (var sess = tf.Session(graph).as_default())
                    {
                        stopwatch.Start();
                        var network_out = sess.run(output_operation.outputs[0], (input_operation.outputs[0], patch));
                        stopwatch.Stop();

                        Console.WriteLine("\n");
                        Console.Write("Time elapsed = ");
                        Console.WriteLine(stopwatch.ElapsedMilliseconds);
                        Console.WriteLine("\n");

                        stopwatch.Reset();

                    }
                }
            }
`

I am essentially loading patches of data by segmenting 3D data and passing in these patches to the network.  Am I using the API incorrectly?

**Comment by Oceania2018** [comment]
Can you try move `using(var sess = tf.Session(graph).as_default())` out around `for loop` ?

**Comment by solarflarefx** [comment]
Thank you very much that solved it!
