### ISSUE TITLE
Any dependencies on Python?

### ISSUE THREAD

**Issue by solarflarefx** [SciSharp/TensorFlow.NET#521]
I was successfully able to build and run my application on my laptop.  I then moved the Visual Studio solution to another computer.  It compiles fine, but upon running I get an error saying tensorflow.dll file does not exist.  I find this strange as I am using the exact same project on my laptop.

Since I copied the whole Visual Studio Solution and project files, I would not think this would have anything to do with the project properties and settings.  I am wondering if there are any dependencies that I may have installed on my laptop that I do not on the test machine.  For example, I have Python on my laptop but not on the test machine.

**Comment by Oceania2018** [comment]
No any dependency on Python.
Related to https://github.com/SciSharp/TensorFlow.NET/issues/340

**Comment by solarflarefx** [comment]
So I read through that issue.  However I do not see a good solution to the problem there.  As I have said, I am literally running the same project in two different computers and getting different behavior.  I tried cleaning the projects and rebuilding, but it does not seem to make a difference.  Could this be related to a Visual Studio setting?

**Comment by Oceania2018** [comment]
As I know, the SciSharp redist binary doesn't work on specific CPU architecture.

**Comment by solarflarefx** [comment]
Can you elaborate on that a bit more?  If I install the Nuget packages and build in Visual Studio, would this not work?

**Comment by Oceania2018** [comment]
Can you paste your CPU specification here?

**Comment by Oceania2018** [comment]
Try lastet version [Preview3](https://www.nuget.org/packages/TensorFlow.NET/0.20.0-preview3).
