### ISSUE TITLE
Gpu memory limit

### ISSUE THREAD

**Issue by songminkyu** [SciSharp/TensorFlow.NET#523]
Hello. I want to limit C # tensorflow gpu memory, but I want to know if it is possible

https://github.com/tensorflow/tensorflow/issues/25138

**Comment by Superpiffer** [comment]
Of course you can:

```
var config = new ConfigProto
{
    GpuOptions = new GPUOptions
    {
        AllowGrowth = true,
        PerProcessGpuMemoryFraction = 0.5
    }
};

var session = tf.Session(graph, config);
```

**Comment by abhikirk** [comment]
Hi @Superpiffer , I have the same issue as @songminkyu even with your proposed solution. Almost all of the GPU memory is being allocated no matter what PerProcessGpuMemoryFraction is chosen, and no matter the values of AllowGrowth boolean. 

I am using: 

- M1000M GPU (compute capability = 5), 
- SciSharp.TensorFlow.Redist-Windows-GPU v1.15.1, 
- SharpCV v0.4.5, 
- TensorFlow.NET v0.15.1, 
- Code: [CnnInYourOwnData.cs](https://github.com/SciSharp/SciSharp-Stack-Examples/blob/master/src/TensorFlowNET.Examples/ImageProcessing/CnnInYourOwnData.cs)

Modifications:
Added
```
public ConfigProto GPUConfig()
        {
            ConfigProto config = new ConfigProto();
            GPUOptions gpuOptions = new GPUOptions();
            gpuOptions.AllowGrowth = true;
            //gpuOptions.PerProcessGpuMemoryFraction = 0.5;
            config.GpuOptions = gpuOptions;
            return config;
        }
```

With
```
private NDArray ReadTensorFromImageFile(string file_name)
        {
            using (var graph = tf.Graph().as_default())
            {
                Tensor file_reader = tf.read_file(file_name, "file_reader");
                Tensor decodeJpeg = tf.image.decode_jpeg(file_reader, channels: n_channels, name: "DecodeJpeg");
                Tensor cast = tf.cast(decodeJpeg, tf.float32);
                Tensor dims_expander = tf.expand_dims(cast, 0);
                Tensor resize = tf.constant(new int[] { img_h, img_w });
                Tensor bilinear = tf.image.resize_bilinear(dims_expander, resize);
                Tensor sub = tf.subtract(bilinear, new float[] { img_mean });
                Tensor normalized = tf.divide(sub, new float[] { img_std });
                
                using (Session sess = tf.Session(graph, GPUConfig()))
                {
                    return sess.run(normalized);
                }
            }
        }
```

And:

```
public void Run()
        {
            PrepareData();
            BuildGraph();           

            using (Session sess = tf.Session(GPUConfig()))
            {
                Train(sess);
                //Test(sess);
                Console.ReadLine();
            }
        }
```

I have also checked my GPU memory allocation separately with TensorFlow/Keras in Python, and there the GPU allocation works correctly.

Is there a bug in TensorFlow.NET or am I doing something wrong?
Thanks.

**Comment by openmll** [comment]
same problem. And usually example codes make 9GB memory allocation.

**Comment by openmll** [comment]
I have the same problem...still even TF.NET 2.0 with Tensorflow binary -GPU 2.3.  has same one.

**Comment by Oceania2018** [comment]
Been fixed in latest release.
