### ISSUE TITLE
Cannot find v0.20 on nuget.org

### ISSUE THREAD

**Issue by chriss2401** [SciSharp/TensorFlow.NET#526]
Hello,

The readme on master states that version v0.20 supports tf2.0, but on nuget.org v0.20 isn't published (https://www.nuget.org/packages/TensorFlow.NET/), and there also isn't a branch associated with that version. Is there any plan to support tf2.0 ?

**Comment by Oceania2018** [comment]
It's working in progress.

**Comment by chriss2401** [comment]
Ok, thanks for the quick answer!
