### ISSUE TITLE
tensorflow 2.0 update?

### ISSUE THREAD

**Issue by MnS-Developer** [SciSharp/TensorFlow.NET#545]
Hello
I'm using tensorflow.net very well right now.

I have a few questions.
When will the next version of tensorflow.net be released?
And would you like to add the Keras function on tensorflow.net?
Thank you.

**Comment by chriss2401** [comment]
Apparently it is work in progress:

https://github.com/SciSharp/TensorFlow.NET/issues/526

**Comment by Oceania2018** [comment]
Update the latest progress: https://twitter.com/haiping2015/status/1265730586938953730?s=21 .NET binding version is running faster than Python version.

**Comment by Oceania2018** [comment]
[Preview3](https://www.nuget.org/packages/TensorFlow.NET/0.20.0-preview3) released.
