### ISSUE TITLE
How are packages made like tensorflow.net?

### ISSUE THREAD

**Issue by MnS-Developer** [SciSharp/TensorFlow.NET#547]
Hello
I'm a student who is currently using Tensorflow.net very well.
 I'm curious about the Tensorflow.net development process, and 
I'd like to know what language you develop Tensorflow.net in.
Thank you.

**Comment by Oceania2018** [comment]
We use C# and C++ for tf.net. Welcome to join the development if want to contribute.

**Comment by MnS-Developer** [comment]
I want to unsubscribe.

2020년 9월 20일 (일) 오전 10:55, Haiping <notifications@github.com>님이 작성:
