### ISSUE TITLE
How to convert Jpeg array (byte[]) to an input for a predict function

### ISSUE THREAD

**Issue by sportbilly21** [SciSharp/TensorFlow.NET#551]
Hello
I am working  based on the example of the ImageRecognitionInception but instead of reading the jped from a file I have a jpeg array. I have tried most of the things I found in the internet but nothing is seems to work. Could you please let me know if there is a solution to this.
Many thanks

**Comment by chriss2401** [comment]
Maybe trying to convert the byte array to an NDArray (from the NumSharp nuget) and feed that into your session as an input ?

**Comment by Oceania2018** [comment]
@sportbilly21 Have you tried another simpler lib [SharpCV](https://github.com/SciSharp/SharpCV)?
