### ISSUE TITLE
Run “Hello, TensorFlow!” throw exception “Object reference not set to an instance of an object”

### ISSUE THREAD

**Issue by JohnnyZhang0628** [SciSharp/TensorFlow.NET#552]
this is my code:
```
using NumSharp;
using System;
using Tensorflow;
using static Tensorflow.Binding;

namespace TF.Net
{
    class Program
    {
        static void Main(string[] args)
        {
            var hello = tf.constant("Hello, TensorFlow!");

            // Start tf session
            using var sess = tf.Session();
            // Run the op
            var result = sess.run(hello);
            Console.WriteLine(result.ToString());
        }
    }
}

```
develop environment ：win10 ,vs2019
package:TensorFlow.NET 0.20.0-alpha2
screen:
![image](https://user-images.githubusercontent.com/28375774/82981067-a3279f00-a01d-11ea-91bb-9c0648a9303d.png)

**Comment by sportbilly21** [comment]
Hi , I have the same issue whenever I am trying to create a Tensor

**Comment by Oceania2018** [comment]
@JohnnyZhang0628 @sportbilly21 Have you installed the right [native library](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist/2.2.0.1)?

**Comment by JohnnyZhang0628** [comment]
@Oceania2018 i install this package,it still not work.
![image](https://user-images.githubusercontent.com/28375774/83087485-0bc95700-a0c4-11ea-85a2-d80355c70cf7.png)

**Comment by sportbilly21** [comment]
@Oceania2018 Hi I have installed either the GPU or the CPU package I am getting the same issue. The project is targeting 4.7 .Net Framework

**Comment by Oceania2018** [comment]
Have you checked whether the example works? https://github.com/SciSharp/SciSharp-Stack-Examples

**Comment by sportbilly21** [comment]
Hi , I have checked the examples, the image processing examples I have used are working OK. The above issue appears when you want to construct a new tensor

**Comment by vpenades** [comment]
It's happening to me too... it seems that tensors created from scratch throw a null reference exception.

Inspecting the tensor object, I can see the Device property is throwing it on intellisense.

**Comment by Oceania2018** [comment]
Should working on latest version [Preview3](https://www.nuget.org/packages/TensorFlow.NET/0.20.0-preview3).

**Comment by vpenades** [comment]
Ok, I've just tried preview 3.

Tensors don't throw an exception when they're created, but Device property is still throwing:

![imagen](https://user-images.githubusercontent.com/5433822/91693845-ec7f1180-eb6b-11ea-8de3-c00d75e61564.png)

So when I try to resize the tensor I've created with:

`Tensorflow.Binding.image.resize_bilinear(srcTensor, newSize);`

It throws an exception telling that "Device" is null.
