### ISSUE TITLE
Using TensorFlow.NET in Unity

### ISSUE THREAD

**Issue by andrewhong5297** [SciSharp/TensorFlow.NET#553]
Sorry if this isn't the right place for this but I've been trying for days - "using static Tensorflow.Binding;" gives me an error when I use it in Unity with Visual Studio. Does anyone know why that might be the case? Also, how does it choose which python env to use? 

Thanks!

**Comment by Cheongroach** [comment]
Maybe you can solve it by Unity's NuGet Package...

**Comment by flo-wolf** [comment]
Have you found a solution? I am too looking for tensorflow.NET integration into unity, to create builds in which I can train my models (not just the Unity Editor).

**Comment by andrewhong5297** [comment]
unity doesn't support anything but barracuda now since they want to use their own built solution. .NET and Sharp support stopped a year ago I believe.
