### ISSUE TITLE
loading of hdf5 files from keras not possible

### ISSUE THREAD

**Issue by mkeller97** [SciSharp/TensorFlow.NET#554]
Hi,

Loading of hdf5 files produced on Keras Python is becoming increasingly needed.

For TensorFlow 2.2 freezing graphs and and saving to a single .pb file is no longer supported.
The now recommended way is the SavedModel format which uses a folder with several files.

This makes hdf5 the only available single file format.
Unfortunately loading of hdf5 files in TF.Net Keras seems to be missing.

Is there any way this could be supported in future versions or are there technical limitations?

Thanks!

**Comment by Oceania2018** [comment]
BountySource: https://www.bountysource.com/issues/91873276-loading-of-hdf5-files-from-keras-not-possible
