### ISSUE TITLE
SciSharp.TensorFlow.Redist NuGet package does not contain linux tensorflow.so

### ISSUE THREAD

**Issue by dylangmiles** [SciSharp/TensorFlow.NET#573]
I have installed TensorFlow.NET 0.20.0-preview1 and SciSharp.TensorFlow.Redist 2.2.0.2 to my ASP.NET Core project. When I try to run in Linux Docker container the following exception is raised when I make a call to TensorFlow:  
```
DllNotFoundException: Unable to load shared library 'tensorflow' or one of its dependencies.
```
It looks like the tensorflow.so library is missing from SciSharp.TensorFlow.Redist 2.2.0.2

![image](https://user-images.githubusercontent.com/5096688/86539070-35af3e00-befa-11ea-8ca0-fdad6c8acd58.png)

I am wondering if there are plans to include tensorf.ow.so library in the SciSharp.TensorFlow.Redist package or I should be doing something different?

**Comment by Oceania2018** [comment]
Nothing different needed when stable version released.
Thank you for paying attention tensorflow.net.

**Comment by KevOrr** [comment]
In the meantime, are there any instructions on how to build the linux redist library? I've tried building the solution in `redist/`, but as far as I can tell, this doesn't create the `[lib]tensorflow.so`. I also tried using the vanilla tensorflow library, which is also called `tensorflow.so`, but that doesn't seem to be what it expects

**Comment by Oceania2018** [comment]
@dylangmiles @KevOrr [SciSharp.TensorFlow.Redist](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist/2.3.0) has been updated contains Windows, MacOS and Linux libraries.

**Comment by baiyude** [comment]
The tensorflow.so library is not included yet
