### ISSUE TITLE
load model

### ISSUE THREAD

**Issue by apicquot** [SciSharp/TensorFlow.NET#583]
I apologize in advance for asking a question there but I could not find any blog to do so

I am creating a Keras model in Python and would like to load and use it. Unfortunately the load_model is not implemented, any turn around ? I am using keras installed with Tensorflow, I do not have Keras installed.

```
net = tf.keras.models.load_model(net_name)
res = net.predict(sample)
```

**Comment by glennuggah** [comment]
Hi! I have the same issue. I train models in python with tensorflow 2.3.0 that I would like to load and use in c#. Is it possible with the current version of TensorFlow.NET? If not, will it be in the future? Thank you for your great work!

**Comment by patrickmurray18** [comment]
How do people normally use Tensorflow.NET if they can't load models? Do they only do inference after training? Or do they just load the weights?

**Comment by Oceania2018** [comment]
@patrickmurray18 It's working in progress. Not completed yet.

**Comment by Oceania2018** [comment]
Related to #554

**Comment by jptrxff** [comment]
@Oceania2018 Could you elaborate on what is the status on this issue? Is it in the plans to implement this feature? 

As far as i can see it seems pretty impossible to use models trained in tf2.2 or later with this framework atm. Or am I missing something? 

Thanks,

**Comment by jptrxff** [comment]
> @jptrxff You could use `model.load_weights` as an option.

Thanks for your reply, but as far as I can see then I would need to specify my model in C# right? My main issue is that my model definition and training are done in python. Thus I am looking for a way of running inference in C# for the model trained in python. (This has btw worked quite good for tensorflow 1.x, so thanks for the good work)

**Comment by sportbilly21** [comment]
Hello 
Model created in Python, saved in pb format not hd5 with Keras.
How I can loaded and run inference?
Many thanks

**Comment by jinfeei** [comment]
So many months already... I'm facing the same issue. BTW, thanks.

**Comment by axel578** [comment]
So many years, I'm facing the same issue

**Comment by Esther2013** [comment]
Is anybody interested in dropping bounty for this task.
**Bountysource is the funding platform for open-source software. Users can improve the open-source projects they love by creating/collecting bounties and pledging to fundraisers.**
https://bountysource.com/

**Comment by AsakusaRinne** [comment]
The loading of model has been supported after v0.100.4. I feel sorry for the inconvenience. tf.net has long been in short of hands and even myself began to join and maintain this repo several months ago. Thanks for all your support for tf.net! If there's any problem in the future, please open a new issue and I'll help with that. :)
