### ISSUE TITLE
Datasets<MnistDataSet> and MnistModelLoader don't exist in context while running DigitRecognitionCNN example

### ISSUE THREAD

**Issue by panoramix32** [SciSharp/TensorFlow.NET#584]
Hi all,

as I'm trying to run the DigitRecognitionCNN.cs example, and simply copy-pasting code not adding anything else of my own, I get the following errors:

**1. The name MnistModelLoader does not exist in the current context" referring to the following line:**
mnist = MnistModelLoader.LoadAsync(".resources/mnist", oneHot: true, showProgressInConsole: true).Result;

**2. "Datasets<> and MnistDataSet could not be found" referring to the following line:**
Datasets<MnistDataSet> mnist;

I have imported the following packages in case this helps:
using NumSharp;
using System.Diagnostics;
using System.IO;
using Tensorflow;
using static Tensorflow.Binding;

Any ideas what could be going wrong?

Thanks in advance!

Alex

**Comment by Esther2013** [comment]
@panoramix32 Please use the [1.15 branch](https://github.com/SciSharp/SciSharp-Stack-Examples/tree/tf.net-1.15). Master branch is for tensorflow 2.0 that is not finished yet.

**Comment by Esther2013** [comment]
It's finished: https://github.com/SciSharp/SciSharp-Stack-Examples/blob/9354b2d639b5118204af4d95a1ba13a049c68ac4/src/TensorFlowNET.Examples/BasicModels/LogisticRegression.cs#L93

**Comment by panoramix32** [comment]
I didn't thank you @Esther2013 ! So, thank you for your help! :-)
