### ISSUE TITLE
Tensorflow Lib Built from source (branch r2.2-tfnet) not working with master on Mac

### ISSUE THREAD

**Issue by arghyasur1991** [SciSharp/TensorFlow.NET#585]
I am trying to build Tensorflow from source from fork https://github.com/SciSharp/tensorflow using instructions in https://github.com/SciSharp/TensorFlow.NET/tree/master/tensorflowlib

The resultant libtensorflow.dylib is not working with TensorFlow.net dll I built from master branch or branch v0.22-eager-mode.

I am running the code on https://tensorflownet.readthedocs.io/en/latest/HelloWorld.html

`System.NullReferenceException: Object reference not set to an instance of an object
  at Tensorflow.Graph._as_graph_element_locked (System.Object obj, System.Boolean allow_tensor, System.Boolean allow_operation) [0x001b1] in TensorFlowNET.Core/Graphs/Graph.cs:215 `

**Comment by Esther2013** [comment]
I think the doc is not updated. You can refer the[ example repo](https://github.com/SciSharp/SciSharp-Stack-Examples) to get the latest samples.

**Comment by arghyasur1991** [comment]
This works, thanks.
