### ISSUE TITLE
Why TensorFlow.NET is on NumSharp.Lite and Gym.NET is on NumSharp?

### ISSUE THREAD

**Issue by daerhiel** [SciSharp/TensorFlow.NET#586]
Hi all,

What is the sense of mixing two dependencies together, keeping in mind that they should interact?

Are there any plans to set the common base for NumSharp dependency?
Will be contribution to change that accepted?

Thanks.

**Comment by Oceania2018** [comment]
`TensorFlow.NET` will be switched back to `NumSharp`, it's planning on `tf.net v0.20`.

**Comment by samuelcaldas** [comment]
Gym.NET source is on numsharp.lite

**Comment by Oceania2018** [comment]
@samuelcaldas @Nucs I don't even know `Gym.NET` is using lite version. https://github.com/SciSharp/Gym.NET/blob/master/src/Gym/Gym.csproj

As we know `NumSharp.Lite` is the compact version of `NumSharp` without full datatype supported.

**Comment by samuelcaldas** [comment]
I had problems with this and made a pull request solving the problem. @Nucs, use the source to compile Gym.NET

**Comment by daerhiel** [comment]
@samuelcaldas Gym.NET source references NumSharp.Lite, but the package has NumSharp dependency. Even though the source and a package are of the same version.

![image](https://user-images.githubusercontent.com/485120/88250275-b79bb700-ccaf-11ea-8a3a-7560458d2b25.png)
