### ISSUE TITLE
tf.keras.datasets

### ISSUE THREAD

**Issue by Esther2013** [SciSharp/TensorFlow.NET#587]
TensorFlow Datasets exposes public research datasets. It does all the grungy work of fetching the source data and preparing it into a common format on disk.

https://blog.tensorflow.org/2019/02/introducing-tensorflow-datasets.html

```python
import tensorflow_datasets as tfds

# Fetch the dataset directly
mnist = tfds.image.MNIST()
# or by string name
mnist = tfds.builder('mnist')
```

**Comment by Oceania2018** [comment]
It's been supported since [Preview3](https://www.nuget.org/packages/TensorFlow.NET/0.20.0-preview3).
