### ISSUE TITLE
tf.optimizers and tf.GradientTape() not found

### ISSUE THREAD

**Issue by DanielEliasib** [SciSharp/TensorFlow.NET#591]
Hi. I'm new to TensorFlow.NET, i'm trying to recreate some basic examples. 
When I tried to recreate the example in the main page I get an error that say that **tensorflow** doesn't contain a definition por **optimizers**, and it's the same with GradientTape().

I installed Tensorflow.NET and SciSharp.TensorFlow.Redist using NuGet. I tried looking in the issues for something similar but I couldn't found it, any idea what I'm doing wrong?

**Comment by Oceania2018** [comment]
@DanielEliasib Please check the latest update: https://github.com/SciSharp/SciSharp-Stack-Examples/blob/master/src/TensorFlowNET.Examples/BasicModels/LogisticRegression.cs
