### ISSUE TITLE
System.TypeInitializationException TensorFlow.NET.dll  exception：  “Tensorflow.Bindinng

### ISSUE THREAD

**Issue by loliq** [SciSharp/TensorFlow.NET#592]
I get this error:
System.TypeInitializationException TensorFlow.NET.dll  exception：  “Tensorflow.Bindinng ", in Tensorflow.Graph.OperationByName(String  operName).

**sometimes it can initialiaze correctly, sometimes not?**  I don't know why.

I use tensoflow.dll -GPU 1.15 and Tensorflow.Net 0.15.1.

**Comment by Oceania2018** [comment]
@loliq Please check the latest updated [examples](https://github.com/SciSharp/SciSharp-Stack-Examples).
