### ISSUE TITLE
Windows version of Tensorflow 2.x redistribution

### ISSUE THREAD

**Issue by dje-dev** [SciSharp/TensorFlow.NET#602]
It seems that the Windows version of Tensorflow redistribution ("SciSharp.TensorFlow.Redist-Windows-GPU") is still awaiting an update to 2.x, which is necessary for testing the preview versions of Tensorflow.NET Windows.  Hopefully this could be added. Thanks.

**Comment by GeorgeS2019** [comment]
The discussion leading to **[SciSharp.TensorFlow.Redist-Windows-GPU for 2.x](https://github.com/tensorflow/tensorflow/issues/35405#issuecomment-641681648)**

**Comment by Oceania2018** [comment]
The [nuget package](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist-Windows-GPU/2.3.0) is updated.

**Comment by dje-dev** [comment]
Haiping,
Wonderful, many thanks, it’s working!
Noted with appreciation.
David
