### ISSUE TITLE
Problems with the first "Hello, TensorFlow" Project

### ISSUE THREAD

**Issue by Ask24-7** [SciSharp/TensorFlow.NET#611]
Hello,
I've created a new C# programm in visual studio and get started like the discription (https://tensorflownet.readthedocs.io/en/latest/HelloWorld.html) said. 
I installed the libraries TensorFlow.NET, SciSharp.TensorFlow.Redist and SciSharp.TensorFlow.Redist-Windows-GPU with the Nuget Manager.
It doesn't work because the programm don't know what "tf." is. I think it's because of the inheritance "IExample" behind the class Hello World.
Where did i get the "IExample" or how can i run the programm without it?

![ErrorCode](https://user-images.githubusercontent.com/70621735/91939196-ace43100-ecf5-11ea-9354-030e23d28e40.PNG)

**Comment by Oceania2018** [comment]
Same as #613
