### ISSUE TITLE
TensorFlow.NET integration failed

### ISSUE THREAD

**Issue by Ask24-7** [SciSharp/TensorFlow.NET#613]
After implementing TensorFlow.NET via Nuget and writing a simple code, already by declaring a constant he gives me an error message.

The declaring looks like: var a = tf.constant(2);
The error message: The type initializer for Tensorflow.Binding threw an exception
![Unbenannt](https://user-images.githubusercontent.com/70621735/91977995-b97f7e00-ed23-11ea-905a-5888dd054120.PNG)

What have I done wrong or forgotten?
Thanks in advance.

**Comment by Oceania2018** [comment]
Please get started with the [example repo](https://github.com/SciSharp/SciSharp-Stack-Examples).
