### ISSUE TITLE
Tensorflow-GPU binary doesn't work for GPU usage.

### ISSUE THREAD

**Issue by openmll** [SciSharp/TensorFlow.NET#617]
Hello, I am working on TF.NET 2.0 for deep learning.
As you know, Scisharp.Tensorflow.Redist-Windows-GPU is updated with 2.3.0 last week.
But, when I try to run example code supported by "SciSharp Stack Examples", GPU is never used. I think training is processed with CPU only. GPU resource is not increased and even there is no allocation for GPU memory while running example project.
The example what I done is "MNIST CNN (Eager)" and "MNIST CNN (Keras)".
And, I am sure that I worked with just Tensorflow-GPU version binary without CPU version one.
(SciSharp.TensorFlow.Redist(2.3.0) is removed)

 Do I have any mistake or something skipped?

**Comment by Esther2013** [comment]
One thing you need to double check is the CUDA driver is working properly.

**Comment by anjoeaj** [comment]
It didn't work for me too when I had the wrong version of CUDA and cuDNN. 
The version that worked for me was CUDA 10.1 and cuDNN - cudnn-10.1-windows10-x64-v7.6.5.32

**Comment by quanap5kr** [comment]
What is happening with error? Who can help me with this? Thank you very much.
I am running an example TensorflowNet on GPU mode.
"
![error](https://user-images.githubusercontent.com/51312219/98697347-2a908100-23b8-11eb-98c5-ffff61df6e56.JPG)

Non-OK-status: GpuLaunchKernel(FillPhiloxRandomKernelLaunch<Distribution>, num_blocks, block_size, 0, d.stream(), gen, data, size, dist) status: Internal: no kernel image is available for execution on the device"

**Comment by allanchao** [comment]
I'm experiencing the same problem:

Non-OK-status: GpuLaunchKernel(FillPhiloxRandomKernelLaunch, num_blocks, block_size, 0, d.stream(), gen, data, size, dist) status: Internal: no kernel image is available for execution on the device"

Visual Studio 2019 Community and Preview (same problem on both)
GeForce 860M
Cuda 10.1 (cuda_10.1.243_426.00_windows)
Cudann 7.6.5 (cudnn-10.1-windows7-x64-v7.6.5.32.zip)
Windows 8.1

![image](https://user-images.githubusercontent.com/1066566/102162008-449d0380-3e3d-11eb-8774-e5c094ebbf0f.png)

**Comment by Esther2013** [comment]
Can you try [v2.4.0](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist-Windows-GPU/2.4.0)?
