### ISSUE TITLE
np.where has not been implemented

### ISSUE THREAD

**Issue by Banyc** [SciSharp/TensorFlow.NET#636]
The current version `0.21.0` of `Tensorflow.NET` does not implement `np.where()`

**Comment by GeorgeS2019** [comment]
@Banyc If possible, you need to get familiar with porting Unit Tests from native from google to Tensorflow.NET as discussed [here](https://github.com/SciSharp/TensorFlow.NET/issues/618#issuecomment-700037288).

Then if will have the "helicopter" view where are the missing parts and where the community can contribute in complementary way.

**Comment by GeorgeS2019** [comment]
@Banyc please help us update the [table ](https://github.com/SciSharp/tensorflow-net-docs/blob/master/docs/api/tf.md)so future questions on what has and has not implemented is clearly summarised.
