### ISSUE TITLE
np.pad has not been implemented

### ISSUE THREAD

**Issue by Banyc** [SciSharp/TensorFlow.NET#637]
The current version `0.21.0` of `Tensorflow.NET` does not implement `np.pad()`

**Comment by GeorgeS2019** [comment]
@Banyc If possible, you need to get familiar with porting Unit Tests from native from google to Tensorflow.NET as discussed [here](https://github.com/SciSharp/TensorFlow.NET/issues/618#issuecomment-700037288).

Then if will have the "helicopter" view where are the missing parts and where the community can contribute in complementary way.

**Comment by Esther2013** [comment]
@Banyc Please use `tf.array.pad` instead of `np.pad`.
