### ISSUE TITLE
NDArray set value by NDArray index not implement

### ISSUE THREAD

**Issue by asyura** [SciSharp/TensorFlow.NET#644]
var matrix = np.zeros((10,3));
matrix[np.arange(10), 1] = 1;

matrix[np.arange(10), np.random.randint(0, 2, (1,10))] = 1;

**Comment by GeorgeS2019** [comment]
@asyura  If possible, you need to get familiar with porting Unit Tests from native from google to Tensorflow.NET as discussed [here](https://github.com/SciSharp/TensorFlow.NET/issues/618#issuecomment-700037288).

Then if will have the "helicopter" view where are the missing parts and where the community can contribute in complementary way.

**Comment by Oceania2018** [comment]
@asyura Please try to use `tf.Variable` slice assign function: https://github.com/SciSharp/TensorFlow.NET/blob/d75366ce22a563ba6179840e6c4ac12ae43d5cf3/test/TensorFlowNET.UnitTest/Basics/VariableTest.cs#L56

**Comment by Esther2013** [comment]
@asyura You can follow this [example](https://github.com/SciSharp/TensorFlow.NET/blob/f8daeae69698806a55922a974da7adc89f03a34b/test/TensorFlowNET.UnitTest/Basics/VariableTest.cs#L56).
