### ISSUE TITLE
From docs "TF.NET simulate a 'with' syntax to manage the Graph lifecycle "

### ISSUE THREAD

**Issue by msadengineer** [SciSharp/TensorFlow.NET#645]
I am working through the documentation at <https://tensorflownet.readthedocs.io/> and the code sample it gives 

 `with<Graph>(tf.Graph().as_default(), graph =>
{
	var variable = tf.Variable(31, name: "tree");
	tf.global_variables_initializer();
	variable.assign(12);
});`

Below it it says that, "TF.NET simulate a with syntax to manage the Graph lifecycle which will be disposed when the graph instance is no long need." I can't find how tf.net simulates the 'with' keyword, but I was able to find .tf_with'. Replacing that inches me closer, I believe, but now I am getting hit with another error that states:

CS0311	The type 'Tensorflow.Graph' cannot be used as type parameter 'T' in the generic type or method 'Binding.tf_with<T>(T, Action<T>)'. There is no implicit reference conversion from 'Tensorflow.Graph' to 'Tensorflow.ITensorFlowObject'.

I am unsure how to move forward from here.

Thanks,
Sam

**Comment by Oceania2018** [comment]
Please get started with this [example project](https://github.com/SciSharp/SciSharp-Stack-Examples).
