### ISSUE TITLE
Can not find  keras in Tensorflow.Net 0.30

### ISSUE THREAD

**Issue by pardont** [SciSharp/TensorFlow.NET#647]
Hi，it seems keras has been removed from Tensorflow.Net，why?

how to use keras now?  please suggest.

Thanks.

**Comment by Oceania2018** [comment]
Keras is deployed in a separate package: https://www.nuget.org/packages/TensorFlow.Keras/

**Comment by pardont** [comment]
get it, Thank you very much.
