### ISSUE TITLE
No tf.keras.layers.layer class ?

### ISSUE THREAD

**Issue by minhduc66532** [SciSharp/TensorFlow.NET#648]
I want to translate this python code to C#

```
class ReflectionPadding2D(tf.keras.layers.Layer):
    def __init__(self, padding=(1, 1), **kwargs):
        self.padding = tuple(padding)
        self.input_spec = [tf.keras.layers.InputSpec(ndim=4)]
        super(ReflectionPadding2D, self).__init__(**kwargs)

    def compute_output_shape(self, s):
        return (s[0], s[1] + 2 * self.padding[0], s[2] + 2 * self.padding[1], s[3])

    def call(self, x, mask=None):
        w_pad, h_pad = self.padding
        return tf.pad(x, [[0, 0], [h_pad, h_pad], [w_pad, w_pad], [0, 0]], 'REFLECT')

    def get_config(self):
        config = super().get_config().copy()
        return config

```

This class inherit from tf.heras.layers.layer but there is no such class in Tensorflow.NET. Any ideas ?

**Comment by Oceania2018** [comment]
@minhduc66532 You can follow the implementation of other [layers](https://github.com/SciSharp/TensorFlow.NET/tree/master/src/TensorFlowNET.Keras/Layers).

**Comment by minhduc66532** [comment]
@Oceania2018 Well i'm really want to contribute to the project but i don't think i have enough skill to do it. So back to the problem so basically there currently no such class in tensorflow.NET ? If that so then is there any work around to rewrite the custom layer above in C# ? (I think i'm gonna ask this question in Keras.NET github page ?)

**Comment by Oceania2018** [comment]
@minhduc66532 It's already been here.

![image](https://user-images.githubusercontent.com/1705364/100521083-15ad3f00-3167-11eb-87a7-944d30616788.png)

You just need inherit `Layer` and do your `ReflectionPadding2D` layer.

**Comment by minhduc66532** [comment]
I'm very sorry for the late reply, but thank you. I'm gonna close this problem now

**Comment by minhduc66532** [comment]
I tried to use it but 
![image](https://user-images.githubusercontent.com/66398066/100618318-41d6e480-334e-11eb-9a41-15fdf4246852.png)
For some reasons, i found no "Layer" class, only ILayer and the "Utils" namespace doesn't exist either (sorry for closing and reopen the problem like this without trying the solution first)

**Comment by Oceania2018** [comment]
@minhduc66532 You have to install [TensorFlow.Keras](https://www.nuget.org/packages/TensorFlow.Keras/) package.

**Comment by minhduc66532** [comment]
It WORK !!! Thank you so much for all of your answer. I will close this problem (for real this time)
