### ISSUE TITLE
TensorFlow.Binding from F#?

### ISSUE THREAD

**Issue by nhirschey** [SciSharp/TensorFlow.NET#656]
I was working on the starting example from the readme. I am having trouble with the initial setup.

- In Visual studio,  intellisense works, but the code does not run. 
- In VS code: intellisense does not work, but the code will run.

1. In Visual studio 16.9.0 Preview1, intellisense works but the code does not.

![image](https://user-images.githubusercontent.com/5226115/101258712-99c07300-36e1-11eb-9f5c-027b45585c3e.png)

2. In VSCode (insider, dev F# extension), intellisense is broken but the code works.

![image](https://user-images.githubusercontent.com/5226115/101258739-c2e10380-36e1-11eb-978c-291c13e99d79.png)

**Comment by Oceania2018** [comment]
@nhirschey Maybe this is a better [initial start project](https://github.com/SciSharp/SciSharp-Stack-Examples/tree/master/src/TensorFlowNET.Examples.FSharp) written in F#.

**Comment by nhirschey** [comment]
Hi @Oceania2018 , yes I saw that and it is where I saw the binding code. Thank you for putting that example together.

But I thought it was important to raise this issue, because a script workflow using `#r "nuget: ..."` library loading is a good goal for an F# workflow. Granted, this is perhaps more an IDE issue right now, but it's good to recognize where those issues are.

**Comment by nhirschey** [comment]
Looks like it works in dotnet fsi and ionide 4.17.0.  It should work in ionide 5.0 and visual studio dotnet fsi once those tooling features are finished.

See https://github.com/SciSharp/TensorFlow.NET/pull/662 for a working example.

**Comment by Esther2013** [comment]
@nhirschey Do you mind fix the [F# example](https://github.com/SciSharp/SciSharp-Stack-Examples/tree/master/src/TensorFlowNET.Examples.FSharp)? Currently it's using the old version of v0.11 tf.net, we'd like to upgrade to v0.20+.

**Comment by nhirschey** [comment]
@Esther2013 I will take a look at it and try to fix it when I have a chance.

**Comment by dsyme** [comment]
Thanks @nhirschey !
