### ISSUE TITLE
Set Weights on layer

### ISSUE THREAD

**Issue by mjkkirschner** [SciSharp/TensorFlow.NET#657]
I am looking to set the weights of an individual neuron or layer manually without training.
According to this post:
https://stackoverflow.com/questions/47183159/how-to-set-weights-in-keras-with-a-numpy-array

I should be looking for something similar to set_weights()

Can this be done currently in TensorFlow.NET?

**Comment by Oceania2018** [comment]
@mjkkirschner `set_weights` hasn't been implemented yet. It's on the way.

**Comment by Oceania2018** [comment]
@mjkkirschner Check if you can usr `keras.backend.batch_set_value`.
