### ISSUE TITLE
tf.scan() NOT work

### ISSUE THREAD

**Issue by quanap5** [SciSharp/TensorFlow.NET#659]
I would like to implement the RNN layer using tf.scan(). But there is something wrong with tf.scan(). Do you have any idea for this exception? Or how to reimplement scan function in Graph mode.
```
        [TestMethod]
        public void ScanTest()
        {
            tf.compat.v1.disable_eager_execution();
            var fn = new Func<Tensor, Tensor, Tensor>((a, x) => tf.add(a, x));

            var sess = tf.Session().as_default();

            var input = tf.placeholder(TF_DataType.TF_INT32, new TensorShape(6));
            var scan = functional_ops.scan(fn, input);
            try
            {
                sess.run(scan, (input, np.array(1, 2, 3, 4, 5, 6)));
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }
```

And this is the exception message the above code throw.
{"{{node scan/while/Less}} has inputs from different frames. The input {{node scan/while/Merge_1}} is in frame 'scan/while/while_context'. The input {{node scan/Const_2}} is in frame ''."}

Thank you very much.

**Comment by Oceania2018** [comment]
@quanap5 `TF.NET` 0.20+ doesn't support the `conditional` and `loop` statement very well. Can you try to switch back to v0.15?

**Comment by quanap5** [comment]
I try to switch TF.Net version 0.15 but the exception still happen.

![Capture](https://user-images.githubusercontent.com/3444790/101300385-c78bf000-3878-11eb-86cf-718642c46852.JPG)

Please take a look and comment on it. Thank you.

**Comment by Oceania2018** [comment]
@quanap5 You need to downgrade the tensorflow lib as well, install [tensorflow v1.15 redist](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist/1.15.1) from NuGet.

**Comment by quanap5** [comment]
Hi, I used TF.Net v0.15.1 and SciSharp.Tensorflow.Redist v 0.15.1. The exception now disappears but the result is not correct.
Why result return [0, 0, 0, 0, 0, 0]. What is problem in my case?
![Capture02](https://user-images.githubusercontent.com/3444790/101305902-fad57b80-3886-11eb-898f-aa9829f8ce0f.JPG)

**Comment by Oceania2018** [comment]
@quanap5 Can you PR a minimal UnitTest for v0.20 int [this file](https://github.com/SciSharp/TensorFlow.NET/blob/master/test/TensorFlowNET.UnitTest/ManagedAPI/ControlFlowApiTest.cs). Due to limited personal time, I don't have time to maintain old version. I'll try my best to fix it in newer version.

**Comment by quanap5** [comment]
OK. Thank you for your support.
