### ISSUE TITLE
Missing properties and methods in both Layer and LayerArgs class

### ISSUE THREAD

**Issue by minhduc66532** [SciSharp/TensorFlow.NET#660]
I want to translate this class to C#:
```
class BilinearUpSampling2D(Layer):
    def __init__(self, size=(2, 2), data_format=None, **kwargs):
        super(BilinearUpSampling2D, self).__init__(**kwargs)
        self.data_format = normalize_data_format(data_format)
        self.size = conv_utils.normalize_tuple(size, 2, 'size')
        self.input_spec = InputSpec(ndim=4)

    def compute_output_shape(self, input_shape):
        if self.data_format == 'channels_first':
            height = self.size[0] * input_shape[2] if input_shape[2] is not None else None
            width = self.size[1] * input_shape[3] if input_shape[3] is not None else None
            return (input_shape[0],
                    input_shape[1],
                    height,
                    width)
        elif self.data_format == 'channels_last':
            height = self.size[0] * input_shape[1] if input_shape[1] is not None else None
            width = self.size[1] * input_shape[2] if input_shape[2] is not None else None
            return (input_shape[0],
                    height,
                    width,
                    input_shape[3])

    def call(self, inputs):
        input_shape = K.shape(inputs)
        if self.data_format == 'channels_first':
            height = self.size[0] * input_shape[2] if input_shape[2] is not None else None
            width = self.size[1] * input_shape[3] if input_shape[3] is not None else None
        elif self.data_format == 'channels_last':
            height = self.size[0] * input_shape[1] if input_shape[1] is not None else None
            width = self.size[1] * input_shape[2] if input_shape[2] is not None else None
        
        return tf.image.resize(inputs, [height, width], method=tf.image.ResizeMethod.BILINEAR)

    def get_config(self):
        config = {'size': self.size, 'data_format': self.data_format}
        base_config = super(BilinearUpSampling2D, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))
```
But the problem is i can't find compute_output_shape() to override, no size and data_format property or something fimiliar in Layer class. 

![image](https://user-images.githubusercontent.com/66398066/101305447-50a12800-3875-11eb-84af-f2861303040b.png)

No compute_output_shape() method in sight:

![image](https://user-images.githubusercontent.com/66398066/101305669-c4433500-3875-11eb-8d81-dbec03dfc723.png)

And in the LayerArgs class there is no items() method:

![image](https://user-images.githubusercontent.com/66398066/101305525-77f7f500-3875-11eb-8c4b-eb18c12fb72d.png)

Any ideas ? And thank you for all of our answer

**Comment by Oceania2018** [comment]
@minhduc66532 Added virtual method `ComputerOutputShape`, will be available for 12/12/2020 release.

**Comment by minhduc66532** [comment]
Thank you, i hope it will available as soon as possible

**Comment by Oceania2018** [comment]
It's available on [tensorflow.kears v0.2.0](https://www.nuget.org/packages/TensorFlow.Keras/), please take a look and let's know if you need further functions.

**Comment by minhduc66532** [comment]
![image](https://user-images.githubusercontent.com/66398066/101989114-c7548000-3cd0-11eb-9695-bb2226163ea7.png)
![image](https://user-images.githubusercontent.com/66398066/101989121-d89d8c80-3cd0-11eb-8921-480165690591.png)
For some reason Layer class does not exist in Tensorflow.Keras.Layers anymore ?

**Comment by Oceania2018** [comment]
@minhduc66532 Please follow the [example projects](https://github.com/SciSharp/SciSharp-Stack-Examples/blob/master/src/TensorFlowNET.Examples/ImageProcessing/MnistFnnKerasFunctional.cs).

**Comment by minhduc66532** [comment]
Ahh ok, everything is working fine now
