### ISSUE TITLE
No tf.keras.models.load_model() and tf.saved_model.load() ?

### ISSUE THREAD

**Issue by minhduc66532** [SciSharp/TensorFlow.NET#664]
Keras is a method not class 
![image](https://user-images.githubusercontent.com/66398066/101569525-38f9a900-3a07-11eb-877f-1b565248d4d2.png)
No load_model function in sight
![image](https://user-images.githubusercontent.com/66398066/101569606-647c9380-3a07-11eb-9457-6dbc05e7ef59.png)
Still no luck
![image](https://user-images.githubusercontent.com/66398066/101569704-91c94180-3a07-11eb-9216-4e3c6b25358b.png)
No tf.saved_model.load()
![image](https://user-images.githubusercontent.com/66398066/101573541-09e53680-3a0b-11eb-8c96-b42f02dd7558.png)

**Comment by Oceania2018** [comment]
```csharp
using static Tensorflow.KerasApi;
var inputs = keras.Input(shape: (32, 32, 3), name: "img");
```

**Comment by minhduc66532** [comment]
Ok i'm confused, i think that u are comment at the wrong issue ?

**Comment by Oceania2018** [comment]
Still working on the `load_model` function.

**Comment by minhduc66532** [comment]
Ohh ok so what about tf.lite.TFLiteConverter.from_saved_model() function ? Or is there anyway to load a tflite model ?

**Comment by simonbuehler** [comment]
hi,
is there any progress on this so we could use e.g. posenet tflite model with TensorFlow.net?

**Comment by bradqiu1982** [comment]
saved model is the official model format which TF2.x support. 
Would you mind to implement  the  saved_model.load function?
Otherwise, Tensorflow.net can not work with TF2.x. 
So appreciate for your jobs.

**Comment by Oceania2018** [comment]
It's in progress: https://github.com/SciSharp/TensorFlow.NET/blob/954462f4f835ea561caedc9b0af75aa39c984cb1/src/TensorFlowNET.Keras/Models/ModelsApi.cs#L16

**Comment by minhduc66532** [comment]
That's great to hear

**Comment by IamSierraCharlie** [comment]
Hello there,  is there an update on this?
Or further more, an alternative to "tf.saved_model.load"?
