### ISSUE TITLE
Using flower_photos dataset in ImageClassificationKeras

### ISSUE THREAD

**Issue by ekleiman22** [SciSharp/TensorFlow.NET#666]
I downloaded yours TensorFlowNET.Examples and try to check all examples. In example #15 in class **ImageClassificationKeras** in method PrepareData() you use address
C:/Users/haipi/.keras/datasets/flower_photos
that is obviously wrong for my computer where an user is eug10. So I downloaded flower_photos dataset using the following python code:
  dataset_url = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"
data_dir = tf.keras.utils.get_file(origin=dataset_url, 
                                   fname='flower_photos', 
                                   untar=True)
and now I have 
  C:/Users/eug10/.keras/datasets/flower_photos
with 5 subdirectories such as daisy and so on.
I replaced the path C:/Users/haipi/.keras/datasets/flower_photos
with my path  C:/Users/eug10/.keras/datasets/flower_photos
But get an error 
  "Object reference not set to an instance of an object."
on the line
   var train_ds = keras.preprocessing.image_dataset_from_directory(data_dir,

How to resolve this problem?
Thank you

**Comment by Esther2013** [comment]
Fixed, will be available for next release (Jan 9th, 2021).
