### ISSUE TITLE
Error when running latest version of redist package

### ISSUE THREAD

**Issue by Aangbaeck** [SciSharp/TensorFlow.NET#687]
When running SciSharp.TensorFlow.Redist 2.4.0 the keras example gets an error 
"System.EntryPointNotFoundException: 'Unable to find an entry point named 'TF_StringEncodedSize' in DLL 'tensorflow'.'"

By downgrading to to 2.3.1 it works again.

There is also some issues with the keras example code that i will try to fix myself

**Comment by Oceania2018** [comment]
v2.4 removed the api, we’ll adopt it. If you can fix it, it’s all welcome to PR your fix.

**Comment by masgh021** [comment]
Hello
I have this problem ,
i use this solution 
[https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_Training/WebApp.Predict] 

with winform application
but i have same error
with this version
v2.3  and  v2.4

**Comment by nhannt201** [comment]
I also downgraded to 2.3.1 and it works again.
