### ISSUE TITLE
tf.slice is not implement?

### ISSUE THREAD

**Issue by gucy1972** [SciSharp/TensorFlow.NET#691]
in Tensorflow.net 0.31.1 version, 

my test sorce cde like this:

int[] tfBegin = new int[] { 1, 1, 1 };
int[] tfSize = new int[] { 1, 1, 1 };
var testImg = tf.slice<int,int>(tensorImg, tfBegin, tfSize);

but I got an exceptions as follow:
System.NullReferenceException:“Object reference not set to an instance of an object.”
 at Tensorflow.Operation.op_Implicit(Operation op) ...

I wonder "tf.slice" functions is not implement or there are some mistakes in my code?

thankx!

**Comment by GeorgeS2019** [comment]
@gucy1972 please help us update the [table ](https://github.com/SciSharp/tensorflow-net-docs/blob/master/docs/api/tf.md)so future questions on what has and has not implemented is clearly summarised.

**Comment by Esther2013** [comment]
@gucy1972 Please check the [slice and assign](https://github.com/SciSharp/TensorFlow.NET/blob/6509ae0b7fcee3fe97fd4ad79309018efba53eef/test/TensorFlowNET.UnitTest/Basics/VariableTest.cs#L57) unit test.
