### ISSUE TITLE
System.NotImplementedException: 'feed_dict data type NDArray'

### ISSUE THREAD

**Issue by minhduc66532** [SciSharp/TensorFlow.NET#696]
My code:
```
static void Main(string[] args)
{
	string dd = $@"{System.IO.Directory.GetCurrentDirectory()}/model/";
	Mat mat = new Mat();
	VideoCapture video = new VideoCapture(0, VideoCaptureAPIs.DSHOW);
	video.Read(mat);
	Bitmap bm = OpenCvSharp.Extensions.BitmapConverter.ToBitmap(mat);
	var nd = bm.ToNDArray(); 

	var graph = new Graph();
	graph.Import($"{dd}pydnet.pb");
	using (var sess = tf.Session(graph))
	{
		var imgTensor = graph.OperationByName("im0");
		var outTensor = graph.OperationByName("truediv");
		var ndout = sess.run(outTensor.outputs[0], (imgTensor.outputs[0], nd));
	}
}
```
Follow this example:
(https://github.com/SciSharp/SciSharp-Stack-Examples - ImageProcessing - ImageRecognitionInception.cs)
![image](https://user-images.githubusercontent.com/66398066/102703986-b2678600-42a8-11eb-9adc-827fba7011ad.png)

Error:
![image](https://user-images.githubusercontent.com/66398066/102703995-c9a67380-42a8-11eb-938b-bf08d17b6583.png)
Any ideas ?

**Comment by Oceania2018** [comment]
Need to use [SharpCV](https://github.com/SciSharp/SharpCV) to get a compatible `NDArray`.
