### ISSUE TITLE
Limit resources for each session ?

### ISSUE THREAD

**Issue by minhduc66532** [SciSharp/TensorFlow.NET#705]
This is from the [official tutorial](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth):
![image](https://user-images.githubusercontent.com/66398066/102990233-a2ba9c80-4549-11eb-9570-1c3c981be78f.png)

But there is no set logical device or something similar in ConfigProto class:
![image](https://user-images.githubusercontent.com/66398066/102991434-c67ee200-454b-11eb-930d-e857a88aaf7a.png)
![image](https://user-images.githubusercontent.com/66398066/102991438-c7177880-454b-11eb-99dd-17133ca73df2.png)
![image](https://user-images.githubusercontent.com/66398066/102991442-c848a580-454b-11eb-8bd3-84510437706b.png)
Thanks for all of your answers

**Comment by Oceania2018** [comment]
Releated to https://github.com/SciSharp/TensorFlow.NET/issues/713.
