### ISSUE TITLE
Can't not run Tensorflow.NET on Nvidia Jetson Nano

### ISSUE THREAD

**Issue by minhduc66532** [SciSharp/TensorFlow.NET#709]
So i have the nano running ubuntu 18.04 arm. I tried to run it but it can't find tensorflow shared library
![image](https://user-images.githubusercontent.com/66398066/103173799-00275400-4890-11eb-855a-eca9d49369b2.png)
So i look into the Tensorflow.NET source code and found this
```
string str1 = "tensorflow";
string directory = AppDomain.CurrentDomain.BaseDirectory;
string file = "";
string url = "";
string str2;
switch (Environment.OSVersion.Platform)
{
  case PlatformID.Win32NT:
    str2 = str1 + ".dll";
    file = Path.Combine(directory, "libtensorflow-cpu-windows-x86_64-1.14.0.zip");
    url = "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.14.0.zip";
    break;
  case PlatformID.Unix:
    str2 = "lib" + str1 + ".so";
    file = Path.Combine(directory, "libtensorflow-cpu-linux-x86_64-1.14.0.tar.gz");
    url = "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.14.0.tar.gz";
    break;
  default:
    throw new RuntimeError(string.Format("Unknown OS environment: {0}", (object) Environment.OSVersion.Platform));
}
```
So basically i need the libtensorflow.so, but by looking at the name of the library i can see that this library is running on x86 not ARM and tensorflow 1.14.0 instead of tensorflow 2.3.0 (which installed on the nano). So what now ? Tensorflow.NET do not have ARM support ??

**Comment by Oceania2018** [comment]
@minhduc66532 I don't have Jetson Nano, so I can't reproduce it. TensorFlow should be able to run on Jetson Nano according to the doc https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform/index.html

**Comment by minhduc66532** [comment]
Well i think Tensorflow.NET refuse to run is because tensorflow lib Tensorflow.NET is using is for x86 CPU and NOT ARM CPU ? Since i also install jetson nano using that tutorial you mentioned

**Comment by Oceania2018** [comment]
TensorFlow.NET can run on Ubuntu 18.04: check the compile and testing log [here](https://ci.appveyor.com/project/Haiping-Chen/tensorflow-net/build/job/6wih89lqr796sshg).

**Comment by minhduc66532** [comment]
#715
