### ISSUE TITLE
Memory Leak Problem

### ISSUE THREAD

**Issue by ijrys** [SciSharp/TensorFlow.NET#710]
When I run ResNet Demo I findthe program use too many memory(up to nearly 9GiB)

![屏幕截图 2020-12-28 115538](https://user-images.githubusercontent.com/15842103/103188639-3bfc0100-4904-11eb-8657-f2be3ca51c50.png)

windows10 20H2(19042.685)
.Net Core 3.1
TensorFlow.NET 0.31.1
TensorFlow.Keras 0.2.1
SciSharp.TensorFlow.Redist 2.3.1

**Comment by Oceania2018** [comment]
@ijrys Are you saying this example [ResNet](https://github.com/SciSharp/SciSharp-Stack-Examples/blob/master/src/TensorFlowNET.Examples/ImageProcessing/ToyResNet.cs)?

**Comment by ijrys** [comment]
> @ijrys Are you saying this example [ResNet](https://github.com/SciSharp/SciSharp-Stack-Examples/blob/master/src/TensorFlowNET.Examples/ImageProcessing/ToyResNet.cs)?

I copy the code from readme.md(homepage of the project), it looks a little different from ToyResNet.cs, but major parts are same

**Comment by Oceania2018** [comment]
Please try latest version [v0.4.0](https://www.nuget.org/packages/TensorFlow.Keras/).
