### ISSUE TITLE
 How to set Keras session options?

### ISSUE THREAD

**Issue by iillii** [SciSharp/TensorFlow.NET#712]
I have create ConfigProto with some options:
`var config = new ConfigProto
{
 GpuOptions = new GPUOptions
 {
  AllowGrowth = true,
  PerProcessGpuMemoryFraction = 0.7
 }
};`
How to apply this options to Keras session? I have not found something similar to keras.backend.set_session()

**Comment by Esther2013** [comment]
Need to compete #713 dependent task.

**Comment by Oceania2018** [comment]
Will be available for next release on 01/09/2021.
`tf.Context.Config.GpuOptions.AllowGrowth = true`

**Comment by Oceania2018** [comment]
Releated to https://github.com/SciSharp/TensorFlow.NET/issues/713.
