### ISSUE TITLE
Recompile everything to use different tensorflow 2.3.1 package ?

### ISSUE THREAD

**Issue by minhduc66532** [SciSharp/TensorFlow.NET#715]
So i made [this](https://github.com/SciSharp/TensorFlow.NET/issues/709) issue but no one answer. So i think i have to do everything in the hard way. So the Jetson nano use ubuntu 18.04 with tensorflow 2.3.1 installed (for ARM obviously). So is there any guide to recompile the library to use tensorflow 2.3.1 built for ARM ?

**Comment by Oceania2018** [comment]
@minhduc66532 You can refer this [doc](https://www.tensorflow.org/install/source) to compile a specific version for tensorflow.

Below commands will only build the `libtensorflow.so`.
```shell
./configure
bazel --output_base=D:/tmp/tfcompilation build -c opt //tensorflow:tensorflow
```

**Comment by minhduc66532** [comment]
Ok so now how can i make Tensorflow.NET to use this custom tensorflow library instead of the SciSharp.TensorFlow.Redist-xxxx-GPU package ?

**Comment by Oceania2018** [comment]
I think one option is replace the `libtensorflow.so` in appropriate runtime folder like:

![image](https://user-images.githubusercontent.com/1705364/103446569-aaafc600-4c46-11eb-9dd3-9b4c12485c8c.png)

Or place the library in the `\user\bin` depends on your local library searching strategy, check the Linux docs.

**Comment by minhduc66532** [comment]
Ahh ok, i gonna try it then report the result. Thank you for your answer

**Comment by minhduc66532** [comment]
@Oceania2018 Everything is working fine now. After the library done building, all i need to do is to drag the built library into the folder that has the executable. Run the program on command line using ./ProgramName.

**Comment by Oceania2018** [comment]
@minhduc66532 Do you mind PR the solution in this [doc](https://github.com/SciSharp/TensorFlow.NET/tree/master/tensorflowlib)?

**Comment by minhduc66532** [comment]
Of course but noob question here. Where do i start :D ? Since this is the first time i work with these kind of stuff

**Comment by minhduc66532** [comment]
@Oceania2018 Oof nvm, i found everything out now
