### ISSUE TITLE
.NET framework 4.8

### ISSUE THREAD

**Issue by Yandychang1** [SciSharp/TensorFlow.NET#717]
Does TensorFlow.NET support .NET framework 4.8??

**Comment by lwqwag** [comment]
tf.net based on Netstandard2.0, so nfx4.8 is supported

**Comment by Superpiffer** [comment]
@Oceania2018, starting from TF.NET 0.60.0, .NET Framework 4.8 is not supported anymore:
![image](https://user-images.githubusercontent.com/1334453/129538636-5ad84c01-529e-4737-80ff-ee9727745569.png)

**Comment by Oceania2018** [comment]
@Superpiffer We changed the default framework to .net standard 2.1 to support new language feature.

**Comment by Superpiffer** [comment]
> 
> 
> @Superpiffer We changed the default framework to .net standard 2.1 to support new language feature.

So we cannot update your library anymore, at least until we migrate all our packages to net5.0. Bummer... Thanks for the answer! 😃

**Comment by Oceania2018** [comment]
@Superpiffer It'll change back to .net standard 2.0 for next release.

**Comment by themightierdan** [comment]
I've started a simple .NET Framework4.7.2 winform project, installed the tensorflow.Net and the scisharp.tensorflow.redist nugets.. 
and it won't load Tensorflow.Binding.  But the same process works perfectly on .NET Core projects I'd created.  Any idea what I'm missing?
