### ISSUE TITLE
Memory leak in FuncGraph

### ISSUE THREAD

**Issue by Esther2013** [SciSharp/TensorFlow.NET#727]
There is memory leak when created a `FuncGraph` with resources in the graph.
When disposing the `FuncGraph`, the resources havn't been disposed never.

**Comment by Esther2013** [comment]
`KerasHistory` causes `ResourceVariable` not released.

**Comment by Oceania2018** [comment]
Same issue as https://github.com/SciSharp/TensorFlow.NET/issues/719.

**Comment by MPnoy** [comment]
As I understand it, because of this, when working in eager mode with Keras models, a memory leak occurs when model.Apply() or layer.Apply() is constantly called.
