### ISSUE TITLE
tf.zeros_like and tf.ones_like don't work

### ISSUE THREAD

**Issue by MPnoy** [SciSharp/TensorFlow.NET#732]
I am trying to port my GAN network code to C# and found several problems:

the first is that the tf.zeros_like and tf.ones_like functions throw the "Object reference not set to an instance of an object" exception anyway. Simple code:

```
using System;
using Tensorflow;
using NumSharp;
using static Tensorflow.Binding;
using static Tensorflow.KerasApi;
using Tensorflow.Keras.Layers;
using Tensorflow.Keras.Utils;

class Program
{
     static void Main (string [] args)
     {
         var test1 = tf.zeros_like(new Tensor(new float [] {0f, 0.5f, 1f}, TF_DataType.TF_FLOAT), TF_DataType.TF_FLOAT, "test1");
         var test2 = tf.ones_like(new Tensor(new float [] {0f, 0.5f, 1f}, TF_DataType.TF_FLOAT), TF_DataType.TF_FLOAT, "test2");
     }
}
```

instead, I wrote these functions that work and should do the same, but I'm not sure:

```
public static Tensor TFOnesLike(Tensor x)
{
    return tf.constant(1f, x.dtype, x.TensorShape);
}

public static Tensor TFZerosLike(Tensor x)
{
    return tf.constant(0f, x.dtype, x.TensorShape);
}
```

Another problem is that after that the project started, but after 100-130 training cycles the program crashes due to out of video memory, that is, most likely a memory leak occurs. I tried to manually call Dispose on tensors, but it doesn't help. I can post the project if it helps.

Windows 10
NET Core 3.1
SciSharp.TensorFlow.Redist-Windows-GPU 2.3.1
TensorFlow.Keras 0.3.0
TensorFlow.NET 0.32.0
CUDA 10.1 and cudnn for this

**Comment by Oceania2018** [comment]
Memory issue is fixed as https://github.com/SciSharp/TensorFlow.NET/issues/727
`tf.ones_likie` is related to https://github.com/SciSharp/TensorFlow.NET/pull/731

**Comment by MPnoy** [comment]
I switched from the nuget version to the repository version and the memory leak was fixed.
The problem with tf.zeros_like turned out to be false because I wrote tf.zeros_like(new Tensor... instead of tf.zeros_like(tf.constant..., after that it worked.
Only tf.ones_like remains broken, but you know about it, so the issue can be closed.
