### ISSUE TITLE
math.erf unavilable

### ISSUE THREAD

**Issue by chaseaucoin** [SciSharp/TensorFlow.NET#738]
Hi there,

For some of the stuff I'm doing it would be nice to have access to math.erf 

https://www.tensorflow.org/api_docs/python/tf/math/erf

I tried using the patterns I saw in this library to do the following

`       static Tensor erf(Tensor x, string name = null)
        {
            var results = tf.Runner.TFE_FastPathExecute(tf.Context, tf.Context.DeviceName,
                    "Erf", name,
                    null,
                    x);

            return results[0];
        }`
        
This seemed to be the right key given:
https://github.com/tensorflow/tensorflow/blob/e433b66b7a82920e072eb7526560e2b07411633a/tensorflow/core/kernels/cwise_op_erf.cc

That gave me the error: 'The given key 'Erf' was not present in the dictionary.'

I'm using Tensorflow.NET 0.32.0.0 with SciSharp.TensorFlow.Redist-Windows-GPU 2.4.0

Any help would be appreciated.

**Comment by Oceania2018** [comment]
@chaseaucoin Added `tf.math.erf` as https://github.com/SciSharp/TensorFlow.NET/commit/c8643c42662282d37f0600889e1a3df3ef76f9ec, if you found more missing functions, you can follow the pattern to add, welcome to PR.
