### ISSUE TITLE
When I tried example, it showed EntryPointNotFoundException

### ISSUE THREAD

**Issue by jhoeing** [SciSharp/TensorFlow.NET#744]
Does anybody happen before?
![擷取](https://user-images.githubusercontent.com/78470296/106716993-0ef4e980-663a-11eb-986f-760bbed7becb.PNG)

**Comment by Oceania2018** [comment]
Please install [v2.3.1](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist/2.3.1).

**Comment by jhoeing** [comment]
I install v2.3.1 shown the same error.  Is there any other solution?

**Comment by Oceania2018** [comment]
Can you try download this [example project](https://github.com/SciSharp/SciSharp-Stack-Examples)?
