### ISSUE TITLE
tf.train.Saver() saver.save() System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by Tomazzzzz** [SciSharp/TensorFlow.NET#750]
var saver = tf.train.Saver();
saver.save(sess, @"D:\FOREX\TensorFlow\FirstTry", global_step: step);
On save I got the exception bellow:
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

Inner Exception 1:
EntryPointNotFoundException: Unable to find an entry point named 'TF_StringEncodedSize' in DLL 'tensorflow'.

**Comment by Oceania2018** [comment]
Related to https://github.com/SciSharp/TensorFlow.NET/issues/721

**Comment by Tomazzzzz** [comment]
Current version is 0.33.0 TensorFlow.NET
Should I downgrade to some specific version?

**Comment by Oceania2018** [comment]
https://www.nuget.org/packages/SciSharp.TensorFlow.Redist/2.3.1

**Comment by Tomazzzzz** [comment]
THNX!!!

**Comment by Tweekaz2018** [comment]
Sry, but it doesnt work for me. 
I wrote about change version  :(
