### ISSUE TITLE
LSTM Model Loading

### ISSUE THREAD

**Issue by cdwetal** [SciSharp/TensorFlow.NET#752]
How can I load an LSTM model in TensorFlow.NET? I trained and saved the model in python, and now I would like to load the model in TensorFlow.NET and make a prediction. I have seen no guidance on this in the documentation.

**Comment by akaimody123** [comment]
Hi, I'm also very interested in knowing the answer for this question.

**Comment by 3threeFX** [comment]
> Hi, I'm also very interested in knowing the answer for this question.

me too...

**Comment by Wanglongzhi2001** [comment]
Close due to LSTM has been developed and can be load, please reopen if you still have question, thanks!
