### ISSUE TITLE
Can you replace Numsharp.Lite with normal NumSharp package ?

### ISSUE THREAD

**Issue by minhduc66532** [SciSharp/TensorFlow.NET#769]
The latest SharpCV package is using NumSharp which conflicts with Tensorflow.NET using Numsharp.Lite. And what is the difference between Numsharp and Numsharp.Lite anyway ? Also, Numsharp is updated more frequently than Numsharp.Lite so yeah..

**Comment by Oceania2018** [comment]
Will combine them into NumSharp for next release.
