### ISSUE TITLE
Any plans for Tensorflow Graphics?

### ISSUE THREAD

**Issue by bitstormGER** [SciSharp/TensorFlow.NET#785]
First of all many thanks for your amazing work!
Do you have any plans to also cover tensorflow-graphics in the future?

**Comment by Oceania2018** [comment]
@bitstormGER What's `tensorflow-graphics` ? do you have the introduction link?

**Comment by bitstormGER** [comment]
I would start looking into https://www.tensorflow.org/graphics/overview

**Comment by Oceania2018** [comment]
Sorry, no plan for it.
