### ISSUE TITLE
The "NDArray" type exists both in NumSharp.Lite and in NumSharp

### ISSUE THREAD

**Issue by esisl** [SciSharp/TensorFlow.NET#786]
var nd = new NDArray(new int[] { 3, 1, 1, 2 });

The code gives an error

The "NDArray" type exists both in "NumSharp.Lite, Version = 0.1.12.0, Culture = neutral, PublicKeyToken = cc7b13ffcd2ddd51" and in "NumSharp, Version = 0.30.0.0, Culture = neutral, PublicKeyToken = cc7b13ffcd2ddd51"

Unfortunately I couldn't find any ready-made solutions :(

**Comment by Oceania2018** [comment]
Try to remove `NumSharp.Lite`
