### ISSUE TITLE
Why do I use GPU to compute much slower than CPU?

### ISSUE THREAD

**Issue by bbhxwl** [SciSharp/TensorFlow.NET#792]
Why do I use GPU to compute much slower than CPU?

DateTime dt = DateTime.Now;
            for (int i = 0; i < 100000; i++)
            {
                float w = -0.06f;
                float b = -0.73f;
                float sum = w + b;
                //var W = tf.Variable(-0.06f);
                //var b = tf.Variable(-0.73f);
                //var sum = tf.add(W, b);
            }
            var d = DateTime.Now - dt;

00 18789 seconds for CPU and 18 seconds for GPU. 100000 cycles

**Comment by Oceania2018** [comment]
Please try latest version.
