### ISSUE TITLE
Unable to find an entry point named 'TF_StringInit' in DLL 'tensorflow'

### ISSUE THREAD

**Issue by zielo-hue** [SciSharp/TensorFlow.NET#794]
I'm following the tutorial in the TF.NET documentation, and the basic Hello World tutorial fails with:

`Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'TF_StringInit' in DLL 'tensorflow'.`

I'm using `Include="TensorFlow.NET" Version="0.40.0"` and `Include="SciSharp.TensorFlow.Redist-Windows-GPU" Version="2.4.0"`.
I've got precisely no clue why the Hello World example doesn't work. I'm using .NET 5; would that be related?

Thanks!

**Comment by bbhxwl** [comment]
me too,

**Comment by zielo-hue** [comment]
It looks like `SciSharp.TensorFlow.Redist-Windows-GPU` is one version (2.4.0) behind `SciSharp.TensorFlow.Redist` (2.4.1), which does not have this issue. Waiting for the 2.4.1 release of Redist GPU seems appropriate here.

**Comment by bbhxwl** [comment]
> It looks like `SciSharp.TensorFlow.Redist-Windows-GPU` is one version (2.4.0) behind `SciSharp.TensorFlow.Redist` (2.4.1), which does not have this issue. Waiting for the 2.4.1 release of Redist GPU seems appropriate here.

Only 2.4.0

**Comment by kenshunlee** [comment]
u might import SciSharp.TensorFlow.Redist-Windows-GPU and SciSharp.TensorFlow.Redist , only need one.
