### ISSUE TITLE
layers.Conv2D input shape missing

### ISSUE THREAD

**Issue by bine0josi** [SciSharp/TensorFlow.NET#795]
Hey,
I am currently missing the feature that I can create a convolutional layer with an input shape.
This is how it works in TensorFlow: layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)) and this returns a layer.
Is there a similar way to do it with tensorflow.net?
I know that I can apply an input after creating the layer, but thsi returns me a tensor and no layer. Am I missing something?

**Comment by Oceania2018** [comment]
You can have the temp layer variable `simple_rnn_layer`:
```csharp
var inputs = np.random.rand(32, 10, 8).astype(np.float32);
var simple_rnn_layer = keras.layers.SimpleRNN(4);
var output_tensor = simple_rnn_layer.Apply(inputs);
```
