### ISSUE TITLE
Can't load tensorflow.dll

### ISSUE THREAD

**Issue by LittleLittleCloud** [SciSharp/TensorFlow.NET#805]
TF.Net version: 0.20.1
TF binary version: 2.3.1

This issue is reported by a customer from ModelBuilder
- https://github.com/dotnet/machinelearning-modelbuilder/issues/1413

From the log, it seems that somehow model builder can't find tensorflow.dll. However, our customer checks the installation folder and the TF binary is located in the right place.

Any idea what might cause this error?

**Comment by zamanashiq3** [comment]
use the NuGet manager to SciSharp.TensorFlow.Redist into the project. It solved the problem for me.
