### ISSUE TITLE
TensorFlow.TFException:“Invalid GraphDef”

### ISSUE THREAD

**Issue by bbhxwl** [SciSharp/TensorFlow.NET#807]
Failed to load model, why?

private TFGraph LoadModel(string modelFile)
        {
            var g = new TFGraph();
            var model = File.ReadAllBytes(modelFile);
            g.Import(model,"AA");
            return g;
        }

**Comment by Oceania2018** [comment]
```csharp
var g = new Graph();
var status = g.Import("saved_model.pb");
```
