### ISSUE TITLE
Warning while installing TensorFlow.Net

### ISSUE THREAD

**Issue by dtrader007** [SciSharp/TensorFlow.NET#809]
I get the following warning during installation. Compiles without issues but when running hello world program it throws unknown error.  

Severity	Code	Description	Project	File	Line	Suppression State
Warning		There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "TensorFlow.NET, Version=0.40.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=AMD64", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	glib

**Comment by mschwrdtnr** [comment]
For me setting the platform target of my program to x64 fixed this issue and let my application compile.

**Comment by Oceania2018** [comment]
Try latest version [v2.5.0 in NuGet](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist/2.5.0).
