### ISSUE TITLE
how  to train NDArray size max then int.MaxValue

### ISSUE THREAD

**Issue by vivid216** [SciSharp/TensorFlow.NET#820]
> i have a code like this  , while run throw a index_out_of_range exception while elements exceed 1716262912. and  newNp2 sharp size is  1716262912 which less than 500000 * 16 * 64 * 25.  so how to train a large data in tensorflow ?  help ！！
```   
           NDArray newNp2 = new NDArray(NPTypeCode.Float, new Shape(500000, 16, 64, 25));
            for (int j = 0; j < 500000; j++)
            {
                var slicenp = newNp[$"{j}:{j + 1024},0:25"];
                newNp2[j] = slicenp.reshape(16, 64, 25);
            } 
```

**Comment by Oceania2018** [comment]
Latest version changed to `long` type.
