### ISSUE TITLE
Save Session

### ISSUE THREAD

**Issue by Tomazzzzz** [SciSharp/TensorFlow.NET#821]
Hello,
I can find public static Session LoadFromSavedModel(string path)
But where is SaveSession ?

**Comment by Oceania2018** [comment]
```csharp
using var graph = tf.Graph().as_default();
graph.Import("model.pb");
```

**Comment by Tomazzzzz** [comment]
_But where is SaveSession ?_
So with "graph.Import("model.pb");" I will be able to save **save session**?

THNX

**Comment by Oceania2018** [comment]
```csharp
tf.train.freeze_graph("\\MODEL", "model", new[] { })
```
