### ISSUE TITLE
How to use Bidirectional in TensorFlow.NET?

### ISSUE THREAD

**Issue by DNF-SaS** [SciSharp/TensorFlow.NET#829]
Hi,

I'd like to use Keras.Layers.Bidirectional (https://github.com/SciSharp/Keras.NET/blob/master/Keras/Layers/Wrappers.cs#L35) from TensorFlow.NET.
Unfortunately, it's not implemented in TensorFlow.Keras (at least I cannot find it it's LayersApi) - or do I miss a point?!
I'm pretty new to these libs, so any advice or workaround is highly appreciated. :-)

Thanks for a short reply!
Sascha

**Comment by Andy-Elizabeth-mouse** [comment]
Bidirectional's api is still waiting for you to create it(at least this project does not have this feature yet) :-)

**Comment by Wanglongzhi2001** [comment]
Close due to bidirectional has been developed, please reopen if you still have question, thanks!
