### ISSUE TITLE
How to use Tensorflow.net for transfer learning? 

### ISSUE THREAD

**Issue by seabluescn** [SciSharp/TensorFlow.NET#838]
Hi,
I tried to use the following code:
Model model = keras.models.load_model(ModelFile);
But i found the function:"keras.models.load_model " What is returned is void type.
Thanks!

**Comment by Oceania2018** [comment]
Please check this example: https://github.com/SciSharp/SciSharp-Stack-Examples/blob/master/src/TensorFlowNET.Examples/ImageProcessing/TransferLearningWithInceptionV3.cs
