### ISSUE TITLE
keras.models.load_model returns void

### ISSUE THREAD

**Issue by asadowns** [SciSharp/TensorFlow.NET#841]
I'm trying to load a previously trained HDF5 model using `keras.models.load_model`.

```csharp
var model = keras.models.load_model(filePathString);
```

Looking at the tensorflow documentation this method should return a model: https://www.tensorflow.org/api_docs/python/tf/keras/models/load_model

However when I go to the function declaration I see

```csharp
using System.IO;
using Tensorflow.Keras.Saving;
using ThirdParty.Tensorflow.Python.Keras.Protobuf;

public void load_model (string filepath, bool compile = true);
```

It looks like this should probably not be void but be a keras `Model` that is the return type?

**Comment by Oceania2018** [comment]
@asadowns `models.load_model` is not completed. Please use `load_weights` instead.

**Comment by asadowns** [comment]
@Oceania2018 Any idea when `load_model` will be completed? My issue with using `load_weights` is that I need to recreate all of the inputs and outputs rather than just load a saved model. Is this not the case? Maybe I'm missing something.

If possible can you point me towards some documentation? Or is my understanding correct that I will need to recreate the input and output layers and then call `load_weights`? Thanks!

**Comment by Oceania2018** [comment]
Pretty busy recently, no estimation to finish `load_model`.
Yes, you need to build the model then `load_weights`.

**Comment by thislookshard** [comment]
@Oceania2018 Thanks for all your work on this
Has there been any update on `load_model`?

It's critical to my project that it can load a HDF5 model without needing to rebuild it every time. Our models can be changed frequently by our computer vision team and we are looking to utilize them in our C# application through this.

@asadowns Have you been able to figure out a work around without having to rebuild the model?

**Comment by asadowns** [comment]
@thislookshard I have not. We ended up just switching tracks and going with `tf2onnx` to convert the model from HDF5 to ONNX and then using https://docs.unity3d.com/Packages/com.unity.barracuda@1.0/manual/index.html to run the model since our team was working on a unity project. Not sure if yours is a `.NET` application but you also might try looking into `WindowsML` as well.
