### ISSUE TITLE
can latest tensorflow.net support .netframework 4.7.x

### ISSUE THREAD

**Issue by xinheblue** [SciSharp/TensorFlow.NET#842]
latest tensorflow.net can only support being installed on netcore projects, due to other issues, we can only use netframework such as netframework 4.7.2, we cann't install the latest master branch.

Can this be supported for the master branch？

Best regards!

**Comment by Oceania2018** [comment]
@xinheblue Should be able to support .net framework 4.7.2 acoording to https://docs.microsoft.com/en-us/dotnet/standard/net-standard. TensorFlow .NET is based on `.netstandard 2.0`.
