### ISSUE TITLE
Tensorflow.NumPy not thread safe

### ISSUE THREAD

**Issue by Superpiffer** [SciSharp/TensorFlow.NET#846]
I upgraded from version 0.40 to version 0.60.2 and now in our multithread application Numpy operations seems not to be thread safe anymore:

![image](https://user-images.githubusercontent.com/1334453/131092927-3bcb9d6a-f5ae-4dc6-8af0-82bc21a2d8ec.png)
![image](https://user-images.githubusercontent.com/1334453/131093117-78f1895f-fc63-4cd9-9b90-df2efb07dd1e.png)

I tried to enclose with `lock (Locks.ProcessWide)` but doesn't always solve the problem.

**Comment by Oceania2018** [comment]
@Superpiffer It's been fixed, it will take effect for v0.60.3.

**Comment by Superpiffer** [comment]
@Oceania2018 I just updated to v0.60.3 but I have the same problem with the same test code:
![image](https://user-images.githubusercontent.com/1334453/132321815-364913d8-d58e-426c-b413-da11a127f681.png)

**Comment by Oceania2018** [comment]
@Superpiffer It seems an other error, can you find out which variable is null?

**Comment by Superpiffer** [comment]
I tried adding TensorFlow.Binding project from master to my solution. More frequently I have this exception (file _tf.compat_):
![image](https://user-images.githubusercontent.com/1334453/132507672-4419f974-d29d-44dd-8e34-2fd16125599d.png)
Sometime I have this different exception (file _EagerRunner.TFE_FastPathExecute.cs_):
![image](https://user-images.githubusercontent.com/1334453/132507361-974053c2-5f18-4e2a-afc7-a74b342a784d.png)
As before, I have this problem only with more than 2 threads.

**Comment by Superpiffer** [comment]
> 
> 
> @Superpiffer I'm pretty sure it's been fixed. Can you try whether it throws error if set the thread as 1 ?

No error with 1 thread, some random errors with 2 or more (THREADS_COUNT variable using the example posted before).

**Comment by Superpiffer** [comment]
@Oceania2018 I just tried again and the only solution I found is to put `tf.enable_eager_execution()` before the lines where I had the exceptions, apparently the EagerMode was disabled by other operations. 
Anyway I tried to disable Eager mode with `tf.compat.v1.disable_eager_execution()` but for some reason I cannot perform Numpy operations:

![image](https://user-images.githubusercontent.com/1334453/141788337-b279cb7f-84a4-4623-b3d5-8bb1cbcaa96a.png)


![image](https://user-images.githubusercontent.com/1334453/141778274-ae533155-fb0d-4e6c-85dc-757455e02eb7.png)

So Eager mode is mandatory for Numpy?

**Comment by Oceania2018** [comment]
@Superpiffer Yes, `Eager Mode` is required for `NumPy`,
It's supposed to enabled automatically by `MethodBoundaryAspect.Fody` component.
Please make sure your start project has installed `MethodBoundaryAspect.Fody` as well:

![image](https://user-images.githubusercontent.com/1705364/141821349-25e1e286-c784-45fb-aa72-30d87386ba39.png)

**Comment by Superpiffer** [comment]
> 
> 
> @Superpiffer Yes, `Eager Mode` is required for `NumPy`, It's supposed to enabled automatically by `MethodBoundaryAspect.Fody` - `AutoNumPy` component. Please make sure your start project has installed `MethodBoundaryAspect.Fody` as well:
> 
> ![image](https://user-images.githubusercontent.com/1705364/141821349-25e1e286-c784-45fb-aa72-30d87386ba39.png)
> 
> ![image](https://user-images.githubusercontent.com/1705364/141821559-242140e4-5793-4765-a6e9-eb6ca6824317.png)

Thanks for the answer. I tried installing the library and it correctly switches between eager and graph mode (even without `MethodBoundaryAspect.Fody` I think) but it still doesn't work with multiple threads (I'm trying with 5 or more). 
I checked the threads:
- One returns an exception here:
![image](https://user-images.githubusercontent.com/1334453/141947073-ec2fec39-d0bf-4e52-acb9-2603450bb882.png)
- some of them are correctly locked:
![image](https://user-images.githubusercontent.com/1334453/141948002-2a32961f-c549-4b0c-9dbf-6d7882673f44.png)
- some of them are performing native calls, for example:
![image](https://user-images.githubusercontent.com/1334453/141948233-3a1dca7a-67e3-434e-9db5-ae9f0b4befc6.png)
![image](https://user-images.githubusercontent.com/1334453/141948704-97db722c-da6b-4e8b-bc1c-0bf67290113c.png)
![image](https://user-images.githubusercontent.com/1334453/141949594-7d1d2c79-18e6-4d63-869e-6cbf700fdfd3.png)
The last one is the inference of a freezed graph, so it's surely in graph mode, all the others threads are Numpy operations.

Maybe I'm missing something?

**Comment by Oceania2018** [comment]
Could you upload your latest updated project?

**Comment by Superpiffer** [comment]
> 
> 
> Could you upload your latest updated project?

Here's the test project:
[TensorflowMultithreadingTest.zip](https://github.com/SciSharp/TensorFlow.NET/files/7553156/TensorflowMultithreadingTest.zip)


I included Tensorflow.Binding from master in the solution and I already shared the segmenter and the test images before. 
Native libraries (TF 2.6 and CUDA) are located elsewhere:

![image](https://user-images.githubusercontent.com/1334453/142170345-a76262c7-57d1-4d1b-83ad-85b3759f97f1.png)

**Comment by Oceania2018** [comment]
@Superpiffer It's working without any issue.

![image](https://user-images.githubusercontent.com/1705364/142295041-b0a964e4-9663-43e2-8ed3-8ca4a165d4af.png)

**Comment by Superpiffer** [comment]
@Oceania2018 Ok I'm dumb... I noticed that in your test there are less images than my test, apparently i forgot that I added other images in "1" folder! Can you try with this folder?
[cats.zip](https://github.com/SciSharp/TensorFlow.NET/files/7561352/cats.zip)

I also noticed that in your test you used the CPU version of tensorflow native, I tried that and the problem seems to be less frequent, I have to launch multiple time the test or increase the thread number (for example 10) in order to obtain the exceptions. With the GPU version (this one: https://www.nuget.org/packages/SciSharp.TensorFlow.Redist-Windows-GPU/ and CUDA 11), I have the exceptions every single time. Maybe because the inference is faster?
