### ISSUE TITLE
Support 'tensorflow::MemmappedEnv' for memory mapped graphs

### ISSUE THREAD

**Issue by feliwir** [SciSharp/TensorFlow.NET#848]
Hey, i was trying to load the mozilla deepspeech model, which are usually provided as memory mapped graphs, see Mozilla DeepSpeech as an example:
https://github.com/mozilla/DeepSpeech/releases/tag/v0.9.3 

They're loading the file in their native api like this:
https://stackoverflow.com/questions/43533264/how-to-read-tensorflow-memory-mapped-graph-file-in-android

However i couldn't find `tensorflow::MemmappedEnv` anywhere. How should i load such a model? My current code only works for non-memory mapped files (which i don't have for Mozilla DeepSpeech):
```csharp
// This only works for regular non-mapped Graphs)
using (var codedInput = new CodedInputStream(File.OpenRead(modelPath)))
{
  var graphDef = new GraphDef();
  codedInput.ReadMessage(graphDef);
}
```

Thanks in advance!

**Comment by Oceania2018** [comment]
@feliwir We're implementing the Lite (mobile) version in this [tflite branch](https://github.com/SciSharp/TensorFlow.NET/blob/v0.70-tflite/test/TensorFlowNET.Native.UnitTest/Lite/TfLiteTest.cs).
Feel free to contribute.

**Comment by feliwir** [comment]
@Oceania2018 I guess you mean "Xamarin Mobile"? No i'm using desktop .NET 5. I'm currently trying to add the memory mapped filesystem, once i get it working i'll update here

**Comment by Oceania2018** [comment]
Yes, currently tf.net doesn't support tflite model. Not sure whether it works or not in the way of `codedInput.ReadMessage(graphDef);`
There is another way to load graph:
```csharp
var graph = new Graph().as_default();
graph.Import(Path.Join(modelDir, pbFile));
```

**Comment by feliwir** [comment]
@Oceania2018 the problem is not the regular tflite model, but the memmapped filesystem: 
https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/core/util/memmapped_file_system.cc#L209
It's the file wrapped in another file

**Comment by Oceania2018** [comment]
The `GraphDef` is converted to `MemmappedFileSystem`, and you want to load this format in your application, correct?

**Comment by feliwir** [comment]
> The `GraphDef` is converted to `MemmappedFileSystem`, and you want to load this format in your application, correct?

Exactly. I think the extension **.pbmm** is used to clarify clarify this.

**Comment by feliwir** [comment]
> Yes, currently tf.net doesn't support tflite model. Not sure whether it works or not in the way of `codedInput.ReadMessage(graphDef);`
> There is another way to load graph:
> 
> ```cs
> var graph = new Graph().as_default();
> graph.Import(Path.Join(modelDir, pbFile));
> ```

This does not work with **Stream** objects. I can't use a path, since the file is only virtual, so i have to use protobuf directly or not?

**Comment by feliwir** [comment]
I got it working like this now:
(MemmappedFileSystem)
```csharp
using System;
using System.IO;
using System.IO.MemoryMappedFiles;
using System.Linq;
using Tensorflow;

namespace Jarvis.TFUtil
{
    public class MemmappedFileSystem
    {
        public const string MEMMAPPED_PACKAGE_DEFAULT_NAME = "memmapped_package://.";

        private MemoryMappedFile _mmapFile;
        private MemmappedFileSystemDirectory _directory;

        public MemmappedFileSystem(string path)
        {
            using (var stream = File.OpenRead(path))
            {
                // Read the offset for the directory
                var offsetData = new byte[sizeof(ulong)];
                stream.Seek(-sizeof(ulong), SeekOrigin.End);
                stream.Read(offsetData, 0, sizeof(ulong));
                var offset = BitConverter.ToUInt64(offsetData, 0);

                var dirLength = stream.Length - (long) offset - sizeof(ulong);
                if (dirLength < 0)
                {
                    throw new InvalidDataException("Malformed mmapped filesystem!");
                }

                var dirData = new byte[dirLength];

                Console.WriteLine("Length: {0}, DirOffset: {1} DirLength: {2}", stream.Length, offset, dirLength);


                stream.Seek((long) offset, SeekOrigin.Begin);
                stream.Read(dirData, 0, (int) dirLength);

                _directory = MemmappedFileSystemDirectory.Parser.ParseFrom(dirData);

                foreach (var element in _directory.Element)
                {
                    Console.WriteLine("Found mmapped file: {0}, {1})", element.Name, element.Length);
                }
            }

            _mmapFile = MemoryMappedFile.CreateFromFile(path, FileMode.Open);
        }

        public Stream OpenMemmapped(string filename)
        {
            var entry = _directory.Element.FirstOrDefault(x => x.Name == filename);
            if (entry == null)
            {
                throw new FileNotFoundException($"Missing memmaped file entry: {filename}");
            }

            return _mmapFile.CreateViewStream((long) entry.Offset, (long) entry.Length);
        }
    }
}
```
And then the actual usage:
```csharp
if (Path.GetExtension(modelPath) == ".pbmm")
            {
                var fs = new MemmappedFileSystem(modelPath);
                using (var stream = fs.OpenMemmapped(MemmappedFileSystem.MEMMAPPED_PACKAGE_DEFAULT_NAME))
                {
                    var buf = new byte[stream.Length];
                    stream.Read(buf, 0, (int)stream.Length);
                    var graphDef = GraphDef.Parser.ParseFrom(buf);
                }
            }
            else
            {
                var graph = new Graph().as_default();
                graph.Import(modelPath));
            }
```` 
As you can see i'm now kind of stuck with the **GraphDef** object which is kind of useless

**Comment by Oceania2018** [comment]
I add this `MemmappedFileSystem` proto in this [commit](https://github.com/SciSharp/TensorFlow.NET/commit/f3a51daba4ab7b13d97ef0c8ec5e5dfe6cdbc0ee).

**Comment by feliwir** [comment]
@Oceania2018 great thanks! One last question: How can i fetch metadata from my model like here:
https://github.com/mozilla/DeepSpeech/blob/master/native_client/tfmodelstate.cc#L101

I tried using the **FeedItem** constructor, but with no real success yet :-/

**Comment by Oceania2018** [comment]
The error may raised from `new Tensor("metadata_version")`, you should find the coresponding tensor  in the way of `graph.OperationByName("metadata_version")`

**Comment by feliwir** [comment]
Yes, i'll do a PR, good suggestion! 
When i do:
```csharp
var op = graph.OperationByName("metadata_version");
_logger.Info(op.output);
```
i'm not quite sure how to get an integer scalar out of that. Whatever i try - it crashes or does not contain the "6" which i'd expect.

**Comment by Oceania2018** [comment]
```csharp
Tensor op = graph.OperationByName("metadata_version");
print(op.numpy());
```

**Comment by feliwir** [comment]
@Oceania2018 
```
Exception has occurred: CLR/System.NotImplementedException
An exception of type 'System.NotImplementedException' occurred in System.Private.CoreLib.dll but was not handled in user code
   at Tensorflow.Operation.numpy()
   at Jarvis.Speech.STT.DeepSpeech.<Setup>d__18.MoveNext() in /home/mbits/Development/jarvis/src/Jarvis.Speech/STT/DeepSpeech.cs:line 119
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Jarvis.Core.Engine.<Setup>d__5.MoveNext() in /home/mbits/Development/jarvis/src/Jarvis.Core/Engine.cs:line 30
   ```

**Comment by Oceania2018** [comment]
Carefully for this:
![image](https://user-images.githubusercontent.com/1705364/132502305-07be51dc-c5fd-4039-b8e9-340d37e2af49.png)

**Comment by feliwir** [comment]
Wow thanks! That worked

**Comment by feliwir** [comment]
One last question before i close this issue. Using **numpy()** works for all scalar integers, but when i try to use it on the string tensor ("metadata_alphabet") it crashes:
```csharp
 Tensor op = graph.OperationByName("metadata_alphabet");
 var alphabet = op.numpy();
 ```
In the native API they use the **tstring** type and then perform some deserialization. I tried using the explicit string conversion and the **StringData** function. Both with no success. Any advice?

**Comment by Oceania2018** [comment]
@feliwir Check these [UnitTests](https://github.com/SciSharp/TensorFlow.NET/blob/master/test/TensorFlowNET.UnitTest/ManagedAPI/StringsApiTest.cs).
