### ISSUE TITLE
Documentation on what objects need to be disposed to release all memory

### ISSUE THREAD

**Issue by LukeBolly** [SciSharp/TensorFlow.NET#850]
Can we get some documentation on how to release all memory used by TF.NET after running some models?

So far, it seems like just about everything in the library needs to either be in a `using` or disposed manually. 

Graph related clean-up:
Graph objects: `_trainSession.graph.Dispose();`
Session objects: `_trainSession.Dispose();`

Data related clean-up:
NDArray objects

Is there anything else I'm missing?

**Comment by LukeBolly** [comment]
If it turns out that NDArrays need to be manually disposed, then allowing implicit casts can be quite dangerous because a method accepting an NDArray does not necessarily return it, so the handle to the object is immediately lost.

**Comment by Oceania2018** [comment]
`NDArray` will be disposed by GC automatically. `NDArray` is initialized by copying memory always. So it's allocation and dispose by itself (managed by GC).
You can test to allocate ndarray repeatly, then monitor the memeory consumption.

**Comment by LukeBolly** [comment]
Ah okay that is good to know, definitely simplifies things a bit. I'll leave this issue open however because currently the information on how to clean-up is scattered through open and closed issues.

**Comment by Oceania2018** [comment]
I can reproduce the issue but with no idea how to fix for this moment, need take more time to investiage.
Have you tried this way? https://github.com/SciSharp/SciSharp-Stack-Examples/blob/master/src/TensorFlowNET.Examples/ImageProcessing/InceptionArchGoogLeNet.cs

```csharp
using var graph = new Graph();
graph.Import(Path.Join(dir, pbFile));

using var sess = tf.Session(graph);
results = sess.run(output_operation.outputs[0], new FeedItem(input_operation.outputs[0], nd));
```

**Comment by LukeBolly** [comment]
graph.Import is for a frozen graph whilst Session.LoadFromSavedModel is for SavedModel format, the two are not interoperable unfortunately so it doesn't work for my use case.

**Comment by Oceania2018** [comment]
Why do you LoadFromSavedModel repeatly? I can be loaded once and shared the session in one process.

**Comment by LukeBolly** [comment]
Is the Session / Graph threadsafe? We have a multithreaded serving instance with concurrent calls happening, so I was following advice like here: https://github.com/keras-team/keras/pull/13116#discussion_r307488853

"Note that Keras models can't be guaranteed to be thread-safe. Consider having independent copies of the model in each thread for CPU inference."

**Comment by Oceania2018** [comment]
@LukeBolly It's not threadsafe.

**Comment by Oceania2018** [comment]
@LukeBolly Now it's stable now, it keeps in 46M cost.

![image](https://user-images.githubusercontent.com/1705364/132095824-f6bb4d8e-94c1-438a-aa8c-5d84c1ff91cd.png)

Please upgrade to v0.60.3.

**Comment by LukeBolly** [comment]
Great! I noticed you don't dispose the session / graph now, are they automatically cleaned up when the reference is removed?

**Comment by Oceania2018** [comment]
`using` syntax clean reference automatically.
