### ISSUE TITLE
Fix Documentation Examples

### ISSUE THREAD

**Issue by jimn-purecars** [SciSharp/TensorFlow.NET#851]
I am trying to follow the documentation examples, particularly:
https://github.com/SciSharp/TensorFlow.NET/blob/master/docs/source/NeuralNetwork.md

But there are several discrepancies between the code there and what is actually supported by the library today. Particularly, the MNIST data loading isn't done how the example shows, and `tf.get_variable` is used but does not exist, a call to `tf.matmul(x, W)` doesn't work because of a typing issue around `W`. There may be others. 

I don't know how to work around these discrepancies so I am pretty stuck unable to learn how to use the library for this purpose.

**Comment by Oceania2018** [comment]
Please follow the latest [sample source code](https://github.com/SciSharp/SciSharp-Stack-Examples/tree/master/src/TensorFlowNET.Examples/NeuralNetworks).
