### ISSUE TITLE
Linear Regression Eager

### ISSUE THREAD

**Issue by Maxtomouse** [SciSharp/TensorFlow.NET#855]
Operator '*' cannot be applied to operands of type 'ResourceVariable' and 'NDArray'	

I tried your first-page example but got this error on line:

var pred = W * X + b;

**Comment by t0b4cc0** [comment]
why is this closed? im foing the first example of this getting started.

https://scisharp.github.io/tensorflow-net-docs/#/essentials/introduction?id=getting-started

W * X does not compile

this is the error:

Error	CS0019	Operator '*' cannot be applied to operands of type 'ResourceVariable' and 'NDArray'

**Comment by ru-sh** [comment]
I have the same issue.
