### ISSUE TITLE
"System.NotImplementedException" when running Sess.run(fetch, feed)

### ISSUE THREAD

**Issue by PachiBlub** [SciSharp/TensorFlow.NET#863]
Hello TensorFlow.NET Team,

first of all, huge respect for the great effort from everyone involved building this awesome tool!

Unfortunately, I have an issue while trying to inference with a CNN, which has a 5 dimensional input-tensor and a 5 dimensional output-tensor.

Here is the basic code I am using to load the trained model and to start the inference:

```c#

            Sess = Session.LoadFromSavedModel(path);
            var graph = Sess.graph;

            InputTensor = graph.OperationByName("serving_default_input_1").outputs[0];
            OutputTensor = graph.OperationByName("StatefulPartitionedCall").outputs[0];

            FeedItem feed = new FeedItem(InputTensor, input);
            object fetch = OutputTensor;
            Sess.run(fetch, feed);
```

When running this code ```Sess.run(fetch, feed)``` creates an "System.NotImplementedException" from ```InitTensor()``` from this file:
https://github.com/SciSharp/TensorFlow.NET/blob/master/src/TensorFlowNET.Core/Tensors/Tensor.Creation.cs

I looked into ```InitTensor()``` an found that float tensors are only implemented up to ``` float[,,,] val => InitTensor(val, shape, dtype)``` (see the picture).

![Screenshot 2021-09-17 143420](https://user-images.githubusercontent.com/91184836/134349870-de6b6e86-91a0-4b38-8e9d-d93a4ff208f0.jpg)

So my 5 dimensional float input-/output- tensors seem to be not supported?

Is there a way to fix this?

I tried to simply add support for a 5dim tensor like this: 

``` float[,,,,] val => InitTensor(val, shape, dtype)```  

plus:

 ```
unsafe SafeTensorHandle InitTensor<T>(T[,,,,] array, Shape shape, TF_DataType dtype) where T : unmanaged
        {
            fixed (T* addr = &array[0, 0, 0, 0, 0])
                return TF_NewTensor(shape, dtype, addr);
        }

 ```

But when I try out the newly build TensorFlow.NET.dll, with this changes, then I get a "System.AccessViolationException" in   ```public Operation OperationByName(string operName)```  in https://github.com/SciSharp/TensorFlow.NET/blob/master/src/TensorFlowNET.Core/Graphs/Graph.Operation.cs

Has anyone dealt with a similiar issue before or has any ideas what I'm doing wrong?

Every help, clue or comment to solve the issue would be much appreciated.

**Comment by Oceania2018** [comment]
You can use `NDArray` to init like tests [here](https://github.com/SciSharp/TensorFlow.NET/blob/master/test/TensorFlowNET.UnitTest/Numpy/Array.Creation.Test.cs).

**Comment by PachiBlub** [comment]
@Oceania2018 Thank you for the quick response!

I tested the my adjusted code for ```InitTensor()``` with the mentioned UnitTest. 
However the tests don't show any problems.

So the creation of a 5 dimensional tensor seems to work. 👍 

But I still get the "System.AccessViolationException: attempted to read or write protected memory".

That is the StackTrace for this error:

"at Tensorflow.c_api.TF_GraphOperationByName(IntPtr graph, String oper_name)\r\n   at Tensorflow.Graph.OperationByName(String operName) in E:\\Voxel_Paper\\TensorFlow.NET-master\\TensorFlow.NET-master\\src\\TensorFlowNET.Core\\Graphs\\Graph.Operation.cs:line 67\r\n   at GeometryDetection.LoadModel(String path)"

It seems that the problem is [here](https://github.com/SciSharp/TensorFlow.NET/blob/master/src/TensorFlowNET.Core/Graphs/Graph.Operation.cs) in line 67:

```var handle = c_api.TF_GraphOperationByName(_handle, operName);```

Unfortunatly, I have no idea what to do with this error message.

Could it be something about the graph from my loaded model, which causes this error?

**Comment by Oceania2018** [comment]
Have you looked at the [examples repo](https://github.com/SciSharp/SciSharp-Stack-Examples)?
I can't tell what issue has if I can't reproduce the issue.

**Comment by PachiBlub** [comment]
Thanks for the comment.
I looked at the examples repo and changed the code to make at like the example code:

old:
```         
            Sess = Session.LoadFromSavedModel(path);
            var graph = Sess.graph;

            InputTensor = graph.OperationByName("serving_default_input_1").outputs[0];
            OutputTensor = graph.OperationByName("StatefulPartitionedCall").outputs[0];

            FeedItem feed = new FeedItem(InputTensor, input);
            object fetch = OutputTensor;
            Sess.run(fetch, feed);

```

new:

```
            var graph = new Graph();
            graph = graph.as_default();
            graph.Import(path + "saved_model.pb");
            InputTensor = graph.OperationByName("inputs").outputs[0];
            OutputTensor = graph.OperationByName("Identity").outputs[0];

            FeedItem feed = new FeedItem(InputTensor, input);
            object fetch = OutputTensor;
            Sess.run(fetch, feed);
```

the new code loads a frozen graph of a model without problems, but 

```
            Sess.run(fetch, feed);
```

throws a System.NullReferenceException "object reference not set to an instance of an object"

So I guess my model is the source of the issue?

**Comment by Oceania2018** [comment]
Does the model run in python?

**Comment by PachiBlub** [comment]
Yes, I train the model in python and do inference in python too. 
I then save the model as frozen graph in a .pb file.
I can also load the frozen model back in python and to do inference again.
But when I try to load the same frozen model in C# then I get the  "System.NullReferenceException "object reference not set to an instance of an object" when running ```Sess.run(fetch, feed); ```

**Comment by PachiBlub** [comment]
I have found the reason for my error. 
The session was not using the correct graph.
It works with:

 ```
using (var sess = tf.Session(graph))
            {
                result = sess.run(fetch, feed);
            }
```
