### ISSUE TITLE
TF.gradienttape () with tF.gradients

### ISSUE THREAD

**Issue by lijianxin520** [SciSharp/TensorFlow.NET#869]
Hello, I would like to ask that the value calculated using TF.gradienttape () is not the same as tF.gradients
![image](https://user-images.githubusercontent.com/47262889/137304853-a11406f6-cf3d-4909-9581-b099e4c144cc.png)
![image](https://user-images.githubusercontent.com/47262889/137305108-f78e73df-a4b2-4baf-9f14-e94f9589f5ff.png)

**Comment by Oceania2018** [comment]
Can you elaborate your issue?
