### ISSUE TITLE
is there any methods can implement [:,:,::-1] operate in python

### ISSUE THREAD

**Issue by dupeng0224** [SciSharp/TensorFlow.NET#883]
there is a ndarray like [[[2,3,4], [2,3,4], ...,[2,3,4]]]  i want convert it to [[[4,3,2], [4,3,2], ...,[4,3,2]]]。
 in python i can do [:,:,::-1], in C# or Tensorflow.Net is there any method to implement it?

**Comment by cross-hello** [comment]
You could use **NumSharp** NuGet package, then the game is just easy as [":,:,::-1"]
You can reference from here [NumSharp Slice](https://medium.com/scisharp/slicing-in-numsharp-e56c46826630)

**Comment by dupeng0224** [comment]
thanks for you answer, this is resolved my problem perfect.
