### ISSUE TITLE
Tensorflow.Numpy.NDArray constructor abnormal? 

### ISSUE THREAD

**Issue by cross-hello** [SciSharp/TensorFlow.NET#884]
Here are my code:
```C#
 static void Main(string[] args)
        {
            List<int> a =new List<int>{1,-1,-2,-3};
            Tensorflow.NumPy.NDArray aa=new Tensorflow.NumPy.NDArray(a.ToArray());// Point A
            Console.WriteLine("Hello World!");
            Console.Write("Hi");
        }
```
Point A will raise a error like this:
![image](https://user-images.githubusercontent.com/42733664/143828028-2d53c34b-1358-4f89-a806-318d9f7c3ca0.png)

But if I use `Tensorflow.NumPy.NDArray aa= (Tensorflow.NumPy.NDArray)a.ToArray();` in the position of Point A, the question solved. 
Now I want to know if it is some of my error or others cause it happen.

**Comment by Oceania2018** [comment]
@cross-hello Can you try this [sample](https://github.com/SciSharp/TensorFlow.NET/blob/b048b62436d4d6a439f9816ef56f3604622365ba/test/TensorFlowNET.UnitTest/Numpy/Array.Creation.Test.cs#L49)?

**Comment by cross-hello** [comment]
OK
I try: 
```C#
var x = Tensorflow.NumPy.np.array(1, 2, 3);
Tensorflow.NumPy.NDArray aa=new Tensorflow.NumPy.NDArray( x.ToArray<int>());
```
The code pass. Could you figure me why it happen?

**Comment by Oceania2018** [comment]
Fixed for next release.

**Comment by cross-hello** [comment]
Thank you~
