### ISSUE TITLE
System.NullReferenceException after calling tf.Variable

### ISSUE THREAD

**Issue by WaylandGod** [SciSharp/TensorFlow.NET#888]
![image](https://user-images.githubusercontent.com/6711913/144419042-66fb0a20-d548-487e-bd0a-da97b835f75a.png)
![image](https://user-images.githubusercontent.com/6711913/144419196-f62aae9d-b917-41d9-9b0d-720b4b17651d.png)
Is there any point needed to pay attention to when calling tf.Variable？

**Comment by Oceania2018** [comment]
@WaylandGod Please reference this [example](https://github.com/SciSharp/TensorFlow.NET/blob/e40be9338012df6f84ad923967df4b2ea7a7ab9b/test/TensorFlowNET.Graph.UnitTest/Basics/VariableTest.cs#L14).
