### ISSUE TITLE
there is no moveaxis method in np

### ISSUE THREAD

**Issue by dupeng0224** [SciSharp/TensorFlow.NET#891]
there is no moveaxis method in np, or other method can replace this method?

**Comment by Oceania2018** [comment]
Fixed for next release.
[np.moveaxis](https://github.com/SciSharp/TensorFlow.NET/blob/28157248871e2aec0d1a03c99876233801ce7b5d/test/TensorFlowNET.UnitTest/NumPy/Manipulation.Test.cs#L29)

**Comment by dupeng0224** [comment]
thanks!
