### ISSUE TITLE
Inference exception

### ISSUE THREAD

**Issue by FelixKras** [SciSharp/TensorFlow.NET#900]
This code worked on version 0.51 but broke when i upgraded to 0.61 (or any later than 0.51 ver)

I get "Cannot implicitly convert type 'Tensorflow.NumPy.NDArray[]' to 'NumSharp.NDArray[]"
at the marked line below

if I change output type than I get unimplemented exception at the ExecutionContext.cs

`using(Session sess = tf.Session(graph))
            {
                Tensor tensorNum = graph.OperationByName("num_detections");
                Tensor tensorBoxes = graph.OperationByName("detection_boxes");
                Tensor tensorScores = graph.OperationByName("detection_scores");
                Tensor tensorClasses = graph.OperationByName("detection_classes");
                Tensor imgTensor = graph.OperationByName("image_tensor");
                Tensor[] outTensorArr = new Tensor[] { tensorNum, tensorBoxes, tensorScores, tensorClasses };
                NDArray[] ndResults = sess.run(outTensorArr, new FeedItem(imgTensor, imgArr));  //<= this line
                results = BuildOutputData(ndResults, bmp.Size);
            }`

**Comment by Oceania2018** [comment]
Please remove `NumSharp` reference, you can use `TensorFlow.NumPy` instead of `NumSharp`.
