### ISSUE TITLE
TensorArray not working

### ISSUE THREAD

**Issue by diego-apellaniz** [SciSharp/TensorFlow.NET#903]
Hello,

aren't TensorArrays compatible with the last version 0.60.5? I get the following error when I try to create a TensorArray:
![image](https://user-images.githubusercontent.com/48953695/148407651-724ae59f-59ec-4455-a0c0-9d42310d38b1.png)

I'm trying to replicate this example:
https://www.tensorflow.org/tutorials/reinforcement_learning/actor_critic

thank you very much!

**Comment by Oceania2018** [comment]
https://github.com/SciSharp/TensorFlow.NET/blob/5a8b1cb59c25de4e3feca9c8e983f816755b1bac/test/TensorFlowNET.UnitTest/ManagedAPI/ArrayOpsTest.cs#L87
