### ISSUE TITLE
"Cannot access a disposed object." with multithreading 

### ISSUE THREAD

**Issue by Superpiffer** [SciSharp/TensorFlow.NET#912]
I have an issue with Tensorflow.NET 0.70.1 and a multithreading console application:
![image](https://user-images.githubusercontent.com/1334453/154437771-e5533571-5a28-48c7-be6d-682da5bc02fc.png)
I have the same problem with CPU or GPU native library, tensorflow 2.7.0.
Here you can find a sample project:
[TensorflowMultithreadingTest.zip](https://github.com/SciSharp/TensorFlow.NET/files/8087008/TensorflowMultithreadingTest.zip)

Note: I cannot use `using` for the inference because I need to reuse the same session, I don't think is feasible to create a new Session every time.
Note 2: Using `modelSession.Dispose()` at the end of the processing or using `GC.SuppressFinalize(modelSession)` after the declaration solve the problem, but I don't think it's the best solution.

**Comment by Superpiffer** [comment]
@Oceania2018 I have an update on this issue:
- I have this problem only on **.NET Framework 4.8**, not on .NET 5 or .NET 6 for some reason. I read online that maybe there are some difference in the finalize phase between .NET Framework and .NET Core: https://stackoverflow.com/a/44735403
- As a workaround, in my project I created a new Session in a wrapper class, in this class I disabled the finalizer with `GC.SuppressFinalize(_session)` and I manually deleted the session in the finalizer of the wrapper using a new Status object and not the static one: 
`~Session() => c_api.TF_DeleteSession(_session, _status.Handle)`

Wrapper class:
```csharp
internal class Session
{
    private readonly Tensorflow.Session _session;
    private readonly Status _status = new Status();
    public Graph graph => _session.graph;

    public Session(Graph graph, ConfigProto config)
    {
        _session = new Tensorflow.Session(graph, config, _status);
        GC.SuppressFinalize(_session);
    }

    public NDArray run(Tensor tensor, FeedItem item) => _session.run(tensor, item);
    public NDArray[] run(Tensor[] tensors, FeedItem item) => _session.run(tensors, item);

    ~Session() => c_api.TF_DeleteSession(_session, _status.Handle);
}
```

I don't know if this make sense, but apparently it works for now...

**Comment by Oceania2018** [comment]
@Superpiffer Is it possible to PR a patch with compile condition?

**Comment by Superpiffer** [comment]
> @Superpiffer Is it possible to PR a patch with compile condition?

I don't know exactly how to solve the problem. My understanding is that the _DisposeUnmanagedResources_ method always use the static _tf.Status_ instance to delete the session. For some reason, with .NET 4.8, at the last thread tf.Status is already disposed, causing the exception:
https://github.com/SciSharp/TensorFlow.NET/blob/c5cdf2c540922ac3abf38e53d1b00e4241802e35/src/TensorFlowNET.Core/Sessions/BaseSession.cs#L291-L295

My workaround simply suppress the finalizer of the Session instance, implementing a new finalizer without _tf.Status_.

Anyway a stupid solution like this one works no problem, but I don't know if can have other issues elsewhere:
`c_api.TF_DeleteSession(handle, c_api.TF_NewStatus());`

**Comment by Superpiffer** [comment]
@Oceania2018 I can close the issue, thanks. https://github.com/SciSharp/TensorFlow.NET/commit/a7c9a75954d219cb606042fcbfbeb1b176781d7e
