### ISSUE TITLE
Keras model.load_weights() gives FileLoadException for HDF5CSharp.dll

### ISSUE THREAD

**Issue by horseathesource** [SciSharp/TensorFlow.NET#915]
There is an issue with a call from load_weights to HDF5CSharp.dll. This is the error I get:

System.IO.FileLoadException: 'Could not load file or assembly 'HDF5CSharp, Version=1.12.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

HDF5CSharp is installed, and even updated to 1.12.7.0. The dll is in the correct path.
Any idea?

**Comment by snowaterr** [comment]
When I use 'save_weights', I got the same error as yours,  is there a solution?

**Comment by zhangjiechina001** [comment]
I also meet this problem，but when I use net.core3.1,could success save and save_weight.

**Comment by codingyoutub** [comment]
Did you find a solution?

**Comment by lionwu** [comment]
save  can use in net.core3.1.  Save and save_weight can't work on .net frameworks

**Comment by Oceania2018** [comment]
@lionwu Can you help check if the [HDF5-CSharp](https://www.nuget.org/packages/HDF5-CSharp/1.16.2) works in your side?

**Comment by lionwu** [comment]
@Oceania2018   no, still the same msg  "System.IO.FileLoadException: 'Could not load file or assembly 'HDF5CSharp, Version=1.12.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required." in .NetFramework 4.8.   But it's work on net.core3.1.  I am update HDF5CSharp to 1.16.2

**Comment by codingyoutub** [comment]
The save issue has been resolved, but load_model is still not working
