### ISSUE TITLE
    System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. 

### ISSUE THREAD

**Issue by sportbilly21** [SciSharp/TensorFlow.NET#923]
Hi 

I am getting an error while trying to run some unit tests.
"The type initializer for 'Tensorflow.Binding' threw an exception. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information."
My setup is VS2019. I am building for x64
Tensorflow.Net 0.70.1
Tensorflow.Keras 0.7.0
The issue comes either with the GPU or CPU Scisharp.Tensorflow.Redist latest versions. I have tried also older ones.
My target framework is 4.7 which I cannot easily changes as the project I am using Tensorflow is part of a bigger solution.
The dll's in the Build x64 Release folder are:
Tensorflow.Binding.dll
tensorflow.dll
Tensorflow.Keras.dll
Should I have also a Tensorflow.Net.dll in the folder and if yes why it is not building?
Many thanks

**Comment by AsakusaRinne** [comment]
Hey, I met the same problem as yours, which throws an error `System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.`. May I ask that if your code has something like `using(graph.as_default())`? I found it the reson of my problem, as illustrated in #970 . I'd like to fix it and I'll appreciate it if you tell me more about your problem.
