### ISSUE TITLE
Model.predict output refreshes at each step

### ISSUE THREAD

**Issue by MKhaeS** [SciSharp/TensorFlow.NET#928]
https://github.com/SciSharp/TensorFlow.NET/blob/56b4b189828c88bcf1697b04a15beee932a41e50/src/TensorFlowNET.Keras/Engine/Model.Predict.cs#L58

The output variable here gets reasssigned at each step in the cycle. The following fix worked for me:
`outputs = outputs is null ? batch_outputs : tf.concat(new Tensor[] { outputs, batch_outputs }, 0);`

**Comment by Oceania2018** [comment]
Please try latest release.
