### ISSUE TITLE
Use dotnet naming instead of python?

### ISSUE THREAD

**Issue by Regenhardt** [SciSharp/TensorFlow.NET#929]
Currently there are both PascalCase and snake_case in hete. How about changing the snake_case methods to PascalCase, so they also fit the dotnet ecosystem?

For example  
boolean_mask -> BooleanMask

**Comment by Oceania2018** [comment]
@Regenhardt For user level APIs we decided to keep thie `snake_case`, for internal implementation, we maybe would change to PascalCase to make .NET developers feel better.
