### ISSUE TITLE
Does TensorFlow.NET support .NET Framework 4.7.2

### ISSUE THREAD

**Issue by themightierdan** [SciSharp/TensorFlow.NET#936]
I created a simple winform project using .NET Framework 4.7.2, installed the TensorFlow.NET and the SciSharp.TensorFlow.Redist nugets.
I get BadImageFormatException in TensorFlow.Binding.  But when I create a .NET Core project, all work fine.  Am I missing something?

**Comment by Oceania2018** [comment]
TensorFlow.NET supports .netstandard 2.0. In theory it should support 4.7.2.

**Comment by kirilllapi** [comment]
It is necessary to change the project to x64

Menu Build → Configuration Manager
Creating a new x64 platform

![Image](https://github.com/user-attachments/assets/984deebc-1c98-4b85-a7a1-0e8a0f835fb8)
