### ISSUE TITLE
When will TensorFlow.NET support TensorFlow 2.9.x?

### ISSUE THREAD

**Issue by JustinWickMS** [SciSharp/TensorFlow.NET#945]
Or does the latest version already work with TensorFlow 2.9.x?

**Comment by chriskasturi2** [comment]
Same, question, I would like to know when it will be updated to support TensorFlow 2.9.x or at least 2.8.2.
Also is there a way to just build TensorFlow.NET manually to use one of these TensorFlow versions or to install a newer version of tensorflow and then configure TensorFlow.NET to use one of these new versions?

**Comment by JustinWickMS** [comment]
Is there someone we should assign this question to? Many people are waiting for newer TF support here an it would be useful to have even a vague roadmap.

**Comment by Oceania2018** [comment]
@JustinWickMS [Latest version](https://www.nuget.org/packages/TensorFlow.NET/0.70.2) support v2.10.x already. Sorry for the slow response due to limited spare time to work on this open source project.
