### ISSUE TITLE
Keras model.load_weights()  error

### ISSUE THREAD

**Issue by codingyoutub** [SciSharp/TensorFlow.NET#949]
There is an issue with a call from load_weights to HDF5CSharp.dll. This is the error I get:

System.IO.FileLoadException: 'Could not load file or assembly 'HDF5CSharp, Version=1.12.5.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

Is there any way to fix it?

**Comment by Oceania2018** [comment]
Please try the lastest release.
