### ISSUE TITLE
Multiple  output support

### ISSUE THREAD

**Issue by mshanak** [SciSharp/TensorFlow.NET#965]
I would ask if Tensorflow.net support multiple output?

In python version we can configure the model to have multiple outputs layer. in the following example, the network will have two outputs (`outputs=[y1_output, y2_output]`)

```python
def build_model():
    # Define model layers.
    input_layer = Input(shape=(len(train .columns),))
    first_dense = Dense(units='128', activation='relu')(input_layer)
    # Y1 output will be fed from the first dense
    y1_output = Dense(units='1', name='price_output')(first_dense)

    second_dense = Dense(units='128', activation='relu')(first_dense)
    # Y2 output will be fed from the second dense
    y2_output = Dense(units='1', name='ptratio_output')(second_dense)

    # Define the model with the input layer and a list of output layers
    model = Model(inputs=input_layer, outputs=[y1_output, y2_output])

    return model

```

Can we have such functionality in the .NET version?

**Comment by AdrienDeverin** [comment]
I'm not an expert, but to the best of my belief, it's not possible to get something like that. 
One idee to answer to your issue will be to use the Concatenate option :

output = Concatenate().Aplly(new Tensors(y1_output, y2_output));

but this mean your are obliged to concatenate your labels too before the training.

**Comment by Oceania2018** [comment]
Absolutely it can return multiple results. As you can see `Apply()` returns `Tensors`.

![image](https://user-images.githubusercontent.com/1705364/215642536-dbe22142-5dfc-4dae-89e7-1ce752f635fe.png)
