### ISSUE TITLE
Please update  SciSharp.TensorFlow.Redist-Linux-GPU 

### ISSUE THREAD

**Issue by ramon-garcia** [SciSharp/TensorFlow.NET#966]
The package in nuget.org for Tensorflow for Linux with GPU support is stuck at version 2.5.0
Please, could you update it?

I think that there is nothing special or difficult in publishing it.

**Comment by Oceania2018** [comment]
Actually it's difficult to put the Linux-GPU version to NuGet due to the 256M file size limitation. v2.10 package is about 480M.
You can download it from https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-2.10.0.tar.gz

**Comment by ramon-garcia** [comment]
Oh, I didn't know about that.

**Comment by ramon-garcia** [comment]
How can one use that tensorflow download? Just copying the shared libraries to the output folder, for instance, ProjectDir/bin/{Debug,Release}/net6.0 ?

**Comment by Oceania2018** [comment]
I think it should follow Linux dynamic library principles for .NET application.
