### ISSUE TITLE
Extract Key-Value Pairs from Image Document.

### ISSUE THREAD

**Issue by Saddamshq** [SciSharp/TensorFlow.NET#971]
Hi,

I want to prepare a project to collect the important detail from document (Like, Invoice Number, Date, Total Due, Seller Name etc.) as Key-value pairs.
We prepare the HOCR file from Image file using OCR engine (Tesseract).
Kindly help us how further proceed with input HOCR file to extract key-value pairs using "TensorFlow.Net".

Or other approach to prepare Key-value pairs using "TensorFlow.Net".

Thank in advance.
Regards,
Saddam

**Comment by Oceania2018** [comment]
Sorry this requirement it's out of scope. Welcome if you can contribute.
