### ISSUE TITLE
cannot load & save weights 

### ISSUE THREAD

**Issue by ammar-albush** [SciSharp/TensorFlow.NET#972]
cannot load & save weights after training the Model and the same applies to the save & load the Model Config  
could you please add this future in your next version of the library

**Comment by Oceania2018** [comment]
Save weights should works referenece [here](https://github.com/SciSharp/SciSharp-Stack-Examples/blob/ba3d3f108592a06705b323553416880bdc5a0756/src/TensorFlowNET.Examples/ImageProcessing/MnistCnnKerasSubclass.cs#L106).

**Comment by ammar-albush** [comment]
thanks for your reply, I have tried it now and it works fine but does model.load_weights also work ?

**Comment by Oceania2018** [comment]
`load_weights` should also work.
