### ISSUE TITLE
I've been training the model in Python for hours，How to load the trained model？

### ISSUE THREAD

**Issue by lindadamama** [SciSharp/TensorFlow.NET#977]

**Comment by AsakusaRinne** [comment]
If tensorflow.keras is used to train the model, you could save it to hdf5 format and load the weights with `Tensorflow.Keras.Model.load_weights`. I guess that you may want to use pb format model to load the whole network without re-define the network structure. We are sorry for the inconvenience as we currently do not have this feature available. However, it is in the works and we anticipate its completion within a month. Thank you for your patience.

Also, you can also train the model in tf.net keras and save it. The model saving of pb format has been implemented. #976

**Comment by Oceania2018** [comment]
@lindadamama You can save the model in python, and use `load` to restore model in `tf.net`, and make sure you've upgraded to `tf.net v0.100.4` and `tf.keras v0.10.4`.

**Comment by lucasramosdev** [comment]
> @lindadamama You can save the model in python, and use `load` to restore model in `tf.net`, and make sure you've upgraded to `tf.net v0.100.4` and `tf.keras v0.10.4`.
How to use tf.net? How i call this function? How i import?

I'm newbie using Tensorflow.NET and this documentation is so confusing for me.

Can you help me?
