### ISSUE TITLE
using static Tensorflow.KerasApi;  KerasApi没有这个命名空间是咋回事？

### ISSUE THREAD

**Issue by yilong789** [SciSharp/TensorFlow.NET#979]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0234	命名空间“Tensorflow”中不存在类型或命名空间名“KerasApi”(是否缺少程序集引用?)	ConsoleApp1	E:\C\机器学习\ConsoleApp1\Program.cs	2	活动

**Comment by AsakusaRinne** [comment]
正常来讲安装了tf.net是不会有这种情况的，请说下您的程序安装了哪些相关的nuget包以及版本，我帮忙看看

**Comment by yilong789** [comment]
不好意思，是我要少安装了一个包，TensorFlow.Keras  ，我刚才在安装这个包的时候，又报了这样的错误：严重性	代码	说明	项目	文件	行	禁止显示状态
错误		无法解析依赖项“PureHDF”。使用的源: 'nuget.org', 'Microsoft Visual Studio Offline Packages'。				
 我多次尝试安装依然失败！！！

**Comment by yilong789** [comment]
尝试降低版本到0.7.2后 可以正常安装！！！

**Comment by AsakusaRinne** [comment]
按理来讲当前tf.net最新版本就是0.70.2呀，可以问下您之前是安装的什么版本吗

**Comment by yilong789** [comment]
0.10.2

**Comment by AsakusaRinne** [comment]
我好像明白了，您之前是克隆代码用的master分支？

**Comment by yilong789** [comment]
在Nuget包管理工具里进行搜索TensorFlow.Keras这个包的时候 下拉框中第一个可以安装的版本就是0.10.2

**Comment by AsakusaRinne** [comment]
明白了，您说的是keras的版本，感谢回答 ：）

**Comment by yilong789** [comment]
好的，我刚才复制了示例代码，想跑一下，发现有两个变量不能进行运算。我是重新开一个issues进行提问还是在这里继续向您请教？

**Comment by AsakusaRinne** [comment]
您直接发在这里就行了

**Comment by yilong789** [comment]
好的感谢，// 线性回归 的 前向传播 公式
                    var pred = W * X + b;

这段代码，W和X不能在一起运算

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0019	运算符“*”无法应用于“ResourceVariable”和“NDArray”类型的操作数

**Comment by yilong789** [comment]
我想问加QQ群来着，发现QQ群被解散了，请问还有别的群吗？我发现tf的人都是python的，我想用.net跑机器学习。实在是学习资料太少了。

**Comment by AsakusaRinne** [comment]
> 好的感谢，// 线性回归 的 前向传播 公式 var pred = W * X + b;
> 
> 这段代码，W和X不能在一起运算
> 
> 严重性 代码 说明 项目 文件 行 禁止显示状态 错误 CS0019 运算符“*”无法应用于“ResourceVariable”和“NDArray”类型的操作数

我运行了一下项目首页的线性回归代码没复现出您的问题，我用的是tf.net 0.100.2和tf.keras 0.7.2以及SciSharp.TensorFlow.Redist-Windows-GPU，方便提供下您的完整代码吗？

**Comment by AsakusaRinne** [comment]
> 我想问加QQ群来着，发现QQ群被解散了，请问还有别的群吗？我发现tf的人都是python的，我想用.net跑机器学习。实在是学习资料太少了。

985366726，可以加一下这个群，之前的因为一些原因被封掉了，首页忘记更新了

**Comment by yilong789** [comment]
985366726  这个QQ群我没有搜到

**Comment by AsakusaRinne** [comment]
我问下群主这个群的情况，晚点回复您，代码的问题您可以先在这里问

**Comment by yilong789** [comment]
好的，我把包全部卸载了，然后重新安装了tf.net 0.100.2和tf.keras 0.7.2以及SciSharp.TensorFlow.Redist-Windows-GPU，例子用的是文档里的线性回归的例子。依旧报错：运算符“*”无法应用于“ResourceVariable”和“NDArray”类型的操作数

**Comment by yilong789** [comment]
> 

对的， W * X + b; w和x不能运算

**Comment by AsakusaRinne** [comment]
方便完整贴下您的代码吗？我感觉或许是一些细节地方改了一下导致的
