### ISSUE TITLE
Protobuf.Text

### ISSUE THREAD

**Issue by xianglai-meng** [SciSharp/TensorFlow.NET#988]
CnnInYourOwnData of TensorFlowNET.Examples  working on .netframework4.8,  
"return tf.train.freeze_graph(Config.Name + "\\MODEL", "model", new[]
            {
            "Train/Prediction/predictions",
            "Train/Prediction/prob"
        });"  
this code return error:"System.IO.FileLoadException:“未能加载文件或程序集“Protobuf.Text, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null”或它的某一个依赖项。需要强名称程序集。 (异常来自 HRESULT:0x80131044)”"。setup dependence by NuGet。

**Comment by Oceania2018** [comment]
Can you try to install this version? https://www.nuget.org/packages/Protobuf.Text/0.6.1

**Comment by xianglai-meng** [comment]
"Protobuf.Text"  0.5.0 and 0.6.1 version return same result.
![image](https://user-images.githubusercontent.com/15043557/221739996-a05ec6c7-0162-45fa-8125-08253e029940.png)

**Comment by xianglai-meng** [comment]
<img width="1204" alt="error" src="https://user-images.githubusercontent.com/15043557/221745524-ed33965b-3364-4758-9e68-d761e7b88d13.png">

**Comment by AsakusaRinne** [comment]
I guess that you signed your assembly (You can check it in your project properties). Could you please remove it and try again? @xianglai-meng 

Other ones had also met this problem several days ago, it's there anyway to solve it? @Oceania2018

**Comment by xianglai-meng** [comment]
@AsakusaRinne  it seems like fail.

**Comment by AsakusaRinne** [comment]
Does it still throw the same exception after removing the signing of assembly?

**Comment by xianglai-meng** [comment]
![image](https://user-images.githubusercontent.com/15043557/221787527-868072f1-6505-4efd-8f51-db14eac3667d.png)
???

**Comment by xianglai-meng** [comment]
@AsakusaRinne  Thank a lot!   update all packages version.   "Protobuf.Text" version(0.6.1) run successful finally.
